import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url)),run=process.env.QA_RUN_ID||'final-2',report=JSON.parse(fs.readFileSync(path.join(root,`checks/${run}/results.json`),'utf8'));
if(report.results.some(r=>r.status!=='pass'))throw Error('Latest browser run is not passing');
for(const f of ['BROWSER_REPORT.md','HANDOFF.md','captures/README.md']){let s=fs.readFileSync(path.join(root,f),'utf8');s=s.replaceAll('checks/repair-2/',`checks/${run}/`).replaceAll('(repair-2/',`(${run}/`).replaceAll('Current authority: `repair-2`',`Current authority: \`${run}\``).replaceAll('72 grouped','73 grouped').replaceAll('72 pass /','73 pass /');fs.writeFileSync(path.join(root,f),s);}
const changelog=fs.readFileSync(path.join(root,'CHANGELOG.md'),'utf8');if(!changelog.includes('Shop disclosure repair'))fs.appendFileSync(path.join(root,'CHANGELOG.md'),'\n5. Shop disclosure repair: visual inspection of repair-2 showed that the grid display rule overrode native hidden. Added an explicit hidden display rule and a real disclosure visibility regression. `final` passed 73 scenarios.\n6. Final refinement: editor labels/help/range scale with the text stress; completed/disabled equip and claim actions restore focus to a retained selection/disclosure. `final-2` passes 73 scenarios and is the latest authority. Earlier source and captures remain intact.\n');
const initial={status:'interrupted-harness-error',completeVerdict:false,reason:'Hash-only page.goto navigation reused previous lab and mode. Subsequent missing-element and stale-state checks were invalid; run interrupted through stdin Ctrl+C.',preserved:'Original source snapshot and actual failure screenshots remain in this directory and captures/initial.',knownObservedErrors:['Corrected modal test was still in previous Problem implementation','Radio note held apap instead of fresh ap','Subsequent lab selectors missing because lab was not reloaded'],counts:{passed:null,failed:null,unrun:null},limits:'No complete results/trace/capture manifest was emitted before interruption. Do not infer execution or success for remaining tests.'};
fs.writeFileSync(path.join(root,'checks/initial/INTERRUPTED.json'),JSON.stringify(initial,null,2)+'\n');
const all=[];function walk(dir){for(const ent of fs.readdirSync(dir,{withFileTypes:true})){const f=path.join(dir,ent.name);if(ent.isDirectory())walk(f);else if(ent.name!=='package-manifest.json')all.push({file:path.relative(root,f).split(path.sep).join('/'),bytes:fs.statSync(f).size,sha256:crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex')});}}walk(root);
fs.writeFileSync(path.join(root,'package-manifest.json'),JSON.stringify({version:'1.0.0',artifactType:'authored-original-demonstrators',baseCommit:report.baseCommit,latestBrowserRun:run,scope:'Additive package with minimal main README/research-index navigation. Source publication authorized; delivered commit identified in Git history.',files:all.sort((a,b)=>a.file.localeCompare(b.file))},null,2)+'\n');console.log(JSON.stringify({latestBrowserRun:run,files:all.length,bytes:all.reduce((a,x)=>a+x.bytes,0)}));
