import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url)),repo=path.resolve(root,'../..'),prefix='research/interaction_corrections_v1/',base='24e2fd2fcd8a0163b3560239b071a48d1188d7c8';
const git=(...args)=>execFileSync('git',args,{cwd:repo,encoding:'utf8',stdio:['ignore','pipe','pipe']}).trim(),sha=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');
const results=[];function check(name,fn){try{fn();results.push({name,status:'pass'});}catch(e){results.push({name,status:'fail',error:e.message});}}
const files=[];function walk(dir){for(const ent of fs.readdirSync(dir,{withFileTypes:true})){const f=path.join(dir,ent.name);if(ent.isDirectory())walk(f);else files.push(f);}}walk(root);
const report=JSON.parse(fs.readFileSync(path.join(root,'checks/final-2/results.json'),'utf8'));
check('changed-tracked-scope-only-package-and-two-navigation-files',()=>{const changed=git('diff','--name-only',base).split('\n').filter(Boolean);assert(changed.every(f=>f.startsWith(prefix)||['README.md','docs/RESEARCH_INDEX.md'].includes(f)));assert.equal(git('rev-parse','origin/main'),base);});
const navigation={};
check('new-readme-gallery-and-index-links-resolve',()=>{for(const relative of ['README.md','docs/RESEARCH_INDEX.md']){const f=path.join(repo,relative),text=fs.readFileSync(f,'utf8');navigation[relative]={workspaceSha256:sha(fs.readFileSync(f)),canonicalLfSha256:sha(Buffer.from(text.replace(/\r\n/g,'\n')))};const candidates=[...text.matchAll(/(?:href|src)="([^"]*interaction_corrections_v1[^\"]*)"/g)].map(m=>m[1]).concat([...text.matchAll(/\]\(([^)]*interaction_corrections_v1[^)]*)\)/g)].map(m=>m[1]));assert(candidates.length>=2);for(const target of candidates){assert(!/^https?:/.test(target));const local=path.resolve(path.dirname(f),target.split('#')[0]);assert(local.startsWith(root+path.sep));assert(fs.existsSync(local),relative+' -> '+target);}}const readme=fs.readFileSync(path.join(repo,'README.md'),'utf8');assert.equal([...readme.matchAll(/<img src="research\/interaction_corrections_v1\/captures\/final-2\//g)].length,6);assert(readme.includes('not unguided/guided AI experiments'));});
check('runtime-bytes-still-equal-73-scenario-authority',()=>{assert.equal(report.results.length,73);assert(report.results.every(r=>r.status==='pass'));assert.deepEqual(report.errors,[]);for(const [name,hash] of Object.entries(report.sourceHashes))assert.equal(sha(fs.readFileSync(path.join(root,name))),hash,name);});
check('bounded-secret-machine-path-and-conversation-id-scan',()=>{const patterns=[/\bgh[pousr]_[a-zA-Z0-9]{20,}\b/,/\bsk-(?:proj-)?[a-zA-Z0-9_-]{20,}\b/,/-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----/,/[A-Z]:[\\/](?:Users|Program Files)[\\/]/,/\b01[0-9a-f]{6}-[0-9a-f]{4}-7[0-9a-f]{3}-[0-9a-f]{4}-[0-9a-f]{12}\b/];for(const file of files.filter(f=>/\.(md|html|js|mjs|css|json)$/.test(f))){const text=fs.readFileSync(file,'utf8');for(const pattern of patterns)assert(!pattern.test(text),path.relative(root,file)+' matches '+pattern);}});
check('no-new-runtime-external-media-or-font-fetch',()=>{const html=fs.readFileSync(path.join(root,'index.html'),'utf8'),css=fs.readFileSync(path.join(root,'style.css'),'utf8');assert(!/<(?:img|script|link)\b[^>]*(?:src|href)="https?:/i.test(html));assert(!/@font-face|url\(['"]?https?:/i.test(css));const sources=JSON.parse(fs.readFileSync(path.join(root,'sources.json'),'utf8'));assert.equal(sources.rights.thirdPartyScreenshotsBundled,false);assert.equal(sources.rights.thirdPartyAssetsBundled,false);assert.equal(sources.rights.fontsBundled,false);});
fs.writeFileSync(path.join(root,'publication-checks.json'),JSON.stringify({checkedAt:new Date().toISOString(),integrationBase:base,scope:'Additive original package plus README.md/docs/RESEARCH_INDEX.md navigation',results,navigation,unrun:['Remote Git/HTTP receipt occurs separately after push','No native/sensory/engine/user-study check is implied by these package tests'],scanLimits:'Bounded patterns and runtime asset references only; not a legal/privacy certification.'},null,2)+'\n');
console.log(JSON.stringify({passed:results.filter(r=>r.status==='pass').length,failed:results.filter(r=>r.status==='fail').length,failures:results.filter(r=>r.status==='fail')}));if(results.some(r=>r.status==='fail'))process.exitCode=1;
