'use strict';
(() => {
  const $ = id => document.getElementById(id);
  const PARAMETERS = Object.freeze({version:'1.0.0',proposal:true,connectionDelayMs:900,desktopTarget:44,controllerTarget:60,touchTarget:48,desktopGap:10,controllerGap:12,portraitGap:12,landscapeGap:8});
  const items = [
    {id:'compass',name:'Survey compass',kind:'Gear',icon:'compass',description:'Keeps a bearing through the marsh. Equipped tool.',effect:'Equipped',locked:true},
    {id:'boots',name:'Marsh boots',kind:'Gear',icon:'boot',description:'Dry footing for the northern crossing.',effect:'Equip boots'},
    {id:'coat',name:'Field coat',kind:'Gear',icon:'coat',description:'A spare layer for the coast.',effect:'Equip coat'},
    {id:'lamp',name:'Signal lamp',kind:'Gear',icon:'lamp',description:'A portable lamp. One active tool at a time.',effect:'Equip lamp'},
    {id:'flask',name:'Water flask',kind:'Supplies',icon:'flask',description:'Restores 8 health once in this local fixture.',effect:'Drink once'},
    {id:'rope',name:'Climbing rope',kind:'Supplies',icon:'rope',description:'Reserved for a future route. Inspect only.',effect:'Route locked',locked:true},
    {id:'rations',name:'Trail rations',kind:'Supplies',icon:'flask',description:'Packed food. Inspect only in this example.',effect:'Inspect only',locked:true},
    {id:'map',name:'North marsh chart',kind:'Gear',icon:'map',description:'A chart of the survey area.',effect:'Equip chart'},
    {id:'marker',name:'Survey markers',kind:'Supplies',icon:'compass',description:'Marks a surveyed point. Inspect only.',effect:'Inspect only',locked:true},
    {id:'gloves',name:'Work gloves',kind:'Gear',icon:'boot',description:'Grip for the relay ladder.',effect:'Equip gloves'},
    {id:'battery',name:'Spare battery',kind:'Supplies',icon:'lamp',description:'Backup power. Inspect only.',effect:'Inspect only',locked:true},
    {id:'journal',name:'Weather journal',kind:'Gear',icon:'map',description:'Notes from the last survey.',effect:'Equip journal'}
  ];
  const initial = () => ({scene:'title',modal:null,connected:false,ready:false,loading:false,error:null,name:'Rowan',region:'Coast relay',attempts:0,selected:'compass',filter:'All',detail:false,bagScroll:0,empty:false,equipped:'compass',usedFlask:false,hp:92,surveys:0,moves:0,returnOrigin:'play',resumeScene:'play',restoreId:null,failNext:false,volume:70});
  let s = initial(), settings = {profile:window.innerWidth<600?'portrait':window.innerHeight<500&&window.innerWidth<1000?'landscape':'desktop',layout:'a',safe:0,annotate:true,compare:false,long:false,scale:1};
  let pendingTimer = null, requestGeneration = 0, playMode = false, trace = [], rects = [], lastPadButtons = [], lastPadDirection = '', padDirectionAt = 0;
  $('profile').value=settings.profile;
  const escapeHtml = v => String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const label = (normal,long) => escapeHtml(settings.long?long:normal);
  const id = (prefix,key) => `${prefix}-${key}`;
  function button(prefix,key,text,action=key,cls='',attrs='') { return `<button id="${id(prefix,key)}" data-action="${action}" class="${cls}" ${attrs}>${text}</button>`; }
  const icon = (kind,cls='') => {
    const paths = {compass:'<circle cx="16" cy="16" r="12"/><path d="m21 9-3 10-7 4 3-10Z"/>',boot:'<path d="M10 4h12v15l6 4v5H5v-8l5-3Z"/>',coat:'<path d="m11 4 5 4 5-4 8 7-4 8-4-3v12H11V16l-4 3-4-8Z"/>',lamp:'<path d="M11 7V5a5 5 0 0 1 10 0v2M8 9h16v18H8ZM6 29h20M12 13h8v10h-8Z"/>',flask:'<path d="M12 3h8v6l5 6v14H7V15l5-6ZM12 3v5h8M7 18h18"/>',rope:'<path d="M9 6c12-10 22 8 9 15C5 29 2 12 15 9s16 20 3 21M4 23l6 5"/>',map:'<path d="m3 7 9-4 9 4 8-4v23l-8 4-9-4-9 4ZM12 3v23M21 7v23"/>'};
    return `<svg class="item-icon ${cls}" viewBox="0 0 32 32" aria-hidden="true">${paths[kind]}</svg>`;
  };
  function terrain(){ return `<svg class="scene-art" viewBox="0 0 1000 600" preserveAspectRatio="xMidYMid slice" aria-hidden="true"><rect width="1000" height="600" fill="#657553"/><path d="M0 110 170 30 300 124 430 64 620 143 790 36 1000 110V0H0Z" fill="#a6b592"/><path d="M0 155 130 117 215 190 372 151 570 210 770 133 1000 195V600H0Z" fill="#536647"/><path d="M580 0c-170 140 220 180 60 280S400 450 510 600h145c-140-158 50-224 95-311C820 166 600 153 740 0Z" fill="#93b2a1"/><path d="M610 0c-160 136 210 190 62 300S445 455 572 600" fill="none" stroke="#c0d2b8" stroke-width="4"/><path d="M40 620 180 430 460 360 590 254 960 204" fill="none" stroke="#bdba8b" stroke-width="29"/><path d="M40 620 180 430 460 360 590 254 960 204" fill="none" stroke="#d3cda0" stroke-width="3" stroke-dasharray="8 16"/><path d="M657 219h60v75h-60Z" fill="#384a32"/><path d="m646 219 42-33 42 33Z" fill="#d0c599"/><path d="M672 251h24v43h-24Z" fill="#a9b38c"/><g fill="#314c34"><path d="m126 218 24-60 24 60h-15v25h-18v-25ZM250 277l29-69 29 69h-19v30h-20v-30ZM790 409l30-73 30 73h-19v29h-22v-29ZM870 345l24-60 24 60h-15v25h-18v-25ZM352 184l24-60 24 60h-15v25h-18v-25ZM903 522l24-60 24 60h-15v25h-18v-25Z"/></g><g fill="#8c9969"><ellipse cx="368" cy="487" rx="47" ry="17"/><ellipse cx="900" cy="145" rx="47" ry="17"/><ellipse cx="590" cy="465" rx="27" ry="12"/></g><circle cx="675" cy="255" r="10" fill="#ead797"/></svg><div class="scene-shade"></div>`; }
  function identity(){return `<div class="scene-identity"><span class="kicker">An original local fixture</span><div class="game-name">NORTH<br>MARSH</div><p>A field station at the edge of the coast.</p></div>`;}
  const hint = text => `<span class="hint">${settings.profile==='controller'?'A':text}</span>`;
  function menu(prefix){
    const p=prefix;
    if(s.scene==='title')return `${identity()}<section class="menu-panel" data-measure="01 Action group"><div class="menu-actions">${button(p,'enter',`${label('Enter station','Enter the northern field station')} ${hint('Enter')}`,'enter','primary','data-measure="02 Primary"')}${button(p,'title-settings',label('Settings','Audio and session settings'),'settings')}${button(p,'about','About this demo','about')}</div></section><div class="world-note"><strong>Coast relay</strong>Session-only progress.<br>No account required.</div>`;
    if(s.scene==='connect')return `${identity()}<section class="menu-panel form-panel panel-bg" data-measure="01 Connection panel"><h2>${s.loading?'Connecting…':s.error?'Connection failed':'Connect to station'}</h2><p>Local simulation · no server request</p><label for="${id(p,'name')}">Call sign<input id="${id(p,'name')}" name="callsign" maxlength="32" autocomplete="off" value="${escapeHtml(s.name)}" ${s.loading?'disabled':''}></label><label for="${id(p,'region')}">Route<select id="${id(p,'region')}" ${s.loading?'disabled':''}><option ${s.region==='Coast relay'?'selected':''}>Coast relay</option><option ${s.region==='Inland relay'?'selected':''}>Inland relay</option></select></label>${s.error?`<p class="error-message">${escapeHtml(s.error)}</p>`:''}${s.loading?'<div class="connecting-marker" aria-hidden="true"></div><p>One request is pending. Cancel is available.</p>':''}<div class="menu-actions">${button(p,'connect',s.loading?'Connecting…':s.error?'Retry connection':label('Connect as guest','Connect to the selected station as a guest'),'connect','primary',`${s.loading?'disabled':''} data-measure="02 Primary"`)}${button(p,'connection-back',s.loading?'Cancel connection':'Back to title','connection-back','', 'data-measure="03 Back"')}</div></section>`;
    if(s.scene==='lobby')return `${identity()}<section class="menu-panel form-panel panel-bg" data-measure="01 Readiness panel"><h2>Station lobby</h2><p>${escapeHtml(s.region)} · local guest</p><div class="route-meta"><strong>${escapeHtml(s.name)}</strong><p>${s.ready?'Ready ✓':'Not ready'}</p><small>Solo fixture. No other player is connected.</small></div><div class="menu-actions">${button(p,'ready',s.ready?'Unready':'Mark ready','ready')}${button(p,'join',label('Enter hub','Enter the field station hub'),'join','primary',`${s.ready?'':'disabled'} data-measure="02 Primary"`)}${button(p,'lobby-back','Back to connection','lobby-back','','data-measure="03 Back"')}</div></section>`;
    if(s.scene==='main')return `${identity()}<section class="menu-panel" data-measure="01 Main action rail"><h2>Field station</h2><p>${escapeHtml(s.name)} · survey ${s.surveys}/3</p><div class="menu-actions">${button(p,'resume',`${label('Resume survey','Resume the northern marsh survey')} ${hint('Enter')}`,'resume','primary','data-measure="02 Primary"')}${button(p,'bag','Inventory','bag')}${button(p,'main-settings','Settings','settings')}${button(p,'leave','Return to title','leave','danger','data-measure="03 Exit"')}</div></section><div class="world-note"><strong>Northern crossing</strong>Return to the same survey.<br>Inventory changes stay local.</div>`;
    return play(prefix);
  }
  function play(prefix){const touch=['portrait','landscape'].includes(settings.profile);return `<div class="actor" style="left:${43+Math.min(s.moves,10)}%" aria-hidden="true"></div><div class="hud-vitals" data-measure="01 Vitals"><strong>North crossing</strong>Survey ${s.surveys}/3 · HP ${s.hp}/100<span class="health" aria-hidden="true" style="background:linear-gradient(to right,#bacd89 ${s.hp}%,#5c7054 ${s.hp}%)"></span></div><div class="hud-map" data-measure="02 Minimap"><svg viewBox="0 0 100 70" aria-hidden="true"><path d="M30 0q60 15 20 40T75 70" fill="none" stroke="#bbd4af" stroke-width="12"/><path d="M5 65 55 35 95 20" fill="none" stroke="#e0dba6" stroke-width="3"/><circle cx="43" cy="42" r="4" fill="#fff0b1"/></svg></div>${button(prefix,'bag',`Inventory ${hint('I')}`,'bag','bag-trigger','data-measure="03 Bag opener"')}${button(prefix,'hub','Hub / Pause','hub','hub-trigger','data-measure="04 Hub"')}${button(prefix,'survey',s.surveys>=3?'Survey complete ✓':'Survey point','survey','primary survey-trigger',`${s.surveys>=3?'disabled':''} data-measure="05 Play action"`)}${touch?`<div class="touch-move" data-measure="06 Move zone">${button(prefix,'move-left','←','move-left','','aria-label="Move left"')}${button(prefix,'move-right','→','move-right','','aria-label="Move right"')}</div>`:''}${s.surveys>=3?'<div class="game-feedback">Survey complete. Return to the hub when ready.</div>':''}`;}
  function bag(prefix){
    const p=prefix, portrait=settings.profile==='portrait', filtered=s.empty?[]:items.filter(x=>s.filter==='All'||x.kind===s.filter), selected=items.find(x=>x.id===s.selected)||items[0];
    const longName = x => label(x.name,`${x.name} for the northern coast survey`);
    const grid=`<div class="bag-list" id="${id(p,'bag-list')}" ${portrait&&s.detail?'hidden':''}><div class="item-grid" role="group" aria-label="Inventory items">${filtered.map(x=>button(p,`item-${x.id}`,`${icon(x.icon)}<span>${longName(x)}</span><b>${s.equipped===x.id?'Equipped':x.kind}</b>`,`item:${x.id}`,'',`aria-pressed="${s.selected===x.id}" data-item="${x.id}"`)).join('')}</div>${filtered.length?'':`<p class="empty-state">${s.empty?'Your bag is empty. Restore the fixture below.':'No items in this category.'}</p>`}</div>`;
    const detail=filtered.length?`<section class="item-detail" data-measure="04 Item detail" ${portrait&&!s.detail?'hidden':''}>${button(p,'detail-back','← Back to items','detail-back','detail-back')}<div class="large-icon">${icon(selected.icon)}</div><h3>${longName(selected)}</h3><p>${escapeHtml(selected.description)}</p><p>${s.equipped===selected.id?'Currently equipped':s.usedFlask&&selected.id==='flask'?'Already consumed · HP restored':selected.kind}</p>${button(p,'use',s.usedFlask&&selected.id==='flask'?'Consumed':s.equipped===selected.id?'Equipped':selected.effect,'use','primary',`${selected.locked||(s.usedFlask&&selected.id==='flask')||s.equipped===selected.id?'disabled':''}`)}</section>`:'';
    return `<div class="overlay"><section class="dialog inventory-dialog" role="dialog" aria-modal="true" aria-labelledby="${id(p,'bag-title')}" data-measure="01 Inventory panel"><header class="dialog-head"><div><h2 id="${id(p,'bag-title')}">Field inventory</h2><p>Local survey paused · ${s.empty?0:12} items</p></div>${button(p,'close-bag','Close','close-bag','','data-measure="02 Close"')}</header><div class="bag-tabs" role="group" aria-label="Inventory categories" data-measure="03 Categories">${['All','Gear','Supplies'].map(x=>button(p,`filter-${x.toLowerCase()}`,x,`filter:${x}`,'',`aria-pressed="${s.filter===x}"`)).join('')}</div><div class="bag-body">${grid}${detail}</div><div class="bag-foot">${portrait?'Tap item → detail · Back → same item':settings.profile==='controller'?'D-pad: grid · LB/RB: category · B: close':'Arrows: grid · Q/E: category · Esc: close'}<br>Selection and list position survive Close.</div></section></div>`;
  }
  function simple(prefix){let title='',body='',buttons='',p=prefix;
    if(s.modal==='return'){title='Return to title?';body='Disconnect this local session. Survey progress stays in this tab; reload resets it.';buttons=button(p,'cancel-return','Keep playing','cancel-return','primary')+button(p,'confirm-return','Return to title','confirm-return','danger');}
    if(s.modal==='disconnect'){title=s.loading?'Reconnecting…':'Connection interrupted';body=`Local simulation. Your survey, equipment, and bag selection are retained.${s.error?' Retry failed; try again or return to title.':''}`;buttons=button(p,'retry',s.loading?'Reconnecting…':'Retry connection','retry','primary',s.loading?'disabled':'')+button(p,'cancel-retry',s.loading?'Cancel retry':'Return to title','cancel-retry','danger');}
    if(s.modal==='settings'){title='Session settings';body=`<label for="${id(p,'volume')}">Volume · <output id="${id(p,'volume-output')}">${s.volume}%</output><input id="${id(p,'volume')}" type="range" min="0" max="100" value="${s.volume}"></label><p>Demonstration setting only. This example has no audio.</p>`;buttons=button(p,'close-settings','Back','close-settings','primary');}
    if(s.modal==='about'){title='A placement proposal';body='North Marsh is original synthetic content. No login, server, purchase, or save service is connected.';buttons=button(p,'close-about','Back','close-about','primary');}
    return `<div class="overlay"><section class="dialog simple-dialog" role="dialog" aria-modal="true" aria-labelledby="${id(p,'modal-title')}" data-measure="01 Return / recovery"><h2 id="${id(p,'modal-title')}">${title}</h2>${s.modal==='settings'?body:`<p>${body}</p>`}${s.loading?'<div class="connecting-marker" aria-hidden="true"></div>':''}<div class="menu-actions" data-measure="02 Recovery actions">${buttons}</div></section></div>`;
  }
  function surface(prefix,layout){const st=settings.safe, side=settings.profile==='landscape'?st:0, stage=$(prefix==='a'?'stage-a':'stage-b');stage.className=`stage ${settings.profile} layout-${layout} ${prefix==='b'?'comparison':''}`;stage.dataset.scene=s.scene;stage.style.setProperty('--st',`${st}px`);stage.style.setProperty('--sb',`${st}px`);stage.style.setProperty('--sl',`${side}px`);stage.style.setProperty('--sr',`${side}px`);stage.style.setProperty('--unit',settings.scale);stage.innerHTML=`${terrain()}<div class="game-base" ${s.modal?'inert':''}>${menu(prefix)}<div class="screen-foot"><span>${s.scene==='play'?'Local survey active':'Local simulation · no server'}</span><span>${settings.profile==='controller'?'D-pad / A / B':settings.profile==='desktop'?'Keyboard + pointer':'Touch layout'}</span></div></div>${s.modal==='inventory'?bag(prefix):s.modal?simple(prefix):''}${settings.annotate?`<div class="safe-outline"></div><span class="safe-label">PROPOSED SAFE ${st}/${side}/${st}/${side} px</span><svg class="annotations" aria-hidden="true"></svg>`:''}`;}
  function render(focusKey){
    const previousFocus=document.activeElement?.id;
    surface('a',settings.layout);if(settings.compare)surface('b',settings.layout==='a'?'b':'a');$('alternate').hidden=!settings.compare;
    const title=s.modal==='inventory'?(s.detail?'Inventory · item detail':'Inventory'):s.modal==='return'?'Return confirmation':s.modal==='disconnect'?'Disconnect / retry':s.modal||s.scene;
    $('active-caption').textContent=`${settings.layout.toUpperCase()} · ${title[0].toUpperCase()+title.slice(1)}`;$('alternate-caption').textContent=`${settings.layout==='a'?'B':'A'} · same ${title}`;
    document.querySelectorAll('[data-inspect]').forEach(x=>x.setAttribute('aria-current',(x.dataset.inspect===s.modal||(!s.modal&&x.dataset.inspect===s.scene))?'step':'false'));
    inspector();
    requestAnimationFrame(()=>{
      const list=$('a-bag-list');if(list)list.scrollTop=s.bagScroll;
      const target=focusKey?$('a-'+focusKey):previousFocus?.startsWith('a-')?$(previousFocus):null;if(target&&!target.disabled&&!target.closest('[hidden]'))target.focus({preventScroll:true});else if(focusKey)$('stage-a').focus({preventScroll:true});
      measure();
    });
  }
  function inspector(){
    const isBag=s.modal==='inventory', isPlay=s.scene==='play', portrait=settings.profile==='portrait', controller=settings.profile==='controller',landscape=settings.profile==='landscape';
    $('rule-title').textContent=isBag?'Collection → detail → return':s.modal==='disconnect'?'Retain state; recover once':s.modal==='return'?'Cancel before leaving':s.scene==='connect'?'Context before connection':s.scene==='lobby'?'Readiness before entry':isPlay?'Keep the world legible':'One dominant next action';
    $('rule-summary').textContent=isBag?portrait?'A full sheet gives items room. Detail replaces the collection; Back restores the same item.':'The panel owns input. Inspect items beside a stable detail region; close restores the opener.':s.scene==='connect'?'Route and call sign precede the connection action. Loading holds its position and leaves Cancel available.':s.scene==='lobby'?'Ready and Enter are separate states. Entry stays disabled until the local guest is ready.':'Primary progression has the strongest fill. Exit remains explicit and requires confirmation.';
    $('anchor-note').textContent=isBag?portrait?'Inset full sheet; A: 3 columns, B: 2 larger columns.':controller?'A: wide 3-column grid; B: right-anchored 3-column grid.':landscape?'A: right split panel; B: full-width 4-column panel.':'A: right split panel; B: wider 4-column panel.':portrait?'A: actions above bottom safe inset; B: upper-middle stack.':controller?'A: central 60 px action stack; B: left 60 px stack.':landscape?'A: left action stack; B: center stack. Forms use a wider local panel.':'A: left action rail; B: centered vertical rail.';
    $('input-note').textContent=controller?'Keyboard stand-ins: arrows = D-pad, Enter = A, Esc = B, Q/E = LB/RB. Standard Gamepad API adapter included; physical hardware unrun.':portrait||landscape?'48 px proposed minimum targets. Tap alternatives for movement and inspection. Browser emulation cannot validate real thumb reach.':'44 px proposed minimum buttons. Tab/Enter/Space, grid arrows, I for inventory, Q/E for categories.';
    $('back-note').textContent=isBag?portrait?'Back detail → same selected item; Close → exact opener.':'Close / Esc → exact opener; selected item and scroll retained.':s.modal==='return'?'Cancel / Esc → Return-to-title opener. Confirm → title.':'Esc follows the active layer. Connection cancel invalidates its pending completion; form values remain.';
    $('hud-note').textContent=isBag?'Scrim blocks input to the world; local survey paused. This is our contract, not a claim about multiplayer games.':isPlay?'Vitals, map, bag opener, movement and survey zones are distinct. Orange boxes show measured extents.':'Scene is decorative; controls stay within the proposed safe bounds. Short frames allow panel scrolling.';
    $('tradeoff-note').textContent=isBag?portrait?'A shows more items; B gives longer names wider cells. Both keep Close and category controls stable.':'A leaves a visible world strip; B gives the collection more room. Both block world input.':portrait?'A puts common actions lower; B reduces travel from the title region. Neither thumb reach has been measured.':'A preserves scene visibility beside the rail; B concentrates focus centrally. Same data, order and state.';
  }
  function collect(stage){const r=stage.getBoundingClientRect(),scroller=stage.querySelector('.menu-panel');return [...stage.querySelectorAll('[data-measure]')].filter(e=>!e.closest('.game-base[inert]')&&!e.closest('[hidden]')).map(e=>{const b=e.getBoundingClientRect();return {target:e.dataset.measure,x:Math.round(b.x-r.x),y:Math.round(b.y-r.y),width:Math.round(b.width),height:Math.round(b.height),scrollContent:Boolean(scroller?.contains(e)&&scroller.scrollHeight>scroller.clientHeight)};});}
  function draw(stage,values){const svg=stage.querySelector('.annotations');if(!svg)return;svg.setAttribute('viewBox',`0 0 ${stage.clientWidth} ${stage.clientHeight}`);svg.innerHTML=values.map(v=>`<rect x="${v.x}" y="${v.y}" width="${v.width}" height="${v.height}"/><text x="${v.x+4}" y="${Math.max(13,v.y-4)}">${v.target.split(' ')[0]} · ${v.width}×${v.height}</text>`).join('');}
  function measure(){const stage=$('stage-a');rects=collect(stage);draw(stage,rects);if(settings.compare)draw($('stage-b'),collect($('stage-b')));$('dimensions').textContent=`${stage.clientWidth} × ${stage.clientHeight} rendered · ${settings.profile}`;$('geometry').innerHTML=rects.map(v=>`<tr><td>${escapeHtml(v.target)}</td><td>${v.x} / ${v.y}</td><td>${v.width} × ${v.height}${v.scrollContent?'*':''}</td></tr>`).join('');const actualGap=getComputedStyle(stage.querySelector('.menu-actions')||stage.querySelector('.item-grid')||stage).gap;$('collision-note').textContent=`Proposed target ≥ ${settings.profile==='controller'?60:settings.profile==='desktop'?44:48}px · measured group gap ${actualGap==='normal'?'—':actualGap}. ${rects.some(x=>x.scrollContent)?'* Action belongs to a scrollable panel.':''}`;}
  function record(action,message){trace.push({at:new Date().toISOString(),action,scene:s.scene,modal:s.modal,connected:s.connected,loading:s.loading,attempts:s.attempts,selected:s.selected,equipped:s.equipped,hp:s.hp,surveys:s.surveys,message});$('status').textContent=message;$('trace-count').textContent=`${trace.length} events`;$('trace').innerHTML=trace.slice(-40).map(x=>`<li>${escapeHtml(x.action)} → ${escapeHtml(x.modal||x.scene)} · ${escapeHtml(x.message)}</li>`).join('');}
  function cancelPending(){requestGeneration++;clearTimeout(pendingTimer);pendingTimer=null;s.loading=false;}
  function connect(retry=false){if(s.loading)return;if(!s.name.trim()){s.error='Enter a call sign before connecting.';render('name');record('validation','Call sign is required. No request started.');return;}s.name=s.name.trim();s.loading=true;s.error=null;s.attempts++;const generation=++requestGeneration,fail=s.failNext;s.failNext=false;$('fail-next').checked=false;record(retry?'retry':'connect',`Local connection attempt ${s.attempts} pending.`);render(retry?'cancel-retry':'connection-back');pendingTimer=setTimeout(()=>{if(generation!==requestGeneration)return;s.loading=false;pendingTimer=null;if(fail){s.error='Simulated relay unavailable. Your call sign and route are retained.';record('connection-failed','Local attempt failed; retry is available.');render(retry?'retry':'connect');return;}s.connected=true;s.error=null;if(retry){s.modal=null;s.scene=s.resumeScene;record('reconnected','Local session restored with survey and inventory state.');render(s.scene==='play'?'bag':'resume');}else{s.scene='lobby';s.ready=false;record('connected','Local connection complete. Mark ready before entering.');render('ready');}},PARAMETERS.connectionDelayMs);}
  function openBag(opener){if(s.modal)return;s.restoreId=opener;s.modal='inventory';s.detail=false;record('open-inventory','Local survey paused. Inventory owns input.');render(s.empty?'close-bag':`item-${s.selected}`);}
  function closeBag(){if(s.modal!=='inventory')return;const opener=s.restoreId||'bag';s.modal=null;s.detail=false;record('close-inventory','Inventory closed; selection retained; focus returns to its opener.');render(opener);}
  function restoreModal(){s.modal=null;record('close-overlay','Overlay closed; focus returns to its opener.');render(s.restoreId);}
  function action(key,opener){
    if(key.startsWith('item:')){const selected=key.split(':')[1];s.bagScroll=$('a-bag-list')?.scrollTop||0;s.selected=selected;s.detail=settings.profile==='portrait';record('select-item',`Selected ${items.find(x=>x.id===selected).name}.`);render(s.detail?'detail-back':`item-${selected}`);return;}
    if(key.startsWith('filter:')){s.filter=key.split(':')[1];s.detail=false;s.bagScroll=0;const filtered=items.filter(x=>s.filter==='All'||x.kind===s.filter);if(!filtered.some(x=>x.id===s.selected))s.selected=filtered[0]?.id||'compass';record('category',`${s.filter} category selected.`);render('filter-'+s.filter.toLowerCase());return;}
    switch(key){
      case 'enter':if(s.scene!=='title'||s.modal)return;s.scene='connect';record(key,'Choose a route and connect locally.');render('connect');break;
      case 'connect':if(s.scene==='connect'&&!s.modal)connect();break;
      case 'connection-back':cancelPending();s.error=null;s.scene='title';record(key,'Pending completion invalidated; title restored.');render('enter');break;
      case 'ready':if(s.scene!=='lobby')return;s.ready=!s.ready;record(key,s.ready?'Local guest ready. Entry is enabled.':'Local guest not ready. Entry is disabled.');render('ready');break;
      case 'join':if(s.scene!=='lobby'||!s.ready)return;s.scene='main';record(key,'Entered the local field station hub.');render('resume');break;
      case 'lobby-back':s.scene='connect';s.connected=false;s.ready=false;record(key,'Connection choices retained.');render('connect');break;
      case 'resume':if(s.scene!=='main')return;s.scene='play';record(key,'Survey active; local inventory and position retained.');render('bag');break;
      case 'hub':if(s.scene!=='play')return;s.scene='main';record(key,'Local survey paused at the hub.');render('resume');break;
      case 'bag':openBag(opener);break;
      case 'close-bag':s.bagScroll=$('a-bag-list')?.scrollTop||s.bagScroll;closeBag();break;
      case 'detail-back':s.detail=false;record(key,'Returned to the selected item and saved list position.');render('item-'+s.selected);break;
      case 'use':{const x=items.find(x=>x.id===s.selected);if(x.locked||s.equipped===x.id||(x.id==='flask'&&s.usedFlask))return;if(x.id==='flask'){s.usedFlask=true;s.hp=Math.min(100,s.hp+8);}else s.equipped=x.id;record('item-action',x.id==='flask'?'Water consumed once; HP restored.':`${x.name} equipped once.`);render(settings.profile==='portrait'?'detail-back':`item-${x.id}`);break;}
      case 'survey':if(s.scene!=='play'||s.modal||s.surveys>=3)return;s.surveys++;record(key,`Survey point ${s.surveys}/3 recorded locally.`);render('survey');break;
      case 'move-left':case 'move-right':if(s.scene!=='play'||s.modal)return;s.moves=Math.max(-10,Math.min(10,s.moves+(key==='move-left'?-1:1)));record(key,'Local actor moved.');render(key);break;
      case 'settings':case 'about':s.restoreId=opener;s.modal=key;record(key,'Opened local overlay.');render(key==='settings'?'volume':'close-about');break;
      case 'close-settings':case 'close-about':restoreModal();break;
      case 'leave':if(s.modal)return;s.restoreId=opener;s.returnOrigin=s.scene;s.modal='return';record(key,'Return confirmation opened; Keep playing receives focus.');render('cancel-return');break;
      case 'cancel-return':s.modal=null;s.scene=s.returnOrigin;record(key,'Return cancelled; current session retained.');render(s.restoreId||'leave');break;
      case 'confirm-return':if(s.modal!=='return')return;cancelPending();s.modal=null;s.scene='title';s.connected=false;s.ready=false;record(key,'Disconnected locally; session progress remains in this tab.');render('enter');break;
      case 'retry':if(s.modal==='disconnect')connect(true);break;
      case 'cancel-retry':if(s.loading){cancelPending();record(key,'Retry cancelled; recovery choices remain.');render('retry');}else{cancelPending();s.modal=null;s.scene='title';s.connected=false;s.ready=false;record(key,'Returned to title with progress retained.');render('enter');}break;
    }
  }
  function back(){if(s.modal==='inventory'){if(settings.profile==='portrait'&&s.detail)action('detail-back');else action('close-bag');}else if(s.modal==='return')action('cancel-return');else if(s.modal==='disconnect'){if(s.loading)action('cancel-retry');else{record('back-blocked','Choose Retry or Return to title; a disconnected world cannot resume.');$('a-retry')?.focus();}}else if(s.modal)restoreModal();else if(s.scene==='play')action('hub');else if(s.scene==='main')action('leave','leave');else if(s.scene==='lobby')action('lobby-back');else if(s.scene==='connect')action('connection-back');}
  function keyInput(event){if(!event.target.closest('#stage-a'))return;const editable=event.target.matches('input,select,textarea');if(event.key==='Escape'){event.preventDefault();back();return;}if(editable)return;const dialog=$('stage-a').querySelector('[role="dialog"]');if(event.key==='Tab'&&dialog){const focusable=[...dialog.querySelectorAll('button,input,select')].filter(e=>!e.disabled&&!e.closest('[hidden]'));const first=focusable[0],last=focusable.at(-1);if(event.shiftKey&&event.target===first){event.preventDefault();last?.focus();}else if(!event.shiftKey&&event.target===last){event.preventDefault();first?.focus();}return;}
    if(event.repeat&&['Enter',' ','i','I'].includes(event.key)){event.preventDefault();return;}
    if(event.key.toLowerCase()==='i'&&!s.modal&&['main','play'].includes(s.scene)){event.preventDefault();openBag('bag');return;}
    if(s.modal==='inventory'&&['q','e','Q','E'].includes(event.key)){event.preventDefault();const cats=['All','Gear','Supplies'],index=(cats.indexOf(s.filter)+(event.key.toLowerCase()==='q'?2:1))%3;action('filter:'+cats[index]);return;}
    if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home','End'].includes(event.key)){
      const grid=event.target.closest('.item-grid'),group=grid||event.target.closest('.menu-actions')||event.target.closest('.bag-tabs');if(!group)return;event.preventDefault();const controls=[...group.querySelectorAll('button')].filter(e=>!e.disabled),index=controls.indexOf(event.target);let next=index;
      if(grid){const cols=getComputedStyle(grid).gridTemplateColumns.split(' ').length;const row=Math.floor(index/cols);if(event.key==='ArrowLeft')next=Math.max(row*cols,index-1);if(event.key==='ArrowRight')next=Math.min(controls.length-1,row*cols+cols-1,index+1);if(event.key==='ArrowUp')next=Math.max(0,index-cols);if(event.key==='ArrowDown')next=Math.min(controls.length-1,index+cols);}
      else {if(['ArrowRight','ArrowDown'].includes(event.key))next=Math.min(controls.length-1,index+1);if(['ArrowLeft','ArrowUp'].includes(event.key))next=Math.max(0,index-1);}
      if(event.key==='Home')next=0;if(event.key==='End')next=controls.length-1;controls[next]?.focus();
    }
  }
  $('stage-a').addEventListener('click',e=>{const btn=e.target.closest('[data-action]');if(btn&&!btn.disabled&&!btn.closest('[inert]'))action(btn.dataset.action,btn.id.replace('a-',''));});
  $('stage-a').addEventListener('input',e=>{if(e.target.id==='a-name')s.name=e.target.value;if(e.target.id==='a-volume'){s.volume=Number(e.target.value);$('a-volume-output').textContent=s.volume+'%';}});
  $('stage-a').addEventListener('change',e=>{if(e.target.id==='a-region')s.region=e.target.value;});
  $('stage-a').addEventListener('scroll',e=>{if(e.target.id==='a-bag-list')s.bagScroll=e.target.scrollTop;measure();},true);
  document.addEventListener('keydown',keyInput);
  for(const name of ['profile','layout','safe','annotate','compare','long-labels','text-scale'])$(name).addEventListener('change',()=>{
    if(s.modal==='inventory')s.bagScroll=$('a-bag-list')?.scrollTop||s.bagScroll;
    settings={profile:$('profile').value,layout:$('layout').value,safe:Number($('safe').value),annotate:$('annotate').checked,compare:$('compare').checked,long:$('long-labels').checked,scale:Number($('text-scale').value)};
    if(settings.profile!=='portrait')s.detail=false;
    render();record('layout-change',`Same state retained: ${settings.profile}, layout ${settings.layout.toUpperCase()}, proposed inset ${settings.safe}px.`);
  });
  $('fail-next').addEventListener('change',()=>{s.failNext=$('fail-next').checked;});
  $('disconnect').addEventListener('click',()=>{if(!s.connected||s.loading){record('disconnect-unavailable','Connect first; disconnect is only available in an established local session.');return;}s.bagScroll=$('a-bag-list')?.scrollTop||s.bagScroll;s.resumeScene=s.scene;s.modal='disconnect';s.connected=false;s.error=null;record('disconnect','Local disconnect injected. Survey and inventory retained.');render('retry');});
  $('empty').addEventListener('click',()=>{s.empty=!s.empty;s.detail=false;record('fixture-density',s.empty?'Bag emptied for a proposed empty-state check.':'Original bag fixture restored.');render(s.modal==='inventory'?(s.empty?'close-bag':'item-'+s.selected):undefined);});
  $('reset').addEventListener('click',()=>{cancelPending();s=initial();trace=[];$('fail-next').checked=false;record('reset','Initial fixture restored. Layout settings retained.');render();});
  document.querySelectorAll('[data-inspect]').forEach(btn=>btn.addEventListener('click',()=>{cancelPending();s.error=null;const target=btn.dataset.inspect;if(['inventory','return'].includes(target)){s.scene='play';s.modal=target;s.restoreId='bag';s.returnOrigin='play';s.detail=false;}else{s.scene=target;s.modal=null;}s.connected=!['title','connect'].includes(s.scene);record('inspect-state','Proposed state opened directly for inspection; this shortcut is not evidence of completing the entry flow.');render(target==='inventory'?'item-'+s.selected:target==='return'?'cancel-return':undefined);}));
  function setPlay(value){playMode=value;document.body.classList.toggle('play-mode',value);$('exit-play').hidden=!value;render();record(value?'play-view':'workshop-view','Same fixture state retained; only the teaching frame changed.');if(value)$('stage-a').focus({preventScroll:true});else $('play-view').focus();}
  $('play-view').addEventListener('click',()=>setPlay(true));$('exit-play').addEventListener('click',()=>setPlay(false));
  $('export').addEventListener('click',()=>{measure();const data={version:PARAMETERS.version,artifactType:'authored-proposal',empiricalExperiment:false,sourceGameMeasurements:false,settings,state:{...s},viewport:{width:innerWidth,height:innerHeight,dpr:devicePixelRatio},renderedFrame:{width:$('stage-a').clientWidth,height:$('stage-a').clientHeight},geometryCssPx:rects,parameters:PARAMETERS,limits:['physical devices unrun','physical controller unrun','screen reader unrun','user approval pending']};const blob=new Blob([JSON.stringify(data,null,2)+'\n'],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='menu-placement-contract.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);record('export','Current authored placement contract downloaded locally.');});
  new ResizeObserver(measure).observe($('stage-a'));
  window.addEventListener('resize',measure);
  // This read-only snapshot supports QA; it cannot force progression or declare success.
  window.menuPlacementSnapshot=()=>({parameters:PARAMETERS,settings:{...settings},state:{...s},playMode,focus:document.activeElement?.id,geometry:rects.map(x=>({...x})),trace:trace.map(x=>({...x}))});
  function padLoop(now){if(settings.profile==='controller'&&document.activeElement?.closest('#stage-a')&&navigator.getGamepads){const pad=[...navigator.getGamepads()].find(x=>x&&x.mapping==='standard');if(pad){const pressed=pad.buttons.map(x=>x.pressed),rising=i=>pressed[i]&&!lastPadButtons[i];if(rising(0))document.activeElement?.click();if(rising(1))back();if(s.modal==='inventory'&&(rising(4)||rising(5))){const cats=['All','Gear','Supplies'];action('filter:'+cats[(cats.indexOf(s.filter)+(rising(4)?2:1))%3]);}const dir=pressed[12]?'ArrowUp':pressed[13]?'ArrowDown':pressed[14]?'ArrowLeft':pressed[15]?'ArrowRight':pad.axes[1]<-.6?'ArrowUp':pad.axes[1]>.6?'ArrowDown':pad.axes[0]<-.6?'ArrowLeft':pad.axes[0]>.6?'ArrowRight':'';if(dir&&(dir!==lastPadDirection||now-padDirectionAt>220)){document.activeElement.dispatchEvent(new KeyboardEvent('keydown',{key:dir,bubbles:true,cancelable:true}));padDirectionAt=now;}lastPadDirection=dir;lastPadButtons=pressed;}else{lastPadButtons=[];lastPadDirection='';}}requestAnimationFrame(padLoop);}
  render();requestAnimationFrame(padLoop);
})();
