import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
import {startServer} from './serve.mjs';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_CORE_PATH||'playwright-core');
const root=path.dirname(fileURLToPath(import.meta.url)),runId=process.env.QA_RUN_ID||'final';
assert.match(runId,/^[a-z0-9-]+$/);
const out=path.join(root,'checks',runId),captures=path.join(root,'captures',runId);
fs.mkdirSync(out,{recursive:true});fs.mkdirSync(captures,{recursive:true});
const frozenFiles=['index.html','app.js','style.css','browser-checks.mjs'];
const sourceHashes=frozenFiles.map(file=>({file,sha256:crypto.createHash('sha256').update(fs.readFileSync(path.join(root,file))).digest('hex')}));
fs.mkdirSync(path.join(out,'source'),{recursive:true});for(const file of frozenFiles)fs.copyFileSync(path.join(root,file),path.join(out,'source',file));
const server=await startServer(0),url=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});
const context=await browser.newContext({viewport:{width:1440,height:1000},deviceScaleFactor:1,acceptDownloads:true});
let page=await context.newPage();page.setDefaultTimeout(6000);
const errors=[],results=[],trace=[],images=[];
page.on('pageerror',e=>errors.push({type:'pageerror',message:e.message}));
page.on('console',m=>{if(m.type()==='error')errors.push({type:'console',message:m.text()});});
page.on('requestfailed',r=>errors.push({type:'requestfailed',message:r.failure()?.errorText,url:new URL(r.url()).pathname}));
const snap=()=>page.evaluate(()=>window.menuPlacementSnapshot());
async function settle(){await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));}
async function click(id){trace.push({action:'click',target:id});await page.locator('#'+id).click();await settle();}
async function key(value){trace.push({action:'key',value});await page.keyboard.press(value);await settle();}
async function fresh(profile='desktop',layout='a',viewport={width:1440,height:1000}){await page.setViewportSize(viewport);await page.goto(url);await page.locator('#profile').selectOption(profile);await page.locator('#layout').selectOption(layout);await page.locator('#annotate').uncheck();await settle();}
async function inspect(state){await page.locator(`[data-inspect="${state}"]`).click();await settle();}
async function connectToPlay(){await click('a-enter');await click('a-connect');await page.waitForFunction(()=>window.menuPlacementSnapshot().state.scene==='lobby');await settle();await click('a-ready');await click('a-join');await click('a-resume');}
async function shot(name,kind='stage'){await settle();const file=path.join(captures,name+'.png');if(kind==='stage')await page.locator('#stage-a').screenshot({path:file,animations:'disabled'});else {await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:file,fullPage:kind==='full',animations:'disabled'});}const bytes=fs.readFileSync(file),s=await snap();images.push({file:path.relative(root,file).replaceAll('\\','/'),kind:'synthetic_visual',observed_scope:'original_local_fixture',capture_mode:kind,viewport_css:page.viewportSize(),image_px:{width:bytes.readUInt32BE(16),height:bytes.readUInt32BE(20)},device_scale_factor:1,zoom_percent:100,profile:s.settings.profile,layout:s.settings.layout,scene:s.state.scene,modal:s.state.modal,selected:s.state.selected,sha256:crypto.createHash('sha256').update(bytes).digest('hex')});}
async function check(name,fn){try{const detail=await fn();results.push({name,status:'pass',detail:detail||'Expected result observed',snapshot:await snap()});console.log('pass: '+name);}catch(e){results.push({name,status:'fail',detail:e.message,snapshot:await snap().catch(()=>null)});console.log('FAIL: '+name+' · '+e.message);await shot('FAIL-'+name.replace(/[^a-z0-9-]/g,'-')).catch(()=>{});}fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(results,null,2)+'\n');}
async function geometry({hud=false,modal=false}={}){const value=await page.evaluate(({hud,modal})=>{const stage=document.getElementById('stage-a'),r=stage.getBoundingClientRect();const visible=e=>!e.closest('[inert]')&&!e.closest('[hidden]')&&e.getClientRects().length;const els=[...stage.querySelectorAll(hud?'.hud-vitals,.hud-map,.bag-trigger,.hub-trigger,.survey-trigger,.touch-move':modal?'.dialog':'.menu-panel')].filter(visible);const boxes=els.map(e=>{const b=e.getBoundingClientRect();return {name:e.className,x:b.left-r.left,y:b.top-r.top,w:b.width,h:b.height};});const collisions=[];for(let i=0;i<boxes.length;i++)for(let j=i+1;j<boxes.length;j++){const a=boxes[i],b=boxes[j];if(Math.min(a.x+a.w,b.x+b.w)-Math.max(a.x,b.x)>1&&Math.min(a.y+a.h,b.y+b.h)-Math.max(a.y,b.y)>1)collisions.push([a.name,b.name]);}return {w:r.width,h:r.height,boxes,collisions,overflow:document.documentElement.scrollWidth>document.documentElement.clientWidth,buttons:[...stage.querySelectorAll('button')].filter(visible).map(e=>({id:e.id,w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height})),badContent:[...stage.querySelectorAll('button,input,select,h2,h3,p')].filter(visible).filter(e=>e.scrollWidth>e.clientWidth+2).map(e=>({id:e.id,text:e.textContent.slice(0,45),w:e.clientWidth,sw:e.scrollWidth}))};},{hud,modal});assert.equal(value.overflow,false,'Page horizontal overflow');assert.deepEqual(value.collisions,[],'Unexpected overlapping HUD zones');for(const box of value.boxes){assert(box.x>=-1&&box.y>=-1,`Negative geometry: ${box.name}`);assert(box.x+box.w<=value.w+1&&box.y+box.h<=value.h+1,`Outside game frame: ${box.name}`);}const s=await snap(),target=s.settings.profile==='controller'?60:s.settings.profile==='desktop'?44:48;for(const b of value.buttons){assert(b.h>=target-1,`Short target ${b.id}: ${b.h}`);assert(b.w>=target-1,`Narrow target ${b.id}: ${b.w}`);}assert.deepEqual(value.badContent,[],'Text clips horizontally');return value;}
try {
 await check('entry-validation-loading-duplicate-cancel',async()=>{await fresh();await click('a-enter');await page.locator('#a-name').fill('');await click('a-connect');assert.equal((await snap()).state.attempts,0);assert.equal((await snap()).focus,'a-name');await page.locator('#a-name').fill('Rowan <test>');await page.locator('#a-region').selectOption('Inland relay');await page.locator('#a-connect').focus();await page.keyboard.down('Enter');await settle();assert.equal((await snap()).state.attempts,1);assert(await page.locator('#a-connect').isDisabled());await page.keyboard.down('Enter');await page.keyboard.up('Enter');await settle();assert.equal((await snap()).state.attempts,1);assert.equal((await snap()).state.loading,true);await shot('desktop-connection-loading');await click('a-connection-back');await page.waitForTimeout(1100);assert.equal((await snap()).state.scene,'title');await click('a-enter');assert.equal(await page.locator('#a-name').inputValue(),'Rowan <test>');assert.equal(await page.locator('#a-region').inputValue(),'Inland relay');});
 await check('entry-failure-retry-readiness-main-flow',async()=>{await page.locator('#fail-next').check();await click('a-connect');await page.waitForFunction(()=>Boolean(window.menuPlacementSnapshot().state.error));assert.equal((await snap()).state.scene,'connect');await shot('desktop-connection-failure');await click('a-connect');await page.waitForFunction(()=>window.menuPlacementSnapshot().state.scene==='lobby');await settle();assert(await page.locator('#a-join').isDisabled());await shot('desktop-lobby-unready');await click('a-ready');assert(!(await page.locator('#a-join').isDisabled()));await click('a-ready');assert(await page.locator('#a-join').isDisabled());await click('a-ready');await click('a-join');await shot('desktop-main');await click('a-resume');await geometry({hud:true});});
 await check('inventory-equip-once-use-once-close-focus',async()=>{await click('a-bag');assert(await page.locator('.game-base').getAttribute('inert')!==null);await click('a-item-boots');await click('a-use');assert.equal((await snap()).state.equipped,'boots');assert(await page.locator('#a-use').isDisabled());await key('Enter');assert.equal((await snap()).state.equipped,'boots');await click('a-filter-supplies');await click('a-item-flask');await click('a-use');assert.equal((await snap()).state.hp,100);assert.equal((await snap()).state.usedFlask,true);assert(await page.locator('#a-use').isDisabled());await shot('desktop-inventory-used');await click('a-close-bag');assert.equal((await snap()).focus,'a-bag');await click('a-bag');assert.equal((await snap()).state.selected,'flask');assert.equal((await snap()).state.filter,'Supplies');await key('Escape');assert.equal((await snap()).focus,'a-bag');});
 await check('inventory-modal-world-blocked-focus-trap',async()=>{await click('a-bag');const before=(await snap()).state.surveys;await page.locator('#a-survey').click({force:true});assert.equal((await snap()).state.surveys,before);await page.locator('#a-close-bag').focus();await key('Shift+Tab');assert.equal((await snap()).focus,'a-item-battery');await key('Tab');assert.equal((await snap()).focus,'a-close-bag');await key('Escape');});
 await check('disconnect-retry-fail-cancel-retain',async()=>{await click('a-survey');await click('disconnect');assert.equal((await snap()).state.modal,'disconnect');await key('Escape');assert.equal((await snap()).state.modal,'disconnect');await page.locator('#fail-next').check();await click('a-retry');assert(await page.locator('#a-retry').isDisabled());await page.waitForFunction(()=>Boolean(window.menuPlacementSnapshot().state.error));await shot('desktop-disconnect-retry-failed');await click('a-retry');await click('a-cancel-retry');await page.waitForTimeout(1100);assert.equal((await snap()).state.connected,false);await click('a-retry');await page.waitForFunction(()=>window.menuPlacementSnapshot().state.connected);await settle();assert.equal((await snap()).state.surveys,1);assert.equal((await snap()).state.equipped,'boots');assert.equal((await snap()).state.selected,'flask');assert.equal((await snap()).state.scene,'play');});
 await check('return-cancel-confirm-repeated',async()=>{await click('a-hub');await click('a-leave');assert.equal((await snap()).focus,'a-cancel-return');await key('Escape');assert.equal((await snap()).state.scene,'main');assert.equal((await snap()).focus,'a-leave');await click('a-leave');await shot('desktop-return');await click('a-confirm-return');assert.equal((await snap()).state.scene,'title');assert.equal((await snap()).state.connected,false);assert.equal((await snap()).state.surveys,1);await click('a-enter');await key('Space');assert.equal((await snap()).state.attempts,7);});
 await check('controller-spatial-grid-linear-actions-back',async()=>{await fresh('controller');await page.locator('#a-enter').focus();await key('ArrowDown');assert.equal((await snap()).focus,'a-title-settings');await key('ArrowUp');await key('Enter');await key('Space');await page.waitForFunction(()=>window.menuPlacementSnapshot().state.scene==='lobby');await settle();await key('Enter');await key('ArrowDown');assert.equal((await snap()).focus,'a-join');await key('Enter');await key('Enter');await key('i');assert.equal((await snap()).focus,'a-item-compass');await key('ArrowRight');assert.equal((await snap()).focus,'a-item-boots');await key('ArrowDown');assert.equal((await snap()).focus,'a-item-flask');await key('Enter');assert.equal((await snap()).state.selected,'flask');await key('q');assert.equal((await snap()).state.filter,'Supplies');await page.locator('#annotate').check();await page.locator('#a-item-flask').focus();await shot('controller-inventory-annotated');await key('Escape');assert.equal((await snap()).focus,'a-bag');});
 await check('alternate-same-fixture-read-only-measurements-export',async()=>{await fresh();await inspect('main');await page.locator('#compare').check();await page.locator('#annotate').check();await settle();const before=(await snap()).state;assert(await page.locator('#stage-b').getAttribute('inert')!==null);assert.equal(await page.locator('#stage-b .annotations rect').count(),3);await page.locator('#layout').selectOption('b');await settle();assert.deepEqual((await snap()).state,before);await shot('desktop-alternative-comparison','full');const dlPromise=page.waitForEvent('download');await click('export');const dl=await dlPromise;await dl.saveAs(path.join(out,'export-contract.json'));const data=JSON.parse(fs.readFileSync(path.join(out,'export-contract.json'),'utf8'));assert.equal(data.sourceGameMeasurements,false);assert.equal(data.empiricalExperiment,false);assert(data.geometryCssPx.length>=3);});
 for(const [profile,viewport] of [['desktop',{width:1165,height:747}],['controller',{width:1440,height:900}],['portrait',{width:390,height:844}],['landscape',{width:844,height:390}]])for(const layout of ['a','b']){
  await check(`${profile}-${layout}-full-flow-real-frame`,async()=>{await fresh(profile,layout,viewport);await page.locator('#safe').selectOption('24');await page.locator('#annotate').check();await shot(`${profile}-${layout}-workshop`,'full');await click('play-view');await geometry();await shot(`${profile}-${layout}-title`,'frame');await connectToPlay();await geometry({hud:true});await shot(`${profile}-${layout}-play`,'frame');await click('a-bag');await geometry({modal:true});await shot(`${profile}-${layout}-bag`,'frame');await click('a-item-boots');if(profile==='portrait'){assert.equal((await snap()).state.detail,true);await shot(`${profile}-${layout}-detail`,'frame');await click('a-detail-back');assert.equal((await snap()).focus,'a-item-boots');}await click('a-close-bag');assert.equal((await snap()).focus,'a-bag');await click('a-hub');await click('a-leave');await geometry({modal:true});await shot(`${profile}-${layout}-return`,'frame');await click('a-cancel-return');assert.equal((await snap()).focus,'a-leave');await click('exit-play');assert.equal((await snap()).state.scene,'main');});
 }
 await check('portrait-scroll-restoration-empty-rotate',async()=>{await fresh('portrait','a',{width:390,height:640});await click('play-view');await connectToPlay();await click('a-bag');await page.locator('#a-item-journal').click();assert.equal((await snap()).state.selected,'journal');await click('a-detail-back');const scroll=(await snap()).state.bagScroll;assert(scroll>0);await click('a-close-bag');await click('a-bag');assert.equal((await snap()).state.selected,'journal');assert.equal(await page.locator('#a-bag-list').evaluate(e=>e.scrollTop),scroll);await click('exit-play');await click('empty');assert.equal(await page.locator('.item-grid button').count(),0);assert.equal((await snap()).focus,'a-close-bag');await shot('portrait-empty-bag');await click('empty');await click('a-item-journal');await page.setViewportSize({width:844,height:390});await page.locator('#profile').selectOption('landscape');assert.equal((await snap()).state.selected,'journal');assert.equal((await snap()).state.detail,false);await geometry({modal:true});await shot('landscape-rotated-selection');});
 await check('deep-inset-long-labels-text-scale-short-height',async()=>{await fresh('landscape','b',{width:844,height:390});await page.locator('#safe').selectOption('44');await page.locator('#long-labels').check();await page.locator('#text-scale').selectOption('1.5');await click('play-view');await geometry();await shot('landscape-deep-inset-long-title','frame');await connectToPlay();await geometry({hud:true});await click('a-bag');await geometry({modal:true});await shot('landscape-deep-inset-scaled-bag','frame');});
 await check('portrait-small-width-text-scale',async()=>{await fresh('portrait','b',{width:320,height:740});await page.locator('#safe').selectOption('44');await page.locator('#long-labels').check();await page.locator('#text-scale').selectOption('1.5');await inspect('inventory');await geometry({modal:true});await shot('portrait-320-scaled-bag','full');await click('a-item-boots');await geometry({modal:true});await click('a-detail-back');await click('a-close-bag');assert.equal((await snap()).focus,'a-bag');});
 await check('reduced-motion-and-native-space-enter',async()=>{await fresh();await page.emulateMedia({reducedMotion:'reduce'});await page.locator('#a-enter').focus();await key('Space');assert.equal((await snap()).state.scene,'connect');await key('Enter');assert.equal(await page.locator('.connecting-marker').evaluate(e=>getComputedStyle(e,'::after').animationName),'none');await page.waitForFunction(()=>window.menuPlacementSnapshot().state.scene==='lobby');await settle();await key('Enter');await key('ArrowDown');await key('Space');assert.equal((await snap()).state.scene,'main');await key('Enter');await key('i');assert.equal((await snap()).state.modal,'inventory');});
 await check('input-shortcut-isolation-and-held-back-rearming',async()=>{await fresh('portrait');await click('a-enter');await page.locator('#a-name').focus();await key('i');assert.equal((await snap()).state.modal,null);assert((await page.locator('#a-name').inputValue()).includes('i'));await inspect('inventory');await click('a-item-boots');assert.equal((await snap()).state.detail,true);await page.keyboard.down('Escape');await settle();assert.equal((await snap()).state.detail,false);await page.keyboard.down('Escape');await settle();assert.equal((await snap()).state.modal,'inventory');await page.keyboard.up('Escape');await key('Escape');assert.equal((await snap()).state.modal,null);assert.equal((await snap()).state.scene,'play');});
 await check('controller-complete-outcome-without-tab-or-pointer',async()=>{await fresh('controller');await connectToPlay();await page.locator('#a-bag').focus();await key('ArrowDown');assert.equal((await snap()).focus,'a-survey');await key('Enter');assert.equal((await snap()).state.surveys,1);await key('ArrowUp');assert.equal((await snap()).focus,'a-bag');await key('Enter');await key('ArrowRight');await key('Enter');assert.equal((await snap()).state.selected,'boots');await key('x');assert.equal((await snap()).state.equipped,'boots');await key('q');assert.equal((await snap()).focus,'a-item-flask');await key('Enter');await key('x');assert.equal((await snap()).state.usedFlask,true);await key('x');assert.equal((await snap()).state.hp,100);await shot('controller-use-focus');await key('Escape');assert.equal((await snap()).focus,'a-bag');return 'Keyboard controller mappings complete survey, selection, equip, consumption, categories and Back without Tab.';});
 await check('browser-emulated-touch-full-flow',async()=>{const oldPage=page,touchContext=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,hasTouch:true,isMobile:true});page=await touchContext.newPage();try{await page.goto(url);const tap=async id=>{trace.push({action:'browser-emulated-touch-tap',target:id});await page.tap('#'+id);await settle();};await tap('a-enter');await tap('a-connect');await page.waitForFunction(()=>window.menuPlacementSnapshot().state.scene==='lobby');await settle();await tap('a-ready');await tap('a-join');await tap('a-resume');await tap('a-bag');await tap('a-item-boots');assert.equal((await snap()).state.detail,true);await tap('a-use');assert.equal((await snap()).state.equipped,'boots');await tap('a-detail-back');await tap('a-close-bag');assert.equal((await snap()).focus,'a-bag');await tap('play-view');await tap('a-move-right');assert.equal((await snap()).state.moves,1);await shot('touch-emulated-portrait-play','frame');return 'Playwright hasTouch + native tap; browser emulation, no physical phone.';}finally{await touchContext.close();page=oldPage;}});
 await check('local-links-and-no-external-runtime-assets',async()=>{await fresh();const links=await page.locator('a[href]').evaluateAll(es=>es.map(e=>e.getAttribute('href')).filter(x=>!x.startsWith('http')&&!x.startsWith('#')));for(const href of links){const response=await page.request.get(url+'/'+href);assert.equal(response.status(),200,href);}assert.equal(await page.locator('img[src^="http"],script[src^="http"],link[href^="http"]').count(),0);});
 await check('browser-console-clean',()=>assert.deepEqual(errors,[]));
} finally {
 const summary={runId,finished_at:new Date().toISOString(),browser:await browser.version(),platform:process.platform,node:process.version,passed:results.filter(x=>x.status==='pass').length,failed:results.filter(x=>x.status==='fail').length,total:results.length,errors,unrun:['physical touchscreen and safe areas','real software keyboard','physical controller','screen readers','Firefox / WebKit','200% browser zoom and native text settings','human usability participants','external visual review','original game hands-on current-build tests','user design approval'],claims:{authored:true,empiricalExperiment:false,publication:false,commit:false,push:false,siteEdit:false,pluginInstallation:false}};
 fs.writeFileSync(path.join(out,'summary.json'),JSON.stringify(summary,null,2)+'\n');fs.writeFileSync(path.join(out,'interaction-trace.json'),JSON.stringify(trace,null,2)+'\n');fs.writeFileSync(path.join(out,'screenshots.json'),JSON.stringify(images,null,2)+'\n');fs.writeFileSync(path.join(out,'source-hashes.json'),JSON.stringify(sourceHashes,null,2)+'\n');console.log(JSON.stringify(summary,null,2));await browser.close();await new Promise(r=>server.close(r));process.exitCode=summary.failed?1:0;
}
