import fs from 'node:fs';
import path from 'node:path';
import http from 'node:http';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_CORE_PATH||'playwright-core');
const root=path.dirname(fileURLToPath(import.meta.url));
const runId=process.env.QA_RUN_ID||'final';
const out=path.join(root,'checks',runId),captures=path.join(root,'captures',runId);
fs.mkdirSync(out,{recursive:true});fs.mkdirSync(captures,{recursive:true});
const types={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.md':'text/plain'};
const server=http.createServer((req,res)=>{const f=path.resolve(root,'.'+(new URL(req.url,'http://127.0.0.1').pathname==='/'?'/index.html':decodeURIComponent(new URL(req.url,'http://127.0.0.1').pathname)));if(!f.startsWith(root+path.sep)){res.writeHead(403).end();return;}fs.readFile(f,(e,data)=>{res.writeHead(e?404:200,{'Content-Type':types[path.extname(f)]||'application/octet-stream'});res.end(e?'Not found':data);});});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const url=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{}),args:['--disable-extensions']});
const context=await browser.newContext({viewport:{width:1165,height:747},deviceScaleFactor:1});
const page=await context.newPage();
const trace=[],results=[],captureRecords=[],errors=[];
page.on('pageerror',e=>errors.push({type:'pageerror',message:e.message}));page.on('console',m=>{if(m.type()==='error')errors.push({type:'console',message:m.text()});});page.on('requestfailed',r=>errors.push({type:'requestfailed',url:r.url(),message:r.failure()?.errorText}));
const snapshot=()=>page.evaluate(()=>window.gameplaySnapshot());
async function action(label,fn){trace.push({at:new Date().toISOString(),action:label});await fn();}
const click=id=>action(`click #${id}`,()=>page.locator('#'+id).click());
const key=k=>action(`key ${k}`,()=>page.keyboard.press(k));
async function fresh(tab='jump'){await action('reload initial fixture',()=>page.goto(url));if(tab!=='jump')await click('tab-'+tab);}
async function range(id,value){const min=Number(await page.locator('#'+id).getAttribute('min')),step=Number(await page.locator('#'+id).getAttribute('step')||1);await page.locator('#'+id).focus();await key('Home');for(let n=min;n<value;n+=step)await key('ArrowRight');}
async function done(){await page.waitForFunction(()=>!window.gameplaySnapshot().jump.running,{},{timeout:7000});}
async function check(name,fn){let result;try{const detail=await fn();result={case_id:name,status:'pass',actual_result:detail??'Expected result observed',snapshot:await snapshot()};}catch(e){result={case_id:name,status:'fail',actual_result:e.message,snapshot:await snapshot().catch(()=>null)};}result.at=new Date().toISOString();results.push(result);fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(results,null,2)+'\n');console.log(`${result.status}: ${name}`);}
async function capture(name){const state=await snapshot();for(const fullPage of [true,false]){const f=path.join(captures,name+(fullPage?'':'-frame')+'.png');await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:f,fullPage,animations:'disabled'});const bytes=fs.readFileSync(f);captureRecords.push({file:path.relative(root,f).replaceAll('\\','/'),kind:'synthetic_visual',observed_scope:'synthetic_fixture_only',capture_mode:fullPage?'full_page':'viewport_frame',viewport_css:page.viewportSize(),image_px:{width:bytes.readUInt32BE(16),height:bytes.readUInt32BE(20)},dpr:1,zoom_percent:100,state:state.tab,raw_file_sha256:crypto.createHash('sha256').update(bytes).digest('hex')});}}
try{
await check('jump-default-same-input-coyote',async()=>{await fresh();await click('replay');await done();let s=await snapshot();assert.equal(s.jump.input,660);assert.equal(s.jump.outcomes.strict.accepted,false);assert.equal(s.jump.outcomes.assisted.accepted,true);await capture('desktop-jump-coyote');return 'Same input 660 ms; strict rejects, assisted accepts.';});
await check('jump-coyote-disabled-repeat-reset',async()=>{await click('coyote');await click('replay');await done();let s=await snapshot();assert(!s.jump.outcomes.strict.accepted&&!s.jump.outcomes.assisted.accepted);await click('replay');await done();assert.deepEqual((await snapshot()).jump.outcomes,s.jump.outcomes);await click('reset-jump');assert.equal((await snapshot()).jump.t,0);assert.equal(await page.evaluate(()=>document.activeElement.id),'reset-jump');});
await check('jump-coyote-boundary-100-and-110',async()=>{await range('jump-offset',100);await click('replay');await done();assert((await snapshot()).jump.outcomes.assisted.accepted);await range('jump-offset',110);await click('replay');await done();assert(!(await snapshot()).jump.outcomes.assisted.accepted);});
await check('jump-buffer-held-release-disabled',async()=>{await page.locator('#jump-case').selectOption('buffer');await click('replay');await done();let s=await snapshot();assert.equal(s.jump.input,540);assert.equal(s.jump.outcomes.assisted.at,600);assert(!s.jump.outcomes.strict.accepted);await capture('desktop-jump-buffer');await click('hold');await click('replay');await done();assert.equal((await snapshot()).jump.outcomes.assisted.reason,'Released before landing');await click('hold');await click('buffer');await click('replay');await done();assert(!(await snapshot()).jump.outcomes.assisted.accepted);});
await check('jump-buffer-boundary-120-and-130',async()=>{await click('buffer');await range('jump-offset',-120);await click('replay');await done();assert((await snapshot()).jump.outcomes.assisted.accepted);await range('jump-offset',-130);await click('replay');await done();assert.equal((await snapshot()).jump.outcomes.assisted.reason,'Buffer expired');});
await check('jump-event-frame-equal-grounded',async()=>{await range('jump-offset',0);await click('replay');await done();let s=await snapshot();assert(s.jump.outcomes.strict.accepted&&s.jump.outcomes.assisted.accepted);assert.equal(s.jump.outcomes.strict.at,s.jump.outcomes.assisted.at);});
await check('jump-native-live-keyboard-held-buffer',async()=>{await fresh();await page.locator('#jump-case').selectOption('buffer');await click('live');await page.waitForFunction(()=>window.gameplaySnapshot().jump.t>=510);await action('hold Space',()=>page.keyboard.down('Space'));await page.waitForFunction(()=>window.gameplaySnapshot().jump.t>=650);await action('release Space',()=>page.keyboard.up('Space'));await done();let s=await snapshot();assert(s.jump.input>=480&&s.jump.input<600);assert(s.jump.releasedAt>=600);assert(s.jump.outcomes.assisted.accepted&&!s.jump.outcomes.strict.accepted);return `Native hold captured input ${s.jump.input}, release ${s.jump.releasedAt}.`;});
await check('jump-live-no-input-cancel-settings-tab-suspend',async()=>{await click('live');await done();assert.equal((await snapshot()).jump.input,null);await click('live');await key('Escape');assert(!(await snapshot()).jump.running);await click('live');await click('coyote');assert(!(await snapshot()).jump.running);await click('live');await click('tab-interaction');assert(!(await snapshot()).jump.running);});
await check('target-mode-preserves-scene-and-aim',async()=>{await fresh('interaction');let before=await snapshot();assert.equal(before.interaction.selected,'relay');await click('mode-exact');let after=await snapshot();assert.deepEqual(after.interaction.aim,before.interaction.aim);assert.equal(after.interaction.selected,null);await click('interact');assert((await page.locator('#status').textContent()).includes('failed'));await click('mode-nearby');assert.equal((await snapshot()).interaction.selected,'relay');});
await check('target-cycling-retention-occlusion',async()=>{await click('next-target');assert.equal((await snapshot()).interaction.selected,'pod');await click('closer');assert.equal((await snapshot()).interaction.selected,'pod');await click('object-relay');assert.equal((await snapshot()).interaction.selected,'relay');await click('block-relay');assert.notEqual((await snapshot()).interaction.selected,'relay');assert((await page.locator('#state-relay').textContent()).includes('Occluded'));await capture('desktop-target-occluded');await click('block-relay');await click('object-relay');assert.equal((await snapshot()).interaction.selected,'relay');});
await check('target-range-stale-completion-repeat-cancel',async()=>{await click('reset-interaction');await click('mode-exact');await click('object-cache');assert.equal((await snapshot()).interaction.selected,null);await click('interact');assert.equal((await snapshot()).interaction.completed.length,0);await click('closer');await click('closer');assert.equal((await snapshot()).interaction.selected,'cache');await click('interact');assert((await snapshot()).interaction.completed.includes('cache'));await click('interact');assert.equal((await snapshot()).interaction.completed.length,1);await click('mode-nearby');await key('Escape');assert.equal((await snapshot()).interaction.selected,null);await click('next-target');assert((await snapshot()).interaction.selected);});
await check('target-keyboard-arrows-switch-interact',async()=>{await click('reset-interaction');await page.locator('#selection-stage').focus();await key('ArrowRight');assert.equal((await snapshot()).interaction.aim.x,48);await key('n');await key('e');assert.equal((await snapshot()).interaction.completed.length,1);});
await check('feedback-independent-shapes-and-states',async()=>{await fresh('feedback');await click('expose');assert.equal((await snapshot()).feedback.hp,100);await click('take-hit');let s=await snapshot();assert.equal(s.feedback.hp,80);assert.equal(s.feedback.exposure,35);assert.equal(await page.locator('#damage-cue').isVisible(),true);assert.equal(await page.locator('#awareness-cue').isVisible(),true);await capture('desktop-feedback-both');await click('hide');assert.equal((await snapshot()).feedback.hp,80);assert.equal((await snapshot()).feedback.exposure,0);await click('expose');await click('expose');await click('expose');assert.equal((await snapshot()).feedback.exposure,100);assert(await page.locator('#expose').isDisabled());await key('Escape');assert.equal((await snapshot()).feedback.exposure,0);assert.equal((await snapshot()).feedback.hp,80);});
await check('feedback-directions-zero-effects-adjustment',async()=>{await page.locator('#damage-direction').selectOption('behind');await page.locator('#observer-direction').selectOption('front');await click('take-hit');let s=await snapshot();assert.equal(s.feedback.lastHit,'behind');assert.equal(s.feedback.observerDir,'front');assert.equal(await page.evaluate(()=>document.getAnimations().length),0);await range('shake',60);await range('flash',40);await page.waitForFunction(()=>!window.gameplaySnapshot().feedback.cooling);await click('take-hit');assert.equal((await snapshot()).feedback.shake,60);assert.equal((await snapshot()).feedback.flash,40);assert(await page.evaluate(()=>document.getAnimations().length)>0);});
await check('feedback-down-repeat-restore',async()=>{await click('restore');for(let i=0;i<5;i++){await click('take-hit');if(i<4)await page.waitForFunction(()=>!window.gameplaySnapshot().feedback.cooling);}assert.equal((await snapshot()).feedback.hp,0);assert(await page.locator('#take-hit').isDisabled());await click('restore');assert.equal((await snapshot()).feedback.hp,100);assert.equal((await snapshot()).feedback.shake,60);await page.locator('#feedback-stage').focus();await key('e');await key('c');assert.equal((await snapshot()).feedback.exposure,0);});
await check('feedback-reduced-motion-suppresses-effects',async()=>{await page.emulateMedia({reducedMotion:'reduce'});await click('take-hit');assert((await snapshot()).feedback.effectsSuppressed);assert.equal(await page.evaluate(()=>document.getAnimations().length),0);assert((await page.locator('#motion-note').textContent()).includes('suppressed'));await page.emulateMedia({reducedMotion:'no-preference'});});
await check('recovery-cancel-checkpoint-availability-focus',async()=>{await fresh('recovery');await click('die');assert.equal((await snapshot()).recovery.pile.amount,125);assert.equal(await page.evaluate(()=>document.activeElement.id),'return-home');await key('Escape');assert(!(await snapshot()).recovery.menu);assert(!(await snapshot()).recovery.alive);assert.equal(await page.evaluate(()=>document.activeElement.id),'choose-return');await click('choose-return');await click('return-relay');await click('relay-available');assert.equal((await snapshot()).recovery.checkpoint,'home');assert(await page.locator('#return-relay').isDisabled());await click('confirm-return');assert.equal((await snapshot()).recovery.x,14);assert.equal(await page.evaluate(()=>document.activeElement.id),'advance');});
await check('recovery-too-far-success-repeat-and-redeath',async()=>{await click('recover');assert.equal((await snapshot()).recovery.wallet,0);assert((await page.locator('#status').textContent()).includes('too far'));await click('advance');await click('advance');await click('advance');assert.equal((await snapshot()).recovery.x,74);await click('recover');assert.equal((await snapshot()).recovery.wallet,125);assert.equal((await snapshot()).recovery.pile,null);await capture('desktop-recovery-recovered');await click('recover');assert.equal((await snapshot()).recovery.wallet,125);await click('die');assert.equal((await snapshot()).recovery.pile.amount,125);assert.equal((await snapshot()).recovery.lost,0);});
await check('recovery-precollection-redeath-replacement-conservation',async()=>{await click('reset-recovery');await click('die');await click('return-relay');await click('confirm-return');assert.equal((await snapshot()).recovery.x,38);await click('find-shards');assert.equal((await snapshot()).recovery.wallet,25);assert(await page.locator('#find-shards').isDisabled());await click('die');let s=await snapshot();assert.equal(s.recovery.lost,125);assert.equal(s.recovery.pile.amount,25);assert.equal(s.recovery.wallet,0);await capture('desktop-recovery-lost');await click('confirm-return');await click('advance');await click('recover');assert.equal((await snapshot()).recovery.wallet,25);assert.equal((await snapshot()).recovery.lost,125);});
await check('recovery-zero-wallet-redeath-removes-old-drop',async()=>{await click('reset-recovery');await click('die');await click('confirm-return');await click('die');assert.equal((await snapshot()).recovery.pile,null);assert.equal((await snapshot()).recovery.lost,125);await click('confirm-return');await page.locator('#recovery-stage').focus();await key('ArrowRight');await key('d');assert(!(await snapshot()).recovery.alive);});
await check('tabs-native-arrow-home-end-focus-and-disclosure',async()=>{await fresh();await page.locator('#tab-jump').focus();await key('ArrowRight');assert.equal((await snapshot()).tab,'interaction');assert.equal(await page.evaluate(()=>document.activeElement.id),'tab-interaction');await key('End');assert.equal((await snapshot()).tab,'recovery');await key('Home');assert.equal((await snapshot()).tab,'jump');await page.locator('summary').focus();await key('Enter');assert(await page.locator('details').getAttribute('open')!==null);await key('Space');assert.equal(await page.locator('details').getAttribute('open'),null);});
await check('jump-live-button-native-enter-hold-release',async()=>{await fresh();await page.locator('#jump-case').selectOption('buffer');await click('live');await page.locator('#jump-press').focus();await page.waitForFunction(()=>window.gameplaySnapshot().jump.t>=510);await page.keyboard.down('Enter');await page.waitForFunction(()=>window.gameplaySnapshot().jump.t>=650);await page.keyboard.up('Enter');await done();let s=await snapshot();assert(s.jump.input<600&&s.jump.releasedAt>=600);assert(s.jump.outcomes.assisted.accepted);await click('live');await page.locator('#jump-press').focus();await page.waitForFunction(()=>window.gameplaySnapshot().jump.t>=510);await page.keyboard.down('Space');await page.keyboard.up('Space');await done();assert.equal((await snapshot()).jump.outcomes.assisted.reason,'Released before landing');});
await check('jump-lane-containment-and-desktop-actions',async()=>{await fresh();await click('replay');await done();await page.evaluate(()=>scrollTo(0,0));const geometry=await page.evaluate(()=>({clipping:[...document.querySelectorAll('.jump-lane')].map(e=>getComputedStyle(e).overflow),bottom:document.querySelector('#reset-jump').getBoundingClientRect().bottom,label:document.querySelector('#label-assist').textContent}));assert.deepEqual(geometry.clipping,['hidden','hidden']);assert(geometry.bottom<=747,`Actions bottom ${geometry.bottom} exceeds desktop frame`);assert.equal(geometry.label,'Ledge grace on');return geometry;});
await check('feedback-legend-rendered-contrast',async()=>{await fresh('feedback');await click('take-hit');const colors=await page.locator('.feedback-readout').evaluate(e=>{let c=getComputedStyle(e);return {foreground:c.color,background:c.backgroundColor};});function lum(rgb){const a=rgb.match(/[\d.]+/g).slice(0,3).map(Number).map(n=>n/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return .2126*a[0]+.7152*a[1]+.0722*a[2];}const a=lum(colors.foreground),b=lum(colors.background),ratio=(Math.max(a,b)+.05)/(Math.min(a,b)+.05);assert(ratio>=4.5);return {...colors,contrast_ratio:ratio,scope:'One rendered text/background pair; not a full contrast audit.'};});
for(const viewport of [{width:1165,height:747},{width:768,height:900},{width:390,height:844},{width:844,height:390},{width:320,height:720}]){
 for(const study of ['jump','interaction','feedback','recovery'])await check(`layout-${viewport.width}x${viewport.height}-${study}`,async()=>{await page.setViewportSize(viewport);await fresh(study);if(study==='jump'){await click('replay');await done();}if(study==='feedback'){await click('expose');await click('take-hit');}if(study==='recovery'){await click('die');}
 const bounds=await page.evaluate(()=>({width:document.documentElement.clientWidth,scroll:document.documentElement.scrollWidth,stage:(()=>{let r=document.querySelector('.stage').getBoundingClientRect();return {x:r.x,width:r.width,height:r.height};})(),bad:[...document.querySelectorAll('button,select,input')].filter(e=>e.getBoundingClientRect().width&&((e.getBoundingClientRect().left<0)||(e.getBoundingClientRect().right>document.documentElement.clientWidth+1))).map(e=>e.id)}));assert.equal(bounds.width,bounds.scroll);assert.deepEqual(bounds.bad,[]);if([1165,390,844].includes(viewport.width))await capture(`${viewport.width===1165?'desktop':viewport.width===390?'narrow':'landscape'}-${study}`);return bounds;});
}
await check('narrow-native-touch-emulation-all-four',async()=>{await page.setViewportSize({width:390,height:844});const touch=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:1,hasTouch:true,isMobile:true});const p=await touch.newPage();p.on('pageerror',e=>errors.push({type:'touch-pageerror',message:e.message}));await p.goto(url);
 async function tap(id){const box=await p.locator('#'+id).boundingBox();await p.locator('#'+id).scrollIntoViewIfNeeded();const b=await p.locator('#'+id).boundingBox();trace.push({action:`native touchscreen tap #${id}`});await p.touchscreen.tap(b.x+b.width/2,b.y+b.height/2);}
 await tap('replay');await p.waitForFunction(()=>!window.gameplaySnapshot().jump.running);assert((await p.evaluate(()=>window.gameplaySnapshot())).jump.outcomes.assisted.accepted);
 await tap('tab-interaction');await tap('object-relay');await tap('interact');assert((await p.evaluate(()=>window.gameplaySnapshot())).interaction.completed.includes('relay'));
 await tap('tab-feedback');await tap('expose');await tap('take-hit');let f=(await p.evaluate(()=>window.gameplaySnapshot())).feedback;assert.equal(f.hp,80);assert.equal(f.exposure,35);
 await tap('tab-recovery');await tap('die');await tap('return-relay');await tap('confirm-return');await tap('advance');await tap('advance');await tap('recover');assert.equal((await p.evaluate(()=>window.gameplaySnapshot())).recovery.wallet,125);
 await touch.close();return 'Actual Chromium touch events in mobile emulation; physical touch remains unrun.';});
await check('source-links-http-bytes-and-console',async()=>{await page.setViewportSize({width:1165,height:747});await fresh();const response=await fetch(url+'/parameters.json');assert.deepEqual(await response.json(),JSON.parse(fs.readFileSync(path.join(root,'parameters.json'),'utf8')));for(const study of ['jump','interaction','feedback','recovery']){await click('tab-'+study);const link=await page.locator('details a').getAttribute('href');assert(link.startsWith('https://'));await page.locator('details summary').click();assert(await page.locator('details a').isVisible());}assert.deepEqual(errors,[]);return 'Source destinations match verified originals; no app/console/request errors in tested session.';});
} finally {
 const report={run_at:new Date().toISOString(),run_id:runId,base_commit:'bdd696ffcde02808759fc009ac2dfa26e3834b5c',environment:{browser:browser.version(),platform:process.platform,dpr:1,zoom_percent:100,input_modes:['native mouse','native keyboard','Chromium touch emulation']},raw_file_sha256:Object.fromEntries(['index.html','app.js','style.css','parameters.json'].map(f=>[f,crypto.createHash('sha256').update(fs.readFileSync(path.join(root,f))).digest('hex')])),results,errors,limits:['No physical touch or phone safe-area testing','No controller or screen-reader testing','No true browser 200% zoom','No source-game runtime testing','No user study or design approval','No deployment, installation, commit or push']};
 fs.writeFileSync(path.join(out,'browser-report.json'),JSON.stringify(report,null,2)+'\n');fs.writeFileSync(path.join(out,'interaction-trace.json'),JSON.stringify(trace,null,2)+'\n');fs.writeFileSync(path.join(out,'capture-manifest.json'),JSON.stringify(captureRecords,null,2)+'\n');await browser.close();await new Promise(resolve=>server.close(resolve));
 console.log(JSON.stringify({passed:results.filter(r=>r.status==='pass').length,failed:results.filter(r=>r.status==='fail').length,captures:captureRecords.length,errors:errors.length}));if(results.some(r=>r.status==='fail'))process.exitCode=1;
}
