import {fileURLToPath} from 'node:url';
process.chdir(path.dirname(fileURLToPath(import.meta.url)));
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {pathToFileURL} from 'node:url';
const require=createRequire(import.meta.url);
const playwright=require(process.env.PLAYWRIGHT_CORE_PATH||'playwright-core');
const run=process.argv[2]||'final';
const dir=path.join('checks',run);fs.mkdirSync(dir,{recursive:true});
const result={run,started:new Date().toISOString(),capture_mode:'Full-page PNG; viewport is CSS layout viewport, not image height',browser:'Real headless Chromium via installed Chrome; no application mocks',environment:{platform:process.platform,browser:'Installed Chromium; executable configured outside the report'},viewports:[{width:1165,height:747},{width:390,height:844}],tests:[],console_errors:[],external_requests:[],limitations:['Not a native phone','No screen reader','No human participant usability test','No full WCAG certification','No real transaction/backend','CSS reflow probe is not native browser zoom']};
const measures=[];
const browser=await playwright.chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||undefined});
const context=await browser.newContext({viewport:result.viewports[0]});
const page=await context.newPage();
page.on('pageerror',e=>result.console_errors.push(e.message));page.on('console',m=>{if(m.type()==='error')result.console_errors.push(m.text())});
await context.route('**/*',route=>{const url=route.request().url();if(/^https?:/.test(url)){result.external_requests.push(url);return route.abort();}return route.continue();});
await page.goto(pathToFileURL(path.resolve('index.html')).href);
async function test(name,fn){try{await fn();result.tests.push({name,passed:true});}catch(e){result.tests.push({name,passed:false,error:e.message});console.log('FAIL '+name+': '+e.message.slice(0,240));}}
const snapshot=()=>page.evaluate(()=>window.flowDemo.getSnapshot());
async function reset(){await page.evaluate(()=>window.flowDemo.resetAll());}
async function choose(id){const mobile=(await page.viewportSize()).width<=700;if(mobile)await page.locator('#example-select').selectOption(id);else await page.locator(`[data-example="${id}"]`).click();}
async function action(id){await page.locator(`#screen [data-action="${id}"]`).filter({visible:true}).first().click();}
async function capture(purpose,stage){const vp=page.viewportSize();await page.screenshot({path:path.join(dir,`${purpose}-${stage}-${vp.width}x${vp.height}.png`),fullPage:true});const geometry=await page.evaluate(()=>{const rect=el=>{const r=el.getBoundingClientRect();return {x:+r.x.toFixed(2),y:+r.y.toFixed(2),width:+r.width.toFixed(2),height:+r.height.toFixed(2)}};const pick=selector=>{const e=document.querySelector(selector);return e?rect(e):null};return {actual_route:window.flowDemo.getSnapshot().current,screen:pick('#screen'),appbar:pick('#screen .appbar'),heading:pick('#view-title'),layout:pick('#screen .catalog,#screen .product-detail,#screen .cart-layout,#screen .search-layout,#screen .course-layout,#screen .forum-layout,#screen .work-layout,#screen .booking-layout'),primary_buttons:[...document.querySelectorAll('#screen .primary')].filter(e=>e.getBoundingClientRect().width).map(e=>({label:e.textContent.trim(),disabled:e.disabled,...rect(e)})),horizontal_overflow:document.documentElement.scrollWidth>innerWidth,min_visible_control_height:Math.min(...[...document.querySelectorAll('#screen button,#screen select,#screen input:not([type=radio]),#screen textarea')].filter(e=>e.getBoundingClientRect().width).map(e=>e.getBoundingClientRect().height)),css_pixels:true};});measures.push({purpose,stage,viewport:vp,...geometry});assert.equal(geometry.horizontal_overflow,false,'horizontal overflow at '+purpose+'/'+stage);}
for(const vp of result.viewports){await page.setViewportSize(vp);for(const id of ['shopping','information','course','community','work','booking'])await test(`${id} entry render ${vp.width}x${vp.height}`,async()=>{await reset();await choose(id);await capture(id,'entry');});}
await page.setViewportSize(result.viewports[0]);
await test('Shopping variants, quantity boundaries, repeated review, Back, remove/undo',async()=>{await reset();await action('shop-product:bookends');await action('shop-add');await action('shop-add');await action('shop-variant:Walnut');await action('shop-add');await action('shop-cart');let s=(await snapshot()).states.shopping;assert.equal(s.cart.length,2);assert.equal(s.cart[0].qty,2);await action('shop-qty:0:-1');assert.equal((await snapshot()).states.shopping.cart[0].qty,1);assert.equal(await page.locator('[data-action="shop-qty:0:-1"]').isDisabled(),true);await action('shop-review');await capture('shopping','review');await action('shop-finish');assert.equal(await page.locator('[data-action="shop-finish"]').isDisabled(),true);await action('shop-cart');await action('shop-qty:0:1');assert.equal((await snapshot()).states.shopping.reviewed,false);await action('shop-review');await action('shop-cart');await action('shop-remove:1');await action('shop-remove:0');assert.equal((await snapshot()).states.shopping.cart.length,0);await capture('shopping','empty');await action('shop-undo');assert.equal((await snapshot()).states.shopping.cart.length,1);assert.equal(await page.locator('[data-action="shop-undo"]').count(),0);await action('shop-list');await page.goBack();assert.equal((await snapshot()).current.view,'cart');await action('shop-list');await action('shop-product:bookends');for(let i=0;i<8;i++)await action('shop-add');s=(await snapshot()).states.shopping;assert.ok(s.cart.every(x=>x.qty<=5));});
await test('Information query/topic, article sections, Back, zero results and clear',async()=>{await reset();await choose('information');await page.locator('#query').fill('seeds');await page.locator('#category').selectOption('Garden');await page.locator('#query').press('Enter');await action('info-article:seeds');await page.locator('[data-section="section-keep"]').click();assert.equal(await page.evaluate(()=>document.activeElement.id),'section-keep');await capture('information','article');await action('info-back');assert.equal(await page.locator('#query').inputValue(),'seeds');assert.equal(await page.locator('#category').inputValue(),'Garden');assert.equal(await page.evaluate(()=>document.activeElement.id),'result-seeds');await action('info-article:seeds');await page.goBack();assert.equal(await page.locator('#query').inputValue(),'seeds');await page.locator('#query').fill('zzzz');await page.locator('#query').press('Enter');await capture('information','empty');await action('info-clear');assert.equal((await snapshot()).states.information.category,'All');assert.equal(await page.locator('.result-list li').count(),3);});
await test('Course native radio arrows, incorrect/revisit/retry/correct/continue',async()=>{await reset();await choose('course');await action('course-practice');assert.equal(await page.locator('#check-answer').isDisabled(),true);await page.locator('input[value="0"]').check();await page.locator('#check-answer').click();assert.equal((await snapshot()).states.course.feedback,'incorrect');await capture('course','incorrect');await action('course-lesson');await action('course-feedback');assert.equal((await snapshot()).states.course.attempts,1);await action('course-retry');assert.equal((await snapshot()).states.course.answer,null);await page.locator('input[value="0"]').focus();await page.keyboard.press('ArrowDown');assert.equal((await snapshot()).states.course.answer,1);await page.locator('#check-answer').click();assert.equal((await snapshot()).states.course.feedback,'correct');assert.equal((await snapshot()).states.course.attempts,2);await action('course-continue');assert.deepEqual((await snapshot()).states.course.completed,[true,false]);await action('course-finish');assert.deepEqual((await snapshot()).states.course.completed,[true,true]);await capture('course','complete');await action('course-open:0');assert.deepEqual((await snapshot()).states.course.completed,[true,true]);});
await test('Community invalid/escaped draft, guard Escape, switch, browser Back, cancel',async()=>{await reset();await choose('community');await action('forum-thread:shelf');await action('forum-draft');await page.locator('#draft-form button[type=submit]').click();assert.equal(await page.locator('#reply').getAttribute('aria-invalid'),'true');const text='<img src=x onerror=alert(1)> & my shelf idea';await page.locator('#reply').fill(text);await page.locator('#draft-form button[type=submit]').click();assert.equal(await page.locator('.draft-preview').textContent(),text);assert.equal(await page.locator('.draft-preview img').count(),0);await capture('community','preview');await choose('work');assert.equal(await page.locator('#guard').isVisible(),true);await page.keyboard.press('Escape');assert.equal((await snapshot()).active,'community');assert.equal((await snapshot()).states.community.draft,text);await action('forum-edit');await page.locator('#reply').fill('Unsaved update');await page.goBack();assert.equal((await snapshot()).current.view,'preview');assert.equal((await snapshot()).states.community.draft,'Unsaved update');await page.goBack();await page.goBack();assert.equal(await page.locator('#guard').isVisible(),true);await page.locator('#guard-stay').click();assert.equal((await snapshot()).current.view,'draft');assert.equal(await page.locator('#reply').inputValue(),'Unsaved update');await action('forum-cancel');await page.locator('#guard-accept').click();assert.equal((await snapshot()).current.view,'thread');assert.equal((await snapshot()).states.community.savedDraft,'');});
await test('Community kept drafts belong to their own thread and cannot be repeated into posts',async()=>{await reset();await choose('community');await action('forum-thread:shelf');await action('forum-draft');await page.locator('#reply').fill('Shelf-only private draft');await page.locator('#draft-form button[type=submit]').click();await action('forum-keep');await action('forum-list');await action('forum-thread:meetup');assert.equal(await page.locator('.draft-preview').count(),0,'draft from shelf leaked into meetup');await action('forum-list');await action('forum-thread:shelf');assert.equal(await page.locator('.draft-preview').textContent(),'Shelf-only private draft');assert.equal((await snapshot()).states.community.savedDraft,'Shelf-only private draft');});
await test('Work invalid/save/cancel/Escape preserve stable records and filters',async()=>{await reset();await choose('work');const original=(await snapshot()).states.work.records;await page.locator('#work-filter').selectOption('Open');await action('work-detail:T-104');await action('work-edit');await page.locator('#task-title').fill('');await page.locator('[name="notes"]').fill('Edited notes <b>literal</b>');await page.locator('[name="owner"]').selectOption('Taylor');await page.locator('#work-form button[type=submit]').click();assert.equal(await page.locator('#task-title').getAttribute('aria-invalid'),'true');assert.equal(await page.locator('[name="notes"]').inputValue(),'Edited notes <b>literal</b>');await page.locator('#task-title').fill('Check final shelf dimensions');await page.locator('#work-form button[type=submit]').click();let records=(await snapshot()).states.work.records;assert.equal(records.length,3);assert.deepEqual(records.slice(1),original.slice(1));assert.equal(records[0].due,original[0].due);assert.equal(records[0].owner,'Taylor');await capture('work','saved');await action('work-edit');await page.locator('#task-title').fill('Unsaved');await action('work-cancel');assert.equal((await snapshot()).states.work.records[0].title,'Check final shelf dimensions');await action('work-edit');await page.locator('#task-title').fill('Unsaved again');await page.keyboard.press('Escape');assert.equal((await snapshot()).states.work.records[0].title,'Check final shelf dimensions');await action('work-list');assert.equal(await page.locator('#work-filter').inputValue(),'Open');});
await test('Work changed edit guard and genuine empty-filter recovery',async()=>{await reset();await choose('work');await action('work-detail:T-104');await action('work-edit');await page.locator('#task-title').fill('Draft retained');await choose('booking');assert.equal(await page.locator('#guard').isVisible(),true);await page.locator('#guard-stay').click();assert.equal(await page.locator('#task-title').inputValue(),'Draft retained');await page.locator('[name="status"]').selectOption('Done');await page.locator('#work-form button[type=submit]').click();await action('work-list');await action('work-detail:T-105');await action('work-edit');await page.locator('[name="status"]').selectOption('Done');await page.locator('#work-form button[type=submit]').click();await action('work-list');await page.locator('#work-filter').selectOption('Open');assert.equal(await page.locator('.task-row').count(),0);await capture('work','empty');await action('work-all');assert.equal(await page.locator('.task-row').count(),3);});
await test('Booking unavailable date, field preservation, stale-slot recovery, duplicate confirmation',async()=>{await reset();await choose('booking');assert.equal(await page.locator('#booking-form button[type=submit]').isDisabled(),true);await page.locator('[name="name"]').fill('Design reading');await action('booking-date:2026-10-16');assert.equal((await snapshot()).states.booking.slot,null);await capture('booking','no-times');await action('booking-next');assert.equal(await page.locator('[name="name"]').inputValue(),'Design reading');await action('booking-slot:14:00');await page.locator('#booking-form button[type=submit]').click();assert.equal((await snapshot()).current.view,'review');await capture('booking','review');await action('booking-confirm');assert.equal((await snapshot()).current.view,'conflict');assert.equal((await snapshot()).states.booking.name,'Design reading');await capture('booking','conflict');await action('booking-recover');assert.equal((await snapshot()).current.view,'review');assert.equal((await snapshot()).states.booking.confirmed,false);await action('booking-confirm');assert.equal((await snapshot()).states.booking.confirmed,true);assert.equal(await page.locator('[data-action="booking-confirm"]').isDisabled(),true);await capture('booking','confirmed');await page.goBack();assert.equal((await snapshot()).current.view,'review');assert.equal(await page.locator('[data-action="booking-confirm"]').isDisabled(),true);await action('booking-back');assert.equal(await page.locator('[data-action="booking-slot:14:00"]').isDisabled(),true);await page.locator('[name="name"]').fill('Changed meeting');assert.equal((await snapshot()).states.booking.confirmed,false);await page.locator('[name="service"][value="desk"]').check();assert.equal((await snapshot()).states.booking.slot,null);assert.equal(await page.locator('[name="name"]').inputValue(),'Changed meeting');await action('booking-slot:15:00');await page.locator('[name="people"]').fill('2');await page.locator('#booking-form button[type=submit]').click();assert.equal((await snapshot()).states.booking.error,'Enter people from 1 to 1.');assert.equal(await page.locator('[name="name"]').inputValue(),'Changed meeting');await page.locator('[name="people"]').fill('1');await page.locator('#booking-form button[type=submit]').click();assert.equal((await snapshot()).current.view,'review');});
await test('Explicit reset clears one example only and Escape keeps state',async()=>{await reset();await action('shop-product:bookends');await action('shop-add');await choose('information');await page.locator('#query').fill('seeds');await page.locator('#query').press('Enter');await page.locator('#reset').click();await page.keyboard.press('Escape');assert.equal(await page.locator('#query').inputValue(),'seeds');await page.locator('#reset').click();await page.locator('#guard-accept').click();assert.equal((await snapshot()).states.information.query,'');assert.equal((await snapshot()).states.shopping.cart.length,1);assert.equal((await snapshot()).states.information.category,'All');});
await test('Native Enter/Space and ordinary Tab/Shift+Tab focus',async()=>{await reset();const entry=page.locator('[data-action="shop-product:bookends"]');await entry.focus();await page.keyboard.press('Space');assert.equal((await snapshot()).current.view,'product');await page.locator('[data-action="shop-add"]').focus();await page.keyboard.press('Enter');assert.equal((await snapshot()).states.shopping.cart.length,1);await page.keyboard.press('Tab');assert.notEqual(await page.evaluate(()=>document.activeElement.tagName),'BODY');await page.keyboard.press('Shift+Tab');assert.equal(await page.evaluate(()=>document.activeElement.dataset.action),'shop-add');const outline=await page.locator('[data-action="shop-add"]').evaluate(e=>getComputedStyle(e).outlineWidth);assert.equal(outline,'3px');await capture('shopping','keyboard-focus');});
await test('All active visible controls reachable in native Tab order',async()=>{for(const id of ['shopping','information','course','community','work','booking']){await reset();await choose(id);await page.locator('.skip').focus();const expected=await page.evaluate(()=>[...document.querySelectorAll('#screen button:not(:disabled),#screen input:not(:disabled),#screen select:not(:disabled),#screen textarea:not(:disabled),#screen a[href],#screen summary')].filter(e=>e.getBoundingClientRect().width>0).filter(e=>e.type!=='radio'||e.checked||(!e.form.querySelector('input[name='+e.name+']:checked')&&e===e.form.querySelector('input[name='+e.name+']'))).map(e=>{e.dataset.tabProbe='pending';return e} ).length);for(let i=0;i<45;i++){await page.keyboard.press('Tab');await page.evaluate(()=>{if(document.activeElement.dataset.tabProbe==='pending')document.activeElement.dataset.tabProbe='seen'});}const seen=await page.locator('[data-tab-probe="seen"]').count();assert.equal(seen,expected,id+' Tab coverage');}});
await page.setViewportSize(result.viewports[1]);
await test('Mobile critical screens and outline reopen',async()=>{await reset();await action('shop-product:bookends');await action('shop-add');await action('shop-cart');await action('shop-review');await capture('shopping','review');await choose('information');await action('info-article:seeds');await capture('information','article');await choose('course');await page.locator('#course-outline summary').click();assert.equal(await page.locator('#course-outline').getAttribute('open'),'');await page.locator('#course-outline summary').click();assert.equal(await page.locator('#course-outline').getAttribute('open'),null);await action('course-practice');await page.locator('input[value="0"]').check();await page.locator('#check-answer').click();await capture('course','incorrect');await choose('community');await action('forum-thread:shelf');await action('forum-draft');await page.locator('#reply').fill('A private mobile draft');await page.locator('#draft-form button[type=submit]').click();await capture('community','preview');await action('forum-keep');await choose('work');await action('work-detail:T-104');await action('work-edit');await capture('work','edit');await action('work-cancel');await choose('booking');await action('booking-slot:14:00');await page.locator('#booking-form button[type=submit]').click();await action('booking-confirm');await capture('booking','conflict');await action('booking-recover');await action('booking-confirm');await capture('booking','confirmed');});
await test('CSS reflow at 320px and enlarged type probe',async()=>{await page.setViewportSize({width:320,height:844});for(const id of ['shopping','information','course','community','work','booking']){await reset();await choose(id);await page.addStyleTag({content:'body { font-size: 20px; }'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,id+' overflow at 320px');}await page.setViewportSize(result.viewports[1]);});
await test('Mobile emulated touch booking and cart actions',async()=>{const touchContext=await browser.newContext({viewport:result.viewports[1],hasTouch:true,isMobile:true});const t=await touchContext.newPage();await t.goto(pathToFileURL(path.resolve('index.html')).href);await t.locator('[data-action="shop-product:bookends"]').tap();await t.locator('[data-action="shop-add"]').tap();await t.locator('[data-action="shop-cart"]').tap();await t.locator('[data-action="shop-qty:0:1"]').tap();assert.equal(await t.evaluate(()=>flowDemo.getSnapshot().states.shopping.cart[0].qty),2);await t.locator('#example-select').selectOption('booking');await t.locator('[data-action="booking-slot:15:00"]').tap();await t.locator('#booking-form button[type=submit]').tap();await t.locator('[data-action="booking-confirm"]').tap();assert.equal(await t.evaluate(()=>flowDemo.getSnapshot().states.booking.confirmed),true);await touchContext.close();});
await test('No page console errors or application network requests',async()=>{assert.deepEqual(result.console_errors,[]);assert.deepEqual(result.external_requests,[])});
result.finished=new Date().toISOString();result.passed=result.tests.filter(x=>x.passed).length;result.failed=result.tests.filter(x=>!x.passed).length;
fs.writeFileSync(path.join(dir,'test-results.json'),JSON.stringify(result,null,2)+'\n');fs.writeFileSync(path.join(dir,'measurements.json'),JSON.stringify(measures,null,2)+'\n');if(run==='final'){fs.writeFileSync('checks/test-results.json',JSON.stringify(result,null,2)+'\n');fs.writeFileSync('checks/measurements.json',JSON.stringify(measures,null,2)+'\n');}
await browser.close();console.log(`${run}: ${result.passed} passed, ${result.failed} failed; ${measures.length} rendered measurements.`);if(result.failed)process.exitCode=1;
