import fs from 'node:fs';
import path from 'node:path';
import {createRequire} from 'node:module';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {createHash} from 'node:crypto';
const require=createRequire(import.meta.url);
const driver=process.env.PLAYWRIGHT_CORE_PATH||'playwright-core';
const {chromium}=require(driver),root=path.dirname(fileURLToPath(import.meta.url));
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH,args:['--allow-file-access-from-files']});
const page=await browser.newPage({viewport:{width:1165,height:747},deviceScaleFactor:1});
const checks=[],errors=[],screens=[],geometry=[];let report={};
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
const url=pathToFileURL(path.join(root,'index.html')).href;
const snap=()=>page.evaluate(()=>window.gameGallery.snapshot());
const state=async g=>(await snap()).states[g];
const click=async id=>page.locator(`[data-id="${id}"]`).click();
const assert=(condition,name,evidence)=>{checks.push({name,status:condition?'passed':'failed',evidence});if(!condition)console.log('FAIL',name,JSON.stringify(evidence));};
const choose=async g=>{if((await page.viewportSize()).width>700)await page.locator(`[data-genre="${g}"]`).click();else await page.locator('#genre-select').selectOption(g);await page.evaluate(()=>window.scrollTo(0,0));};
const reset=()=>click('reset');
const focus=()=>page.evaluate(()=>({id:document.activeElement?.dataset.id||null,tag:document.activeElement?.tagName}));
async function capture(name){fs.mkdirSync(path.join(root,'screenshots'),{recursive:true});const dest=path.join(root,'screenshots',name+'.png');await page.screenshot({path:dest});const bytes=fs.readFileSync(dest),viewport=page.viewportSize();screens.push({path:'screenshots/'+name+'.png',bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex'),viewport_css:viewport,dpr:1,zoom_percent:100,state:await snap()});}
async function measure(genre,stateLabel){await page.evaluate(()=>window.scrollTo(0,0));const data=await page.evaluate(()=>{const bounds=e=>{const r=e.getBoundingClientRect();return{x:r.x,y:r.y,width:r.width,height:r.height,bottom:r.bottom}};const selectors=['#play','.topline','.inventory','.compare','.hand','.board','.map','.inspector','.arena','.action-controls','.foot'];return{overflow:document.documentElement.scrollWidth>innerWidth,width:innerWidth,height:innerHeight,main:bounds(document.querySelector('#play')),elements:Object.fromEntries(selectors.map(sel=>[sel,document.querySelector(sel)?bounds(document.querySelector(sel)):null])),controls:[...document.querySelectorAll('#play button')].map(e=>({id:e.dataset.id,disabled:e.disabled,rect:bounds(e),visible:e.getBoundingClientRect().top>=0&&e.getBoundingClientRect().bottom<=innerHeight-16})),collisions:[...document.querySelectorAll('#play button')].filter(e=>e.scrollWidth>e.clientWidth+1).map(e=>e.dataset.id)};});geometry.push({genre,state:stateLabel,...data});assert(!data.overflow,genre+' '+stateLabel+' no horizontal overflow',data.width);assert(data.collisions.length===0,genre+' '+stateLabel+' control text fits',data.collisions);assert(data.controls.filter(c=>['equip','return','inventory','play','end-turn','undo','retry','confirm','cancel','pulse','pause','reset'].includes(c.id)&&!c.disabled).every(c=>c.visible),genre+' '+stateLabel+' enabled main actions inside viewport with 16px bottom margin',data.controls.filter(c=>!c.visible).map(c=>({id:c.id,top:c.rect.y,bottom:c.rect.bottom})));}
try{
await page.goto(url);assert(!!await page.getByText('Synthetic UI and flow prototypes. Local state only; not released games.').count(),'Synthetic boundary visible',true);
// Actual UI input, no mutation hooks.
await click('inventory');await capture('rpg-desktop-first');await click('item-anchor');let s=await state('rpg');assert(s.equipped==='reed'&&await page.locator('[data-id="equip"]').isDisabled(),'RPG blocked rank preserves equipped item',s);await click('item-brass');await click('equip');s=await state('rpg');assert(s.equipped==='brass'&&await page.locator('[data-id="equip"]').isDisabled(),'RPG equip commits once',s);await page.keyboard.press('Escape');assert((await state('rpg')).view==='camp'&&(await focus()).id==='inventory','RPG return restores camp and focus',await focus());await click('inventory');assert((await state('rpg')).equipped==='brass','RPG reopening retains equipment',await state('rpg'));
await choose('card');await click('card-burst');s=await state('card');assert(s.energy===3&&s.enemy===12&&await page.locator('[data-id="play"]').isDisabled(),'Card selection spends nothing and blocks cost 4',s);await click('card-focus');await click('play');await click('card-burst');await click('play');s=await state('card');assert(s.energy===0&&s.enemy===2&&s.used.join(',')==='focus,burst','Card Focus then Burst exact cost/effect',s);await page.locator('#play').focus();await page.keyboard.press('p');assert((await state('card')).enemy===2,'Card repeated play cannot apply twice',await state('card'));await reset();await click('card-guard');await click('play');await click('end-turn');s=await state('card');assert(s.hp===10&&s.shield===0&&s.turn===2&&s.energy===3&&s.used.length===0,'Card end turn absorbs attack and restores resources',s);await click('card-cut');await click('play');await click('end-turn');await click('card-cut');await click('play');assert((await state('card')).result==='won'&&await page.locator('[data-id="end-turn"]').isDisabled(),'Card natural win disables resolution',await state('card'));await click('retry');for(let i=0;i<4;i++)await click('end-turn');assert((await state('card')).result==='lost','Card natural loss exposes retry',await state('card'));await click('retry');assert((await state('card')).hp===10,'Card retry restores health',await state('card'));
await choose('puzzle');const before=await state('puzzle');await click('left');s=await state('puzzle');assert(s.moves===0&&JSON.stringify(s.player)===JSON.stringify(before.player)&&s.history.length===0,'Puzzle wall blocks without history',s);for(const id of ['right','right','down','right','up'])await click(id);s=await state('puzzle');assert(s.won&&s.moves===5&&s.crate.join(',')==='4,2','Puzzle natural five-move solve',s);await click('undo');s=await state('puzzle');assert(!s.won&&s.moves===4&&s.crate.join(',')==='4,3','Puzzle undo reverses solved state',s);await click('retry');assert((await state('puzzle')).moves===0&&(await state('puzzle')).history.length===0,'Puzzle retry clears history',await state('puzzle'));await page.locator('#play').focus();for(const k of ['ArrowRight','ArrowRight','ArrowDown','ArrowRight','ArrowUp'])await page.keyboard.press(k);assert((await state('puzzle')).won,'Puzzle keyboard matches dpad',await state('puzzle'));
await choose('strategy');await click('map-6-2');assert((await state('strategy')).orders===0&&(await state('strategy')).preview===null,'Strategy target before unit cannot issue order',await state('strategy'));await click('map-1-2');await click('map-6-2');assert((await state('strategy')).orders===0,'Strategy preview does not commit',await state('strategy'));await click('confirm');s=await state('strategy');assert(s.orders===1&&!s.preview&&(await focus()).id==='map-1-2','Strategy confirm clears preview and restores unit focus',{state:s,focus:await focus()});await click('map-7-2');await page.keyboard.press('Escape');s=await state('strategy');assert(s.orders===1&&s.selected==='A'&&!s.preview&&s.lastOrder.target.join(',')==='6,2','Strategy cancel preserves selection and prior order',s);await click('map-7-2');await click('map-4-2');assert(!(await state('strategy')).preview&&await page.locator('[data-id="confirm"]').isDisabled(),'Strategy water clears stale preview',await state('strategy'));await click('map-1-3');const line=await page.locator('.order-lines line').getAttribute('y1');assert(line==='250','Strategy last-order line stays with committed unit',{y1:line,expected:'250'});
await choose('action');await page.locator('#play').focus();await page.keyboard.press('Space');s=await state('action');assert(s.cooldown>0&&s.drones.length===2,'Action empty pulse starts cooldown',s);assert((await focus()).tag!=='BODY','Action cooldown disablement retains usable focus',await focus());const c=s.cooldown;await page.locator('#play').focus();await page.keyboard.press('Space');assert((await state('action')).cooldown<=c&&(await state('action')).drones.length===2,'Action cooldown blocks repeat pulse',await state('action'));await click('pause');s=await state('action');await page.waitForTimeout(450);assert((await state('action')).cooldown===s.cooldown&&await page.locator('#pause-dialog').evaluate(d=>d.open),'Action pause freezes cooldown',await state('action'));await capture('action-pause-desktop');await page.keyboard.press('Escape');assert(!(await state('action')).paused&&(await focus()).id==='pause','Action resume restores Pause focus',await focus());await choose('rpg');const inactive=(await state('action')).cooldown;await page.waitForTimeout(350);assert((await state('action')).cooldown===inactive,'Action gallery switch freezes cooldown',await state('action'));assert((await state('rpg')).equipped==='brass','Genre switch preserves RPG state',await state('rpg'));
await choose('action');await reset();for(let i=0;i<3;i++)await click('right');await click('pulse');assert((await state('action')).drones.length===1,'Action in-range pulse clears first sentry',await state('action'));await page.waitForTimeout(3100);for(let i=0;i<3;i++)await click('right');await click('pulse');for(let i=0;i<4;i++)await click('right');assert((await state('action')).result==='won','Action natural path clears sentries and reaches gate',await state('action'));await click('retry');for(let run=0;run<3;run++)for(let i=0;i<5;i++)await click('right');assert((await state('action')).result==='lost'&&(await state('action')).hp===0,'Action collisions reach loss',await state('action'));await click('retry');assert((await state('action')).hp===3&&(await state('action')).cooldown===0&&(await state('action')).drones.length===2,'Action retry restores fixture',await state('action'));
for(const width of [1165,390]){await page.setViewportSize({width,height:width===1165?747:844});for(const genre of Object.keys(genres())){await choose(genre);await reset();if(genre==='rpg')await click('inventory');if(genre==='card')await click('card-burst');if(genre==='strategy'){await click('map-1-2');await click('map-7-2');const vectorBounds=await page.evaluate(()=>{const line=document.querySelector('.order-lines line'),matrix=line.getScreenCTM(),center=id=>{const r=document.querySelector(`[data-id="${id}"]`).getBoundingClientRect();return{x:r.x+r.width/2,y:r.y+r.height/2}};const point=(x,y)=>new DOMPoint(x,y).matrixTransform(matrix);const a=point(Number(line.getAttribute('x1')),Number(line.getAttribute('y1'))),b=point(Number(line.getAttribute('x2')),Number(line.getAttribute('y2'))),ca=center('map-1-2'),cb=center('map-7-2');return{origin_error:Math.hypot(a.x-ca.x,a.y-ca.y),target_error:Math.hypot(b.x-cb.x,b.y-cb.y)};});assert(vectorBounds.origin_error<2&&vectorBounds.target_error<2,'Strategy '+width+' vector aligns with actual map hitboxes',vectorBounds);}await measure(genre,width+' default/preview');await capture(genre+'-'+(width===1165?'desktop':'narrow'));} }
// Native keyboard spot checks and simulated reflow, separate from phone or AT tests.
await choose('rpg');await reset();await page.locator('#play').focus();await page.keyboard.press('i');await page.keyboard.press('2');await page.keyboard.press('Tab');assert((await state('rpg')).view==='inventory','RPG scoped keyboard entry',await state('rpg'));await page.locator('[data-id="return"]').focus();await page.keyboard.press('Enter');assert((await state('rpg')).view==='camp','Native Enter activates Return',await state('rpg'));await page.locator('[data-id="inventory"]').focus();await page.keyboard.press('Space');assert((await state('rpg')).view==='inventory','Native Space activates Inventory',await state('rpg'));const focusStyle=await page.locator('[data-id="item-brass"]').evaluate(e=>{e.focus();return{outline:getComputedStyle(e).outlineWidth,selected:e.getAttribute('aria-pressed')};});assert(focusStyle.outline==='3px','Keyboard visible focus uses independent ring',focusStyle);await page.locator('#genre-select').focus();const snapshotBefore=await state('rpg');await page.keyboard.press('i');assert(JSON.stringify(await state('rpg'))===JSON.stringify(snapshotBefore),'Shortcuts outside prototype do not mutate state',true);
await page.setViewportSize({width:583,height:374});for(const g of Object.keys(genres())){await choose(g);await reset();const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert(!overflow,g+' 200% equivalent CSS reflow no horizontal overflow',true);}
assert(errors.length===0,'Browser console/page errors absent',errors);
}catch(e){checks.push({name:'Runner execution',status:'failed',evidence:e.stack});console.error(e.stack)}finally{report={date_utc:new Date().toISOString(),browser:'Headless Chromium '+browser.version(),runtime:'file:// standalone index.html; exact real entry, no state mutation hooks',checks,totals:{passed:checks.filter(c=>c.status==='passed').length,failed:checks.filter(c=>c.status==='failed').length},console_errors:errors,screenshots:screens,not_run:['Native phone/hardware safe-area','Controller navigation','Screen-reader','Human usability/participant study','External screenshot review','True browser 200% zoom (583x374 CSS viewport used as reflow probe)','Touch pointer gestures on physical device','Production performance/latency']};fs.writeFileSync(path.join(root,'qa-report.json'),JSON.stringify(report,null,2));fs.writeFileSync(path.join(root,'render-geometry.json'),JSON.stringify(geometry,null,2));await browser.close();console.log(JSON.stringify(report.totals));if(report.totals.failed)process.exitCode=1;}
function genres(){return{rpg:1,card:1,puzzle:1,strategy:1,action:1}}
