import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
const root=path.dirname(fileURLToPath(import.meta.url)),repo=path.resolve(root,'../..'),metadata=JSON.parse(fs.readFileSync(path.join(root,'public-integration.json'),'utf8')),checks=[];
const check=(ok,name,evidence)=>checks.push({name,status:ok?'passed':'failed',evidence});
const hash=f=>createHash('sha256').update(fs.readFileSync(f)).digest('hex');
function files(dir){return fs.readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.isDirectory()?files(path.join(dir,e.name)):[path.join(dir,e.name)]);}
for(const [file,expected] of Object.entries(metadata.protectedFiles))check(hash(path.join(root,file))===expected,'Exact authored source/fixture '+file,expected);
for(const [file,expected] of Object.entries(metadata.approvedPngHashes)){const bytes=fs.readFileSync(path.join(root,file));check(hash(path.join(root,file))===expected&&bytes.subarray(0,8).toString('hex')==='89504e470d0a1a0a','Own PNG hash/header '+file,{bytes:bytes.length,width:bytes.readUInt32BE(16),height:bytes.readUInt32BE(20),sha256:expected});}
const sandbox={window:{}};vm.runInNewContext(fs.readFileSync(path.join(root,'data.js'),'utf8'),sandbox);for(const key of ['config','fixture'])check(JSON.stringify(sandbox.window.PLAYGROUND_DATA[key])===JSON.stringify(JSON.parse(fs.readFileSync(path.join(root,key+'.json'),'utf8'))),'Runtime/JSON parity '+key,true);
const broken=[],sensitive=[];
for(const f of files(root)){if(f.endsWith('.png'))continue;const text=fs.readFileSync(f,'utf8');if(/\b[A-Za-z]:[\\/]|\b(?:gh[pousr]_[A-Za-z0-9]{25,}|github_pat_[A-Za-z0-9_]{30,}|sk-[A-Za-z0-9]{30,})\b/.test(text))sensitive.push(path.relative(root,f));if(!/\.(?:md|html)$/.test(f))continue;const targets=[...text.matchAll(/!?\[[^\]]*\]\(([^)]+)\)|(?:href|src)="([^"]+)"/g)].map(m=>m[1]||m[2]);for(const target of targets){if(/^(?:https?:|data:|#)/.test(target))continue;const p=path.resolve(path.dirname(f),decodeURIComponent(target.split('#')[0]));if(!p.startsWith(repo+path.sep)||!fs.existsSync(p))broken.push({file:path.relative(root,f),target});}}
check(sensitive.length===0,'No private machine paths or credential patterns in public package',sensitive);check(broken.length===0,'All local public package/archival links exist',broken);
const allowed=new Set(['README.md','docs/RESEARCH_INDEX.md','docs/CHANGELOG.md','docs/RIGHTS_AND_SCOPE.md','docs/VERIFICATION.md','docs/PROVENANCE.json','research/series_index.json','validation/validate_release.py','validation/release-checks.json','FILES.sha256.json']);
try{const tracked=execFileSync('git',['ls-tree','-r','--name-only',metadata.baseCommit],{cwd:repo,encoding:'utf8'}).trim().split(/\r?\n/),changed=execFileSync('git',['diff','--name-only',metadata.baseCommit],{cwd:repo,encoding:'utf8'}).trim().split(/\r?\n/).filter(Boolean),drift=changed.filter(f=>!allowed.has(f)&&!f.startsWith('research/game_ui_playground_v1/'));check(drift.length===0,'All earlier tracked implementation/research/evidence Git bytes preserved',{preserved:tracked.filter(f=>!allowed.has(f)).length,drift,lineEndings:'Git normalization; release tree verifies canonical published bytes separately'});}catch(e){check(false,'Baseline preservation check','Git baseline unavailable; run from the integrated repository.');}
const q=JSON.parse(fs.readFileSync(path.join(root,'qa-report.json'),'utf8')),s=JSON.parse(fs.readFileSync(path.join(root,'source-checks.json'),'utf8'));check(q.totals.passed===136&&q.totals.failed===0&&s.totals.passed===55&&s.totals.failed===0,'Retained pre-publication136/55 outcome record unchanged',{browser:q.totals,source:s.totals});
const result={timestamp:new Date().toISOString(),scope:'Current public package exact-byte/hash/link/private-pattern checks and earlier repository preservation; separate from pre-publication136/55 and physical-device/user approval',checks,totals:{passed:checks.filter(x=>x.status==='passed').length,failed:checks.filter(x=>x.status==='failed').length}};fs.writeFileSync(path.join(root,'public-checks.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result.totals));if(result.totals.failed)process.exitCode=1;
