import fs from 'node:fs';
import path from 'node:path';
import {createRequire} from 'node:module';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {createHash} from 'node:crypto';
import os from 'node:os';
const root=path.dirname(fileURLToPath(import.meta.url)),require=createRequire(import.meta.url);
const bundledDriver=path.join(process.env.APPDATA||'','npm/node_modules/agbrowse/node_modules/playwright-core');
const driver=process.env.PLAYWRIGHT_CORE_PATH||(fs.existsSync(bundledDriver)?bundledDriver:'playwright-core');
const {chromium}=require(driver);
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROME_PATH||(process.platform==='win32'?path.join(process.env.ProgramFiles,'Google/Chrome/Application/chrome.exe'):undefined),args:['--disable-gpu']});
const context=await browser.newContext({viewport:{width:1440,height:1000},deviceScaleFactor:1,acceptDownloads:true});
const page=await context.newPage(),errors=[],checks=[],shots=[],steps=[],geometry=[],failedRequests=[];
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
page.on('requestfailed',r=>failedRequests.push({url:r.url(),failure:r.failure()}));
const url=process.env.PLAYGROUND_URL||pathToFileURL(path.join(root,'index.html')).href;
const screenshotDir=path.join(root,'screenshots');fs.mkdirSync(screenshotDir,{recursive:true});
const snap=()=>page.evaluate(()=>window.gamePlayground.snapshot());
const state=async s=>(await snap()).states[s];
function check(ok,name,evidence){checks.push({name,status:ok?'passed':'failed',evidence});if(!ok)console.log('FAIL '+name+' '+JSON.stringify(evidence));}
async function observe(){return {ui:await page.locator('#game').ariaSnapshot(),state:await snap()};}
async function click(selector){const before=await observe();await page.locator(selector).click();steps.push({input:'click '+selector,before,after:await observe()});}
const action=async id=>click('[data-action="'+id+'"]');
async function choose(s){await click('[data-station="'+s+'"]');await page.evaluate(()=>scrollTo(0,0));}
async function reset(){await click('#reset');}
async function config(key,value){const el=page.locator('#settings [data-setting="'+key+'"]');const before=await observe();if(typeof value==='boolean')await el.setChecked(value);else if(await el.first().evaluate(e=>e.tagName==='BUTTON'))await page.locator('#settings [data-setting="'+key+'"][data-value="'+value+'"]').click();else if(await el.first().evaluate(e=>e.type==='range')){await el.fill(String(value));}else await el.selectOption(String(value));steps.push({input:'setting '+key+'='+value,before,after:await observe()});}
async function capture(name){await page.evaluate(()=>scrollTo(0,0));await page.waitForTimeout(250);const filename=name+'.png';await page.screenshot({path:path.join(screenshotDir,filename),fullPage:true,animations:'disabled'});const bytes=fs.readFileSync(path.join(screenshotDir,filename));shots.push({name,file:'screenshots/'+filename,width:bytes.readUInt32BE(16),height:bytes.readUInt32BE(20),bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex'),viewport:page.viewportSize(),state:await snap(),unedited:true});}
async function measure(name){const result=await page.evaluate(()=>{
  const nodes=[...document.querySelectorAll('#game button,#game select')].filter(e=>e.getClientRects().length),rects=nodes.map(e=>{const r=e.getBoundingClientRect();return{id:e.id||e.dataset.filter||e.dataset.catalog,label:e.getAttribute('aria-label')||e.textContent.trim(),x:r.x,y:r.y,w:r.width,h:r.height,disabled:e.disabled,dialog:!!e.closest('dialog')};});
  const overlaps=[];for(let i=0;i<rects.length;i++)for(let j=i+1;j<rects.length;j++){const a=rects[i],b=rects[j];if(a.dialog!==b.dialog)continue;const w=Math.min(a.x+a.w,b.x+b.w)-Math.max(a.x,b.x),h=Math.min(a.y+a.h,b.y+b.h)-Math.max(a.y,b.y);if(w>2&&h>2)overlaps.push([a.id,b.id,w,h]);}const caption=document.querySelector('.map-caption');if(caption?.getClientRects().length){const a=caption.getBoundingClientRect();for(const b of rects){const w=Math.min(a.right,b.x+b.w)-Math.max(a.x,b.x),h=Math.min(a.bottom,b.y+b.h)-Math.max(a.y,b.y);if(w>2&&h>2)overlaps.push(['map-caption',b.id,w,h]);}}
  const clipped=rects.filter(r=>r.x<-.5||r.x+r.w>innerWidth+.5),occluded=[];for(let i=0;i<nodes.length;i++){const e=nodes[i],r=rects[i],x=r.x+r.w/2,y=r.y+r.h/2;if(e.disabled||x<0||x>innerWidth||y<0||y>innerHeight||document.querySelector('dialog[open]')&&!r.dialog)continue;const top=document.elementFromPoint(x,y);if(top&&!e.contains(top)&&top!==e)occluded.push(r.id);}
  return {pageWidth:innerWidth,scrollWidth:document.documentElement.scrollWidth,gameWidth:document.querySelector('#game').clientWidth,rects,overlaps,clipped,occluded};
});geometry.push({name,...result});check(result.scrollWidth<=result.pageWidth,name+' / no horizontal page overflow',result.scrollWidth);check(result.overlaps.length===0&&result.clipped.length===0&&result.occluded.length===0,name+' / controls do not overlap, clip horizontally, or get covered',{overlaps:result.overlaps,clipped:result.clipped,occluded:result.occluded});}
async function active(){return page.evaluate(()=>document.activeElement.id);}
try{
  await page.goto(url);check((await snap()).station==='minimap','Real entry starts in exploration',await snap());
  await capture('01-minimap-desktop');await measure('1440 desktop minimap');
  const initial=await state('minimap');await action('turn-right');check((await state('minimap')).player.heading===75,'Turn changes heading by45',(await state('minimap')).player);
  await config('orientation','heading');const transform=await page.locator('.minimap-open svg g[clip-path]>g').first().getAttribute('transform');check(transform.includes('rotate(-75)'),'Heading-up map counter-rotates to player',transform);
  const markerBefore=await page.locator('.minimap-open [data-marker="tower"]').getAttribute('transform');await config('zoom',2.8);check((await snap()).config.minimap.zoom===2.8,'Zoom updates from actual range input',(await snap()).config.minimap.zoom);
  await config('edgeArrows',false);check(await page.locator('.minimap-open [data-edge="true"]').count()===0,'Offscreen hide removes rim arrows',await page.locator('.minimap-open [data-marker]').count());await config('edgeArrows',true);
  await config('shape','square');check(await page.locator('.minimap-open.square').count()===1,'Shape updates live hit target','square');await action('forward');check((await state('minimap')).player.x!==initial.player.x,'Move changes shared world coordinates',(await state('minimap')).player);
  await config('framing','full');check(await page.locator('#setting-zoom').isDisabled()&&await page.locator('[data-setting="orientation"]').first().isDisabled(),'Full frame disables tracking-only controls',true);const fullTransform=await page.locator('.minimap-open svg g[clip-path]>g').first().getAttribute('transform');await action('forward');check((await page.locator('.minimap-open svg g[clip-path]>g').first().getAttribute('transform'))===fullTransform,'Full frame terrain stays fixed while player moves',fullTransform);await config('framing','follow');
  await page.locator('.advanced summary').click();await config('enemies',false);check(await page.locator('.minimap-open [data-marker="enemy-a"]').count()===0,'Enemy visibility is independent',true);await config('iconScale',1.6);await config('objectiveMaps','overview');check(await page.locator('.minimap-open [data-marker="tower"]').count()===0,'Map-specific goals hidden on minimap',true);await action('open-map');check(await page.locator('[data-waypoint="tower"]').count()===1,'Map-specific goals remain in overview',true);await click('[data-waypoint="camp"]');check((await state('minimap')).waypoint==='camp','Overview goal selection updates tracking','camp');await page.keyboard.press('Escape');check((await state('minimap')).view==='trail'&&await active()==='open-map','Escape returns and restores map opener',await active());
  await reset();await page.locator('#map-preset').selectOption('lookout');check((await snap()).config.minimap.orientation==='heading'&&(await snap()).config.minimap.zoom===2.3,'Authored preset changes settings but retains same fixture',(await snap()).config.minimap);await reset();
  await choose('inventory');await action('open-inventory');const equipment=JSON.stringify((await state('inventory')).equipment);await click('[data-item="brass"]');check(JSON.stringify((await state('inventory')).equipment)===equipment,'Selecting gear does not equip',await state('inventory'));check((await page.locator('.stats-table').innerText()).includes('+6')&&(await page.locator('.stats-table').innerText()).includes('-1'),'Equipment comparison shows signed stat changes',await page.locator('.stats-table').innerText());await capture('02-inventory-compare-desktop');await measure('1440 desktop inventory');await action('equip');check((await state('inventory')).equipment.weapon==='brass','Equip commits chosen slot',await state('inventory'));
  await page.locator('#equip').evaluate(e=>e.click());check((await state('inventory')).equipment.weapon==='brass','Repeated disabled equip preserves equipment',await state('inventory'));await click('[data-item="anchor"]');check(await page.locator('#equip').isDisabled()&&(await page.locator('.notice').innerText()).includes('Requires rank 3'),'Rank requirement blocks unavailable gear',await page.locator('.notice').innerText());
  await click('[data-item="tonic"]');check((await page.locator('.item-detail').innerText()).includes('Owned ×4'),'Consumable detail renders without equip',await page.locator('.item-detail').innerText());await click('[data-item="ore"]');check(await page.locator('#equip').count()===0,'Material has no equip action',true);
  await config('layout','list');await config('sort','name');const names=await page.locator('.item-name').allTextContents();check(names[0]==='Anchor axe'&&names.at(-1)==='Trail ration','Sort reorders unchanged fixture names',names);await config('filter','weapon');check(await page.locator('[data-item]').count()===3&&(await state('inventory')).selected===null,'Filter narrows collection and clears stale selection',await state('inventory'));await config('compare',false);await click('[data-item="reed"]');check(await page.locator('.stats-table th').count()===2,'Compare-off changes table columns',await page.locator('.stats-table').innerText());await action('close-inventory');check((await page.locator('.game-content').innerText()).includes('Brass sabre')&&await active()==='open-inventory','Close shows committed loadout and restores focus',await active());await action('open-inventory');check((await state('inventory')).equipment.weapon==='brass','Reopen retains equipped weapon',await state('inventory'));
  await choose('shop');await click('[data-product="lens"]');check(await page.locator('#review-purchase').isDisabled()&&(await page.locator('.notice').innerText()).includes('160'),'Insufficient funds state names shortfall',await page.locator('.notice').innerText());await action('back-shop');await click('#product-tonic');await action('qty-plus');const shopBefore=await state('shop');await action('review-purchase');check((await state('shop')).balance===260&&(await state('shop')).pending.total===80,'Review purchase creates pending intent without debit',await state('shop'));await measure('1440 desktop confirmation');await capture('03-shop-confirm-desktop');await page.keyboard.press('Escape');const cancelled=await state('shop');check(cancelled.balance===shopBefore.balance&&JSON.stringify(cancelled.stock)===JSON.stringify(shopBefore.stock)&&await active()==='review-purchase','Escape cancels transaction and restores focus',cancelled);await action('review-purchase');await action('cancel-review');check((await state('shop')).transactions===0,'Cancel button makes no purchase',await state('shop'));await action('review-purchase');
  // Dispatch two activations on the observed real button to probe duplicate event safety.
  await page.locator('#confirm-purchase').evaluate(e=>{e.click();e.click();});let purchased=await state('shop');check(purchased.balance===180&&purchased.stock.tonic===10&&purchased.owned.tonic===3&&purchased.transactions===1&&purchased.pending===null,'Repeated confirm resolves exactly one transaction',purchased);await action('continue-shop');await config('catalog','recommended');check(await page.locator('.product-card').count()===2,'Contextual catalog uses authored recommendation flags',await page.locator('.product-card').count());await click('#product-tonic');for(let i=0;i<8;i++)await action('qty-plus');check((await state('shop')).quantity===9&&await page.locator('#qty-plus').isDisabled()&&await page.locator('#review-purchase').isDisabled(),'Quantity limit and insufficient total block review',await state('shop'));await action('back-shop');
  await reset();await click('#quick-ward');await action('qty-plus');await action('review-purchase');const modalFocus=[];for(let i=0;i<5;i++){await page.keyboard.press('Tab');modalFocus.push(await page.evaluate(()=>({dialog:document.activeElement.closest('dialog')?.id||null,tag:document.activeElement.tagName,id:document.activeElement.id})));}check(modalFocus.every(x=>x.dialog==='purchase-dialog'||x.tag==='BODY'),'Native dialog Tab never focuses a background page control',modalFocus);await action('confirm-purchase');await capture('shop-purchase-complete-desktop');await action('continue-shop');await click('#product-ward');check((await state('shop')).stock.ward===0&&await page.locator('#review-purchase').isDisabled()&&(await page.locator('.notice').innerText()).includes('Out of stock'),'Natural purchase depletion reaches sold-out recovery',await state('shop'));await action('back-shop');
  await choose('hud');await action('strike');const strikes=(await state('hud')).strikes;await page.locator('#strike').evaluate(e=>e.click());check((await state('hud')).strikes===strikes,'Cooldown rejects repeated strike',await state('hud'));await action('pause');const paused=(await state('hud')).cooldown;await page.waitForTimeout(350);check((await state('hud')).cooldown===paused,'Pause freezes measured cooldown',paused);await page.keyboard.press('Escape');check(await active()==='pause'&&!(await state('hud')).paused,'Escape resumes and restores pause focus',await active());await choose('shop');const frozen=(await state('hud')).cooldown;await page.waitForTimeout(300);check((await state('hud')).cooldown===frozen,'Station switch freezes inactive combat',frozen);await choose('hud');await action('incoming-hit');await action('heal');check((await state('hud')).health===100&&(await state('hud')).tonics===1,'Heal consumes one tonic and clamps health',await state('hud'));for(let i=0;i<3;i++)await action('incoming-hit');check((await state('hud')).health===28&&await page.locator('.low-health').count()===1,'Low-health warning appears alongside updated health',await state('hud'));await capture('04-hud-low-health-desktop');await action('incoming-hit');await action('incoming-hit');check((await state('hud')).result==='lost','Natural hit sequence reaches loss',await state('hud'));await action('retry-combat');check((await state('hud')).health===100&&(await state('hud')).tonics===2,'Retry restores combat fixture',await state('hud'));for(let i=0;i<3;i++){await action('strike');if(i<2)await page.waitForTimeout(2600);}check((await state('hud')).result==='won'&&(await state('hud')).enemyHealth===0,'Natural strike sequence reaches win',await state('hud'));
  await choose('dialogue');await action('ask-reward');check((await page.locator('.dialogue-text').innerText()).includes('Eighty'),'Reward can be inspected before acceptance',await state('dialogue'));await action('back-talk');await action('leave-talk');await action('return-ranger');await action('accept-quest');check((await state('dialogue')).accepted&&(await state('dialogue')).balance===0,'Accept starts progress without granting reward',await state('dialogue'));await action('return-ranger');check((await page.locator('.dialogue-text').innerText()).includes('3 samples'),'Early return shows remaining requirement',await page.locator('.dialogue-text').innerText());await action('continue-quest');for(let i=0;i<3;i++)await action('collect-sample');check(await page.locator('#collect-sample').isDisabled(),'Collection stops at declared requirement',await state('dialogue'));await action('return-ranger');await page.locator('#claim-reward').evaluate(e=>{e.click();e.click();});check((await state('dialogue')).balance===80&&(await state('dialogue')).claimed,'Reward claimed once under duplicate activation',await state('dialogue'));await capture('05-dialogue-reward-desktop');
  for(const viewport of [{width:1165,height:747},{width:844,height:390},{width:390,height:844},{width:320,height:568}]){
    await page.setViewportSize(viewport);const label=viewport.width+'x'+viewport.height;
    for(const s of ['minimap','inventory','shop','hud','dialogue']){
      await choose(s);await reset();if(s==='inventory'){await action('open-inventory');await click('[data-item="brass"]');}if(s==='shop'){await click('#product-tonic');await action('review-purchase');}if(s==='hud'){await action('strike');await action('pause');}
      await measure(label+' '+s);if((viewport.width===390&&s!=='hud')||(viewport.width===844&&['minimap','shop','hud'].includes(s))||(viewport.width===320&&s==='inventory'))await capture(s+'-'+label);
      if(s==='shop')await action('cancel-review');if(s==='hud')await action('resume');
      if(s==='inventory'&&viewport.width<=620){check(await page.locator('.item-collection').isHidden()&&await page.locator('#back-items').isVisible(),label+' inventory uses sequential compact detail',true);await page.keyboard.press('Escape');check((await state('inventory')).selected===null&&await active()==='item-brass',label+' detail Back restores item focus',await active());await page.keyboard.press('Escape');check((await state('inventory')).view==='camp'&&await active()==='open-inventory',label+' inventory close restores opener',await active());}
    }
  }
  await page.setViewportSize({width:844,height:390});
  for(const s of ['minimap','hud','shop']){await choose(s);await reset();if(s==='shop'){await click('#product-tonic');await action('review-purchase');await action('cancel-review');}await click('#play-view');check(await page.locator('.stations').isHidden()&&await page.locator('#settings').isHidden(),'Play view hides tools and retains '+s+' state',true);await measure('844 landscape play view '+s);if(s!=='shop'){const ids=s==='minimap'?['forward','turn-left','turn-right']:['strike','heal','incoming-hit'];const visible=await page.evaluate(ids=>ids.map(id=>{const r=document.getElementById(id).getBoundingClientRect();return{id,visible:r.y>=0&&r.bottom<=innerHeight};}),ids);check(visible.every(x=>x.visible),'844 landscape '+s+' primary controls fit viewport',visible);}await capture('play-view-'+s+'-844x390');await click('#play-view');check(await page.locator('.stations').isVisible(),'Exit play view restores station tools',true);}
  await page.setViewportSize({width:390,height:844});await choose('inventory');await reset();await action('open-inventory');await click('[data-item="brass"]');await click('#play-view');await measure('390 portrait play view inventory');await capture('play-view-inventory-390x844');await action('equip');check((await state('inventory')).equipment.weapon==='brass','Portrait play view can equip without tool panels',true);await click('#play-view');
  await page.setViewportSize({width:1440,height:1000});await choose('minimap');await reset();await page.locator('#viewport').selectOption('portrait');check(await page.locator('#game').evaluate(e=>e.clientWidth)===390,'Internal portrait framing makes game390px wide',true);await measure('desktop internal portrait');await capture('06-internal-portrait');await page.locator('#viewport').selectOption('landscape');check(await page.locator('#game').evaluate(e=>e.clientWidth)<=844,'Internal landscape framing uses bounded game width',true);await measure('desktop internal landscape');await page.locator('#viewport').selectOption('adaptive');
  // Actual native keys, focus styles, reduced-motion and JSON download.
  await page.locator('#open-map').focus();await page.keyboard.press('Enter');check((await state('minimap')).view==='overview','Native Enter activates map opener',true);await page.keyboard.press('Escape');await page.locator('#open-map').focus();await page.keyboard.press('Space');check((await state('minimap')).view==='overview','Native Space activates map opener',true);await page.keyboard.press('Escape');await page.locator('#game').focus();const pos=(await state('minimap')).player;await page.keyboard.press('w');check((await state('minimap')).player.y!==pos.y,'Scoped keyboard movement updates player',await state('minimap'));await page.locator('#setting-zoom').focus();const p2=(await state('minimap')).player;await page.keyboard.press('w');check(JSON.stringify((await state('minimap')).player)===JSON.stringify(p2),'Inspector keys do not move player',true);await page.locator('#open-map').focus();check(await page.locator('#open-map').evaluate(e=>getComputedStyle(e).outlineWidth)==='3px','Visible keyboard focus is3px',true);
  await page.emulateMedia({reducedMotion:'reduce'});check(await page.locator('.pulse-ring').first().evaluate(e=>getComputedStyle(e).animationName)==='none','Reduced motion suppresses objective pulse',true);
  const downloadPromise=page.waitForEvent('download');await click('#export');const download=await downloadPromise;const localDownload=path.join(os.tmpdir(),'dns-game-ui-export-'+Date.now()+'.json');await download.saveAs(localDownload);const exported=JSON.parse(fs.readFileSync(localDownload,'utf8'));check(exported.minimap.zoom===(await snap()).config.minimap.zoom&&exported.artifactType==='authored-design-proposal'&&!exported.states,'Export delivers valid current settings without session economy',exported);fs.unlinkSync(localDownload);
  await page.reload();check((await state('shop')).balance===260&&(await state('inventory')).equipment.weapon==='reed','Reload restores all default fixtures',await snap());
  // Touch pointer smoke test uses browser emulation, explicitly distinct from hardware.
  const touchContext=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1});const touch=await touchContext.newPage();await touch.goto(url);await touch.locator('[data-station="inventory"]').tap();await touch.locator('#open-inventory').tap();await touch.locator('[data-item="brass"]').tap();await touch.locator('#equip').tap();check((await touch.evaluate(()=>window.gamePlayground.snapshot())).states.inventory.equipment.weapon==='brass','Emulated touch completes select/equip',true);await touchContext.close();
  check(errors.length===0,'No browser console or page errors',errors);check(failedRequests.length===0,'No failed requests',failedRequests);
}catch(e){check(false,'Runner completed declared flow',e.stack);console.error(e.stack);}
finally{
  const report={timestamp:new Date().toISOString(),browser:'Headless installed Chrome '+browser.version(),runtime:process.env.PLAYGROUND_URL?'Loopback-served index.html':'Standalone index.html',inputEvidence:'Native Playwright clicks/keys/range inputs; two duplicate activation probes dispatch click on actual rendered button. Read-only snapshots never mutate app state.',checks,totals:{passed:checks.filter(x=>x.status==='passed').length,failed:checks.filter(x=>x.status==='failed').length},errors,failedRequests,notRun:['native phone hardware/safe-area','controller','screen reader','human usability study','external screenshot reviewer','true browser200% zoom','network/save reconnect','actual model A/B experiment','user design approval','commit/push/Site deployment']};
  fs.writeFileSync(path.join(root,'qa-report.json'),JSON.stringify(report,null,2)+'\n');fs.writeFileSync(path.join(root,'input-output-log.json'),JSON.stringify(steps,null,2)+'\n');fs.writeFileSync(path.join(root,'render-geometry.json'),JSON.stringify(geometry,null,2)+'\n');fs.writeFileSync(path.join(root,'screenshot-manifest.json'),JSON.stringify({timestamp:report.timestamp,source:'Actual runtime screenshots, full-page, no crops or edits',screenshots:shots},null,2)+'\n');
  await browser.close();console.log(JSON.stringify(report.totals));if(report.totals.failed)process.exitCode=1;
}
