/* All graphics and scenes are original. This is an authored teaching fixture. */
(() => {
  'use strict';
  const P = JSON.parse(document.getElementById('parameters').textContent);
  const $ = id => document.getElementById(id);
  const clamp = (n, lo, hi) => Math.max(lo, Math.min(hi, n));
  const esc = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const motion = matchMedia('(prefers-reduced-motion: reduce)');
  const records = {jump:[], interaction:[], feedback:[], recovery:[]};
  let tab = 'jump', frame = 0, hitTimer = 0, coolTimer = 0, pulseAnimations = [];
  const jumpInitial = () => ({scenario:'coyote', offset:P.jump.default_coyote_offset_ms, coyote:true, buffer:true, hold:true, running:false, live:false, t:0, input:null, releasedAt:null, lastRecord:null});
  const interactionInitial = () => ({mode:'nearby', aim:{x:43,y:49}, travel:0, blocked:false, selected:null, cancelled:false, completed:[]});
  const feedbackInitial = () => ({hp:P.feedback.initial_health, exposure:0, damageDir:'left', observerDir:'right', lastHit:null, hitVisible:false, cooling:false, shake:0, flash:0});
  const recoveryInitial = () => ({alive:true, wallet:P.recovery.initial_shards, pile:null, lost:0, x:P.recovery.initial_position, available:P.recovery.relay_available, menu:false, checkpoint:'home', found:false, step:'Alive'});
  let jump = jumpInitial(), interaction = interactionInitial(), feedback = feedbackInitial(), recovery = recoveryInitial();
  function record(message, target=tab) {
    records[target].unshift({time:new Date().toLocaleTimeString('en-GB',{hour12:false}),message});
    records[target] = records[target].slice(0,3);
    if (target === tab) {
      $('status').textContent = message;
      $('log').innerHTML = records[target].slice(1).map(r=>`<li><time>${esc(r.time)}</time>${esc(r.message)}</li>`).join('');
    }
  }
  const eye = '<svg viewBox="0 0 32 32" aria-hidden="true"><path d="M2 16Q16 1 30 16Q16 31 2 16Z" fill="none" stroke="currentColor" stroke-width="2"/><circle cx="16" cy="16" r="5" fill="none" stroke="currentColor" stroke-width="2"/></svg>';
  const spike = '<svg viewBox="0 0 32 32" aria-hidden="true"><path d="M29 2 7 12l8 4L3 30l23-11-8-4Z" fill="currentColor"/></svg>';
  const shard = '<svg viewBox="0 0 32 40" aria-hidden="true"><path d="M16 2 28 18 16 37 4 18Z" fill="#f5cc7b" stroke="#fff0c0" stroke-width="2"/><path d="M16 2v35L28 18Z" fill="#a98a58"/></svg>';
  const shrine = '<svg viewBox="0 0 40 48" aria-hidden="true"><path d="M4 44h32M9 43V21L20 5l11 16v22Z" stroke="#a8cdb9" stroke-width="2" fill="#4d6862"/><path d="M16 43V24h8v19" fill="#b6ddc4"/></svg>';
  const relayArt = '<svg viewBox="0 0 90 80" aria-hidden="true"><ellipse cx="45" cy="72" rx="33" ry="7" fill="#152328"/><path d="m22 63 23 12 22-12V26L45 14 22 26Z" fill="#6c9190" stroke="#c2d9c9" stroke-width="2"/><path d="m45 75 22-12V26L45 38Z" fill="#446c71"/><path d="m22 26 23 12 22-12-22-12Z" fill="#bed2bd"/><path d="M33 45h10v12H33Z" fill="#a2e4cb"/><path d="M45 14V2m-7 2h14" stroke="#b2cfc0" stroke-width="3"/></svg>';
  const podArt = '<svg viewBox="0 0 90 80" aria-hidden="true"><ellipse cx="45" cy="71" rx="34" ry="7" fill="#152328"/><path d="M25 58Q13 32 45 13Q78 32 65 58L45 73Z" fill="#b1ba87" stroke="#e1e7b8" stroke-width="2"/><path d="M45 15v55M24 38l21 12 21-12" fill="none" stroke="#687959" stroke-width="3"/><path d="M42 16Q39 4 55 3" fill="none" stroke="#a2e4cb" stroke-width="3"/></svg>';
  const cacheArt = '<svg viewBox="0 0 90 80" aria-hidden="true"><ellipse cx="45" cy="72" rx="34" ry="7" fill="#152328"/><path d="m13 58 32 16 33-16V28L45 12 13 28Z" fill="#b38f61" stroke="#dec8a2" stroke-width="2"/><path d="m45 74 33-16V28L45 45Z" fill="#7c674e"/><path d="m13 28 32 17 33-17-33-16Z" fill="#cab795"/><path d="M13 41 45 57l33-16M45 45v29" stroke="#4e4e44" stroke-width="3"/><path d="M42 54h8v11h-8Z" fill="#d8ceae"/></svg>';
  const notes = {
    jump:{title:'A jump can be a little late.',description:'Replay one input in both lanes, or press Jump during a live run.',source:'Celeste developer: forgiveness',url:'https://www.maddymakesgames.com/articles/celeste_and_forgiveness/index.html',confirmed:'The developer describes jumping shortly after a ledge, and holding jump shortly before landing to jump on the landing frame.',proposal:'Our 100 ms ledge grace, 120 ms buffer, shared analytic movement and 0.5× playback are teaching proposals. They are not Celeste’s measured settings.'},
    interaction:{title:'Which object did you mean?',description:'Move the reticle, switch candidates, then try the interaction.',source:'No Man’s Sky: Waypoint update',url:'https://www.nomanssky.com/waypoint-update/',confirmed:'The 4.0 patch notes describe highlighting nearby objects without precise aim.',proposal:'The exact-aim comparison, candidate scoring, explicit switching, occlusion guard and 4 m limit are our proposed interaction contract. No Man’s Sky’s internal priority algorithm was not verified.'},
    feedback:{title:'A hit is not a warning.',description:'Take damage and build exposure independently. Adjust the effects.',source:'Naughty Dog: accessibility feature details',url:'https://www.naughtydog.com/blog/the_last_of_us_part_ii_accessibility_features_detailed',confirmed:'The page describes directional damage spikes, awareness direction and stealth/always options, plus screen-shake adjustment and HUD flashing control.',proposal:'Our lightning and eye symbols, exposure steps, persistence and single-pulse intensity sliders are original proposals. The demo does not reproduce the game’s effects or certify accessibility.'},
    recovery:{title:'Death changes what you can recover.',description:'Die, choose a return point, walk to the drop and recover it—or die again.',source:'Bandai Namco: Elden Ring starter guide',url:'https://en.bandainamcoent.eu/elden-ring/news/elden-ring-starter-guide-tips-know-playing-the-game',confirmed:'The guide describes returning to the last rest point or a nearby Stake of Marika, dropped carried runes and losing that drop if you die before recovering it.',proposal:'Our shards, map, quantities, checkpoint names and availability toggle are fictional teaching fixtures. This is not a current-version gameplay guarantee.'}
  };
  function common(body) {
    const n = notes[tab];
    return `<div class="study-head"><div><h2>${n.title}</h2><p>${n.description}</p></div><span class="counter">Interactive study / ${Object.keys(notes).indexOf(tab)+1} of 4</span></div>${body}<p id="status" class="status-line" role="status" aria-live="polite" aria-atomic="true"></p><ol id="log" class="log" aria-label="Recent state changes"></ol><details class="evidence"><summary>Source & what we proposed</summary><p><a href="${n.url}" target="_blank" rel="noopener noreferrer">${n.source}</a> · directly checked 6 Oct 2026.</p><p>${n.confirmed}</p><p class="boundary">${n.proposal} Official documentation describes its published scope; it does not establish universal rules or current behavior in every edition. Source links only; no original game assets are redistributed.</p></details>`;
  }
  function stopJump(reason) {
    if (!jump.running) return;
    cancelAnimationFrame(frame); jump.running=false;
    if (reason) record(reason,'jump');
    if (tab==='jump') updateJump();
  }
  function clearEffects() {
    clearTimeout(hitTimer);clearTimeout(coolTimer);pulseAnimations.forEach(a=>a.cancel());pulseAnimations=[];
    feedback.hitVisible=false;feedback.cooling=false;
  }
  function switchTab(next) {
    if (!notes[next]) return;
    stopJump('Run cancelled on tab change. Input record retained.');
    clearEffects();tab=next;
    document.querySelectorAll('[data-tab]').forEach(b=>{const active=b.dataset.tab===tab;b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1;});
    $('lab').setAttribute('aria-labelledby',`tab-${tab}`);
    ({jump:renderJump,interaction:renderInteraction,feedback:renderFeedback,recovery:renderRecovery})[tab]();
    record(records[tab][0]?.message || ({jump:'Choose a timing case, then replay the same input.',interaction:'Nearby mode ranks eligible candidates. Click or tap the scene to aim.',feedback:'Hidden · health 100. Hit and awareness cues are independent.',recovery:'Alive · carrying 125 shards. Die to create a recoverable drop.'}[tab]));
  }
  document.querySelectorAll('[data-tab]').forEach(b=>{
    b.addEventListener('click',()=>switchTab(b.dataset.tab));
    b.addEventListener('keydown',e=>{let i=Object.keys(notes).indexOf(b.dataset.tab);if(e.key==='ArrowRight')i=(i+1)%4;else if(e.key==='ArrowLeft')i=(i+3)%4;else if(e.key==='Home')i=0;else if(e.key==='End')i=3;else return;e.preventDefault();const next=Object.keys(notes)[i];switchTab(next);$(`tab-${next}`).focus();});
  });
  // One input timestamp is shared by both lanes. Outcomes never use wall-clock frame order.
  function jumpOutcome(assisted) {
    if (jump.input===null) return {accepted:false,at:null,reason:'No input yet'};
    const delta=jump.input-P.jump.event_ms;
    if(jump.scenario==='coyote'){
      if(delta<=0) return {accepted:true,at:jump.input,reason:'Grounded jump'};
      if(assisted&&jump.coyote&&delta<=P.jump.coyote_ms)return {accepted:true,at:jump.input,reason:'Ledge grace accepted'};
      return {accepted:false,at:null,reason:delta<=P.jump.coyote_ms?'No ledge grace':'Outside grace window'};
    }
    if(delta===0)return {accepted:true,at:jump.input,reason:'Landing-frame jump'};
    if(delta>0)return {accepted:true,at:jump.input,reason:'Grounded jump after landing'};
    const held=jump.releasedAt===null||jump.releasedAt>=P.jump.event_ms;
    if(assisted&&jump.buffer&&-delta<=P.jump.buffer_ms&&held)return {accepted:true,at:P.jump.event_ms,reason:'Buffered → jump on landing'};
    return {accepted:false,at:null,reason:!held?'Released before landing':-delta>P.jump.buffer_ms?'Buffer expired':'Early input discarded'};
  }
  function renderJump() {
    $('lab').innerHTML=common(`<div class="stage jump-stage" id="jump-stage" tabindex="0" role="group" aria-label="Shared jump experiment. Space holds jump in a live run. Escape cancels."><div class="stage-top"><strong id="jump-event">Ledge departure · 600 ms</strong><span class="badge" id="jump-time">0 ms · 0.5×</span></div>${['strict','assist'].map(id=>`<div class="jump-lane"><span class="lane-label"><b>${id==='strict'?'No tolerance':'With assistance'}</b></span><span class="lane-result" id="result-${id}">Ready</span><div class="ledge-line" id="ledge-${id}"></div><div class="platform" id="platform-${id}"></div><div class="pawn ${id==='assist'?'assist':''}" id="pawn-${id}"></div></div>`).join('')}<div class="timeline" aria-label="One timeline for both lanes"><span class="event-tick"></span><span id="input-tick" class="input-tick"></span><span id="playhead" class="playhead"></span><span class="event-label" id="event-label">leave ledge · 600</span><span class="timeline-end">1600 ms</span></div></div><div class="controls jump-controls"><label>Case <select id="jump-case"><option value="coyote">After ledge</option><option value="buffer">Before landing</option></select></label><label class="offset">Input offset <input id="jump-offset" type="range" min="-200" max="200" step="10"><output id="offset-value" for="jump-offset"></output></label></div><div class="settings"><label><input id="coyote" type="checkbox">Ledge grace · 100 ms</label><label><input id="buffer" type="checkbox">Jump buffer · 120 ms</label><label><input id="hold" type="checkbox">Hold through landing</label></div><div class="controls"><div class="control-group"><button id="replay" class="primary">Replay input</button><button id="live">Live run</button><button id="jump-press" disabled>Jump · Space</button></div><div class="control-group"><button id="cancel-jump" disabled>Cancel run</button><button id="reset-jump">Reset</button></div></div><p class="hint" id="jump-hint">Amber diamond = input. Mint line = playback. Same timestamp and motion in both lanes; only tolerance changes. All timing values are our proposals.</p>`);
    $('jump-case').value=jump.scenario;$('jump-offset').value=jump.offset;
    ['coyote','buffer','hold'].forEach(id=>{$(id).checked=jump[id];$(id).addEventListener('change',()=>{stopJump('Run cancelled before changing settings.');jump[id]=$(id).checked;jump.t=0;jump.input=null;updateJump();record('Setting changed. Replay uses a fresh shared input.');});});
    $('jump-case').addEventListener('change',()=>{stopJump();jump.scenario=$('jump-case').value;jump.offset=jump.scenario==='coyote'?P.jump.default_coyote_offset_ms:P.jump.default_buffer_offset_ms;jump.t=0;jump.input=null;jump.lastRecord=null;$('jump-offset').value=jump.offset;updateJump();record('Case changed. Both lanes reset to the same start.');});
    $('jump-offset').addEventListener('input',()=>{stopJump();jump.offset=Number($('jump-offset').value);jump.t=0;jump.input=null;jump.lastRecord=null;updateJump();});
    $('replay').addEventListener('click',()=>runJump(false));$('live').addEventListener('click',()=>runJump(true));
    $('cancel-jump').addEventListener('click',()=>stopJump('Run cancelled. Replay or Reset to try again.'));
    $('reset-jump').addEventListener('click',()=>{stopJump();jump=jumpInitial();renderJump();$('reset-jump').focus();record('Reset · default timing and both lanes restored.');});
    $('jump-press').addEventListener('pointerdown',e=>{e.preventDefault();$('jump-press').setPointerCapture(e.pointerId);pressJump();});
    $('jump-press').addEventListener('pointerup',releaseJump);$('jump-press').addEventListener('pointercancel',releaseJump);
    $('jump-press').addEventListener('keydown',e=>{if((e.key===' '||e.key==='Enter')&&!e.repeat){e.preventDefault();pressJump();}});
    $('jump-press').addEventListener('keyup',e=>{if(e.key===' '||e.key==='Enter'){e.preventDefault();releaseJump();}});
    $('jump-stage').addEventListener('keydown',e=>{if(e.key===' '){e.preventDefault();if(!e.repeat)pressJump();}});
    $('jump-stage').addEventListener('keyup',e=>{if(e.key===' '){e.preventDefault();releaseJump();}});
    updateJump();
  }
  function runJump(live) {
    stopJump();jump.running=true;jump.live=live;jump.t=0;jump.input=live?null:P.jump.event_ms+jump.offset;
    jump.releasedAt=live?null:jump.hold?null:jump.input+20;
    record(live?'Live run started · hold Jump or Space.':'Replay started · identical recorded input in both lanes.');
    if(live)$('jump-stage').focus();
    let start=performance.now();
    function tick(now){if(!jump.running||tab!=='jump')return;jump.t=Math.min(P.jump.duration_ms,(now-start)*P.jump.playback_rate);updateJump();if(jump.t<P.jump.duration_ms)frame=requestAnimationFrame(tick);else{
      jump.running=false;jump.lastRecord={scenario:jump.scenario,input_ms:jump.input,released_ms:jump.releasedAt,strict:jumpOutcome(false),assisted:jumpOutcome(true)};updateJump();record(`Finished · no tolerance: ${jumpOutcome(false).accepted?'jump':'no jump'}; assistance: ${jumpOutcome(true).accepted?'jump':'no jump'}.`);
    }}frame=requestAnimationFrame(tick);updateJump();
  }
  function pressJump(){if(!jump.running||!jump.live||jump.input!==null)return;jump.input=Math.round(jump.t);jump.releasedAt=null;record(`Live input captured at ${jump.input} ms for both lanes.`);updateJump();}
  function releaseJump(){if(jump.running&&jump.live&&jump.input!==null&&jump.releasedAt===null){jump.releasedAt=Math.round(jump.t);updateJump();}}
  function updateJump(){
    $('jump-event').textContent=`${jump.scenario==='coyote'?'Ledge departure':'Landing'} · ${P.jump.event_ms} ms`;
    $('event-label').textContent=jump.scenario==='coyote'?'leave ledge · 600':'land · 600';
    $('offset-value').textContent=`${jump.offset>0?'+':''}${jump.offset} ms`;
    $('jump-time').textContent=`${Math.round(jump.t)} ms · 0.5×`;
    $('playhead').style.left=`${jump.t/P.jump.duration_ms*100}%`;
    const marker=jump.input??P.jump.event_ms+jump.offset;$('input-tick').style.left=`${marker/P.jump.duration_ms*100}%`;$('input-tick').hidden=jump.live&&jump.input===null;
    ['strict','assist'].forEach(id=>{
      const outcome=jumpOutcome(id==='assist'),t=jump.t,active=outcome.accepted&&t>=outcome.at;
      let x=10+Math.min(t,1400)/1400*65,y=60;
      if(jump.scenario==='coyote'){x=10+t/600*30;if(t>600&&!active)y=60+Math.pow((t-600)/230,2)*32;}
      else {x=40;y=t<600?60-(1-t/600)*62:60;}
      if(active){let dt=t-outcome.at;y=60-Math.sin(Math.min(dt,900)/900*Math.PI)*64;if(jump.scenario==='coyote')x=Math.min(88,10+t/600*30);}
      $('pawn-'+id).style.left=`${Math.min(x,91)}%`;$('pawn-'+id).style.top=`${Math.min(y,155)}px`;$('pawn-'+id).classList.toggle('fallen',y>126);
      $('platform-'+id).classList.toggle('landing',jump.scenario==='buffer');$('ledge-'+id).hidden=jump.scenario==='buffer';
      const shown=jump.input!==null&&t>=jump.input;const pending=shown&&outcome.accepted&&t<outcome.at;
      $('result-'+id).textContent=!shown?'Waiting for input':pending?'Stored · waiting to land':outcome.reason;
      $('result-'+id).className='lane-result '+(shown&&!pending?(outcome.accepted?'success':'fail'):'');
    });
    $('replay').disabled=jump.running;$('live').disabled=jump.running;$('cancel-jump').disabled=!jump.running;$('jump-press').disabled=!(jump.running&&jump.live);
  }
  function candidates(){
    return P.interaction.objects.map(o=>{const distance=Math.max(.4,o.distance_m-interaction.travel),aim=Math.hypot(o.x-interaction.aim.x,o.y-interaction.aim.y),blocked=o.id==='relay'&&interaction.blocked,done=interaction.completed.includes(o.id),radius=interaction.mode==='exact'?P.interaction.exact_radius_scene_units:P.interaction.nearby_radius_scene_units;
      const reason=done?'Completed':blocked?'Occluded':distance>P.interaction.range_m?'Out of range':aim>radius?'Outside aim area':'Eligible';
      return {...o,distance,aim,reason,eligible:reason==='Eligible',score:P.interaction.aim_weight*(1-aim/P.interaction.nearby_radius_scene_units)+P.interaction.range_weight*(1-distance/P.interaction.range_m)};
    }).sort((a,b)=>b.score-a.score||a.id.localeCompare(b.id));
  }
  function selectTarget(){const list=candidates().filter(o=>o.eligible);if(interaction.cancelled){interaction.selected=null;return;}if(!list.some(o=>o.id===interaction.selected))interaction.selected=list[0]?.id??null;}
  function renderInteraction(){
    $('lab').innerHTML=common(`<div class="stage selection-stage" id="selection-stage" tabindex="0" role="group" aria-label="Aim with arrow keys or tap the scene. N switches candidate. E interacts. Escape cancels selection."><div class="stage-grid"></div><div class="stage-top"><strong id="selection-mode">Nearby candidates</strong><span class="pill">Range limit · 4 m</span></div><div id="aim-area" class="scene-area"><div id="aim-halo" class="aim-halo"></div>${P.interaction.objects.map(o=>`<button class="object" id="object-${o.id}" style="left:${o.x}%;top:${o.y}%" aria-label="Aim at ${o.name}">${({pod:podArt,relay:relayArt,cache:cacheArt})[o.id]}<span class="object-name">${o.name}</span><span class="object-state" id="state-${o.id}"></span></button>`).join('')}<div id="crosshair" class="crosshair"></div></div><div class="scene-note" id="selection-note">Tap an object to center the reticle. Tap empty space to aim freely.</div></div><div id="candidates" class="candidates" aria-label="Candidate priority"></div><div class="controls"><div class="mode-buttons control-group" aria-label="Selection mode"><button id="mode-exact" aria-pressed="false">Exact aim</button><button id="mode-nearby" aria-pressed="true">Nearby candidates</button></div><div class="control-group"><button id="next-target">Next target · N</button><button id="interact" class="primary">Interact · E</button><button id="cancel-target">Cancel selection</button></div></div><div class="controls"><div class="control-group dpad" aria-label="Move aim"><button id="aim-left" aria-label="Aim left">←</button><button id="aim-up" aria-label="Aim up">↑</button><button id="aim-down" aria-label="Aim down">↓</button><button id="aim-right" aria-label="Aim right">→</button></div><div class="control-group"><button id="closer">Move closer</button><button id="back">Move back</button><button id="reset-interaction">Reset</button></div><label><input id="block-relay" type="checkbox">Block relay</label></div><p class="hint">Proposed priority: 70% aim proximity + 30% distance. Occluded, completed and distant objects are excluded. Your switched candidate stays selected while eligible.</p>`);
    const area=$('aim-area');
    function aim(x,y){interaction.aim={x:clamp(x,4,96),y:clamp(y,8,92)};interaction.cancelled=false;interaction.selected=null;updateInteraction();}
    let dragging=false;
    area.addEventListener('pointerdown',e=>{if(e.target.closest('.object'))return;e.preventDefault();dragging=true;area.setPointerCapture(e.pointerId);const r=area.getBoundingClientRect();aim((e.clientX-r.left)/r.width*100,(e.clientY-r.top)/r.height*100);});
    area.addEventListener('pointermove',e=>{if(!dragging)return;const r=area.getBoundingClientRect();aim((e.clientX-r.left)/r.width*100,(e.clientY-r.top)/r.height*100);});
    ['pointerup','pointercancel'].forEach(type=>area.addEventListener(type,()=>{dragging=false;}));
    P.interaction.objects.forEach(o=>$('object-'+o.id).addEventListener('click',()=>{aim(o.x,o.y);record(`Reticle centered on ${o.name}.`);}));
    ['exact','nearby'].forEach(mode=>$('mode-'+mode).addEventListener('click',()=>{interaction.mode=mode;interaction.selected=null;interaction.cancelled=false;updateInteraction();record(`Mode: ${mode==='exact'?'exact aim':'nearby candidates'}. Same scene and reticle retained.`);}));
    function moveAim(dx,dy){aim(interaction.aim.x+dx,interaction.aim.y+dy);record('Reticle moved. Eligible candidates recalculated.');}
    ['left','right','up','down'].forEach(dir=>$('aim-'+dir).addEventListener('click',()=>moveAim((dir==='right'?1:dir==='left'?-1:0)*P.interaction.aim_step_scene_units,(dir==='down'?1:dir==='up'?-1:0)*P.interaction.aim_step_scene_units)));
    $('selection-stage').addEventListener('keydown',e=>{if(e.target!==$('selection-stage'))return;if(e.key.startsWith('Arrow')){e.preventDefault();moveAim((e.key==='ArrowRight'?1:e.key==='ArrowLeft'?-1:0)*5,(e.key==='ArrowDown'?1:e.key==='ArrowUp'?-1:0)*5);}else if(e.key.toLowerCase()==='n'){e.preventDefault();nextTarget();}else if(e.key.toLowerCase()==='e'){e.preventDefault();interact();}});
    $('next-target').addEventListener('click',nextTarget);$('interact').addEventListener('click',interact);
    $('cancel-target').addEventListener('click',cancelTarget);
    ['closer','back'].forEach(id=>$(id).addEventListener('click',()=>{interaction.travel=clamp(interaction.travel+(id==='closer'?1:-1)*P.interaction.movement_step_m,-3,5);interaction.cancelled=false;updateInteraction();record(`${id==='closer'?'Moved closer':'Moved back'}. Range checked again.`);}));
    $('block-relay').checked=interaction.blocked;$('block-relay').addEventListener('change',()=>{interaction.blocked=$('block-relay').checked;interaction.cancelled=false;updateInteraction();record(interaction.blocked?'Relay occluded. It cannot be selected or activated.':'Relay visible again. Eligibility restored.');});
    $('reset-interaction').addEventListener('click',()=>{interaction=interactionInitial();renderInteraction();$('reset-interaction').focus();record('Reset · all three objects restored.');});updateInteraction();
  }
  function nextTarget(){if(interaction.mode!=='nearby')return;const list=candidates().filter(o=>o.eligible);interaction.cancelled=false;if(!list.length){updateInteraction();record('No eligible candidate. Move closer, aim nearer, or remove the obstruction.');return;}let i=list.findIndex(o=>o.id===interaction.selected);interaction.selected=list[(i+1)%list.length].id;updateInteraction();record(`Switched to ${list[(i+1)%list.length].name}. Selection retained until it becomes ineligible.`);}
  function cancelTarget(){interaction.cancelled=true;interaction.selected=null;updateInteraction();record('Selection cancelled. Aim again or use Next target to resume.');}
  function interact(){selectTarget();const o=candidates().find(o=>o.id===interaction.selected&&o.eligible);if(!o){record('Interaction failed: no eligible selection. Aim closer, move within 4 m, or clear occlusion.');return;}interaction.completed.push(o.id);interaction.selected=null;updateInteraction();record(`${o.action} succeeded · ${o.name}. A completed object cannot grant a second result.`);}
  function updateInteraction(){selectTarget();const list=candidates(),eligible=list.filter(o=>o.eligible);$('selection-mode').textContent=interaction.mode==='exact'?'Exact aim · 5-unit radius':'Nearby candidates · 32-unit radius';['exact','nearby'].forEach(mode=>$('mode-'+mode).setAttribute('aria-pressed',String(mode===interaction.mode)));$('crosshair').style.left=interaction.aim.x+'%';$('crosshair').style.top=interaction.aim.y+'%';$('aim-halo').hidden=interaction.mode==='exact';$('aim-halo').style.left=interaction.aim.x+'%';$('aim-halo').style.top=interaction.aim.y+'%';
    list.forEach(o=>{$('object-'+o.id).classList.toggle('selected',o.id===interaction.selected);$('object-'+o.id).classList.toggle('unavailable',!o.eligible);$('object-'+o.id).classList.toggle('occluded',o.id==='relay'&&interaction.blocked);$('state-'+o.id).textContent=`${o.distance.toFixed(1)} m · ${o.reason}`;});
    $('candidates').innerHTML=eligible.length?eligible.map((o,i)=>`<span class="candidate ${o.id===interaction.selected?'active':''}"><span class="rank">${i+1}</span>${o.name} · ${o.score.toFixed(2)}${o.id===interaction.selected?' · selected':''}</span>`).join(''):'No eligible candidates';
    const selected=list.find(o=>o.id===interaction.selected);$('interact').textContent=selected?`${selected.action} ${selected.name} · E`:'Try interaction · E';$('next-target').disabled=interaction.mode==='exact';
  }
  function directionOptions(){return ['left','right','front','behind'].map(d=>`<option value="${d}">${d[0].toUpperCase()+d.slice(1)}</option>`).join('');}
  function renderFeedback(){
    $('lab').innerHTML=common(`<div class="stage feedback-stage" id="feedback-stage" tabindex="0" role="group" aria-label="Feedback workshop. H takes damage. E increases exposure. C hides. Escape clears cues."><div id="world" class="world"><svg viewBox="0 0 900 355" preserveAspectRatio="xMidYMid slice" aria-hidden="true"><rect width="900" height="355" fill="#25373b"/><path d="M0 267 230 166 476 237 755 151 900 211V355H0Z" fill="#324944"/><path d="m0 353 397-150 129 35 374 117" fill="#506153"/><path d="m34 233 16-71 35-15 6 64m679-22 11-93 41 24 10 93" fill="#78927e"/><path d="M0 297 900 297M0 328 900 328" stroke="#788d78" stroke-opacity=".2"/></svg><div class="avatar"></div><span id="observer-marker" class="observer-marker" data-direction="right">◉</span></div><div class="stage-top"><div class="health"><strong id="health-label">HP 100</strong><div class="health-track" aria-hidden="true"><div id="health-fill" class="health-fill"></div></div></div><span class="badge" id="awareness-state">Hidden</span></div><div id="damage-cue" class="cue damage-cue" hidden>${spike}<div id="damage-text">Damage · left</div></div><span id="cue-spike" class="cue-spike" data-direction="left" hidden aria-hidden="true">◀</span><div id="awareness-cue" class="cue awareness-cue" hidden>${eye}<div><span id="awareness-text">Suspicious · right</span><div class="awareness-meter"><span id="awareness-fill"></span></div></div></div><div id="flash-layer" class="flash-layer"></div><div class="feedback-readout"><span id="last-hit">Lightning = damage taken</span><span>Eye = detection risk, not damage</span></div></div><div class="controls"><button id="take-hit" class="primary">Take hit · H</button><button id="expose">Expose · E</button><button id="hide">Hide · C</button><button id="clear-cues">Clear cues</button><button id="restore">Restore health</button></div><div class="controls"><label>Damage direction <select id="damage-direction">${directionOptions()}</select></label><label>Observer direction <select id="observer-direction">${directionOptions()}</select></label></div><div class="settings effect-settings"><label>Shake <input id="shake" type="range" min="0" max="100" step="10"><output id="shake-value" for="shake">0%</output></label><label>Flash <input id="flash" type="range" min="0" max="100" step="10"><output id="flash-value" for="flash">0%</output></label><span id="motion-note" class="hint"></span></div><p class="hint">Damage removes 20 HP. Exposure rises 35 points per press; 100 = spotted. Effects start at zero. Flash is one 260 ms pulse, with an 800 ms hit cooldown. All values and symbols are proposals.</p>`);
    $('damage-direction').value=feedback.damageDir;$('observer-direction').value=feedback.observerDir;
    $('damage-direction').addEventListener('change',()=>{feedback.damageDir=$('damage-direction').value;updateFeedback();record('Damage direction changed. The next hit uses this direction.');});
    $('observer-direction').addEventListener('change',()=>{feedback.observerDir=$('observer-direction').value;updateFeedback();record('Observer direction changed. Damage direction is independent.');});
    ['shake','flash'].forEach(id=>{$(id).value=feedback[id];$(id).addEventListener('input',()=>{feedback[id]=Number($(id).value);if(motion.matches){pulseAnimations.forEach(a=>a.cancel());}updateFeedback();});});
    $('take-hit').addEventListener('click',takeHit);$('expose').addEventListener('click',expose);$('hide').addEventListener('click',hide);
    $('clear-cues').addEventListener('click',clearCues);$('restore').addEventListener('click',()=>{clearEffects();feedback.hp=P.feedback.initial_health;feedback.lastHit=null;feedback.exposure=0;updateFeedback();record('Restored · health 100, warnings cleared. Effect preferences retained.');});
    $('feedback-stage').addEventListener('keydown',e=>{if(e.target!==$('feedback-stage')||e.repeat)return;const fn={h:takeHit,e:expose,c:hide}[e.key.toLowerCase()];if(fn){e.preventDefault();fn();}});updateFeedback();
  }
  function takeHit(){if(feedback.cooling||feedback.hp===0)return;feedback.hp=Math.max(0,feedback.hp-P.feedback.damage);feedback.lastHit=feedback.damageDir;feedback.hitVisible=true;feedback.cooling=true;clearTimeout(hitTimer);clearTimeout(coolTimer);
    pulseAnimations.forEach(a=>a.cancel());pulseAnimations=[];
    if(!motion.matches){const shake=P.feedback.max_shake_px*feedback.shake/100,flash=P.feedback.max_flash_opacity*feedback.flash/100;if(shake)pulseAnimations.push($('world').animate([{transform:'translateX(0)'},{transform:`translateX(${-shake}px)`},{transform:`translateX(${shake}px)`},{transform:'translateX(0)'}],{duration:P.feedback.pulse_ms}));if(flash)pulseAnimations.push($('flash-layer').animate([{opacity:0},{opacity:flash,offset:.2},{opacity:0}],{duration:P.feedback.pulse_ms}));}
    hitTimer=setTimeout(()=>{feedback.hitVisible=false;if(tab==='feedback')updateFeedback();},P.feedback.hit_cue_ms);coolTimer=setTimeout(()=>{feedback.cooling=false;if(tab==='feedback')updateFeedback();},P.feedback.hit_cooldown_ms);updateFeedback();record(`Damage from ${feedback.damageDir} · −20 HP. ${feedback.hp===0?'Downed. Restore health to continue.':`HP ${feedback.hp}. Awareness unchanged.`}`);
  }
  function expose(){feedback.exposure=clamp(feedback.exposure+P.feedback.exposure_step,0,100);updateFeedback();record(`${feedback.exposure===100?'Spotted':'Suspicious'} · ${feedback.observerDir}, ${feedback.exposure}% exposure. Health unchanged.`);}
  function hide(){feedback.exposure=0;updateFeedback();record('Hidden · awareness cleared. Damage and health unchanged.');}
  function clearCues(){clearEffects();feedback.exposure=0;updateFeedback();record('Cues cleared · health retained. Take hit or Expose to repeat.');}
  function updateFeedback(){const state=feedback.exposure===0?'Hidden':feedback.exposure===100?'Spotted':'Suspicious';$('health-label').textContent=`HP ${feedback.hp}${feedback.hp===0?' · downed':''}`;$('health-fill').style.width=feedback.hp+'%';$('awareness-state').textContent=`${state}${feedback.exposure?' · '+feedback.exposure+'%':''}`;$('awareness-state').classList.toggle('warn',feedback.exposure>0);$('damage-cue').hidden=!feedback.hitVisible;$('cue-spike').hidden=!feedback.hitVisible;$('cue-spike').dataset.direction=feedback.lastHit||feedback.damageDir;$('damage-text').textContent=`Damage · ${feedback.lastHit||feedback.damageDir}`;$('last-hit').textContent=feedback.lastHit?`Last hit · ${feedback.lastHit} · −20 HP`:'Lightning = damage taken';$('awareness-cue').hidden=feedback.exposure===0;$('awareness-text').textContent=`${state} · ${feedback.observerDir}`;$('awareness-fill').style.width=feedback.exposure+'%';$('observer-marker').hidden=feedback.exposure===0;$('observer-marker').dataset.direction=feedback.observerDir;$('take-hit').disabled=feedback.cooling||feedback.hp===0;$('expose').disabled=feedback.exposure===100;$('shake-value').textContent=feedback.shake+'%';$('flash-value').textContent=feedback.flash+'%';$('motion-note').textContent=motion.matches?'Reduced motion active · effects suppressed.':'Cue shapes and text stay readable at zero intensity.';}
  motion.addEventListener('change',()=>{pulseAnimations.forEach(a=>a.cancel());if(tab==='feedback')updateFeedback();});
  function renderRecovery(){
    $('lab').innerHTML=common(`<div class="stage recovery-stage" id="recovery-stage" tabindex="0" role="group" aria-label="Recovery route. Arrow keys move, D dies, E recovers. Escape cancels checkpoint choice."><div class="stage-grid"></div><div class="stage-top"><div class="ledger"><span>Carrying<strong id="wallet">125</strong></span><span>Recoverable<strong id="pile-value">0</strong></span><span>Lost<strong id="lost-value">0</strong></span></div><span class="badge" id="life-state">Alive</span></div><div class="trail"></div><div class="landmark" style="left:14%">${shrine}Home checkpoint</div><div class="landmark" id="relay-landmark" style="left:38%">${shrine}Relay checkpoint</div><div id="recovery-pawn" class="recovery-pawn"><div class="pawn"></div></div><div id="shard-pile" class="shard-pile" hidden>${shard}<span id="pile-label"></span></div><div class="death-label" id="death-label" hidden>Downed · choose a return point</div></div><div class="step-chips" aria-label="Recovery milestone">${['Alive','Dropped','Returned','Recovered','Lost'].map(s=>`<span id="step-${s}">${s}</span>`).join('')}</div><fieldset id="return-choice" class="return-choice" hidden><legend>Choose your return point</legend><div class="choice-options"><label><input id="return-home" name="checkpoint" type="radio" value="home">Home · last rest point</label><label><input id="return-relay" name="checkpoint" type="radio" value="relay">Relay · nearby, if available</label></div><div class="choice-actions"><button id="confirm-return" class="primary">Confirm return</button><button id="cancel-return">Cancel choice</button></div></fieldset><div class="controls"><button id="die" class="danger">Die · D</button><button id="choose-return" hidden>Choose return point</button><button id="advance">Advance →</button><button id="retreat">← Go back</button><button id="recover" class="primary">Recover shards · E</button><button id="find-shards">Find 25 shards</button><button id="reset-recovery">Reset</button></div><div class="settings"><label><input id="relay-available" type="checkbox">Nearby checkpoint available</label><span id="recovery-distance" class="hint"></span></div><p class="hint">Die before recovering a drop: that old drop is lost. Die after recovering it: carried shards form a new drop. Find 25 works once per life; Reset restores the teaching fixture.</p>`);
    $('die').addEventListener('click',die);$('choose-return').addEventListener('click',chooseReturn);$('confirm-return').addEventListener('click',confirmReturn);$('cancel-return').addEventListener('click',cancelReturn);
    ['home','relay'].forEach(id=>$('return-'+id).addEventListener('change',()=>{recovery.checkpoint=id;record(`Return point selected: ${id}. No shards recovered yet.`);updateRecovery();}));
    $('advance').addEventListener('click',()=>moveRecovery(1));$('retreat').addEventListener('click',()=>moveRecovery(-1));$('recover').addEventListener('click',recover);$('find-shards').addEventListener('click',findShards);
    $('relay-available').checked=recovery.available;$('relay-available').addEventListener('change',()=>{recovery.available=$('relay-available').checked;if(!recovery.available&&recovery.checkpoint==='relay')recovery.checkpoint='home';updateRecovery();record(recovery.available?'Nearby checkpoint available for the next return.':'Nearby checkpoint unavailable. Home remains available.');});
    $('reset-recovery').addEventListener('click',()=>{recovery=recoveryInitial();renderRecovery();$('reset-recovery').focus();record('Reset · carrying 125 shards; no drop or loss.');});
    $('recovery-stage').addEventListener('keydown',e=>{if(e.target!==$('recovery-stage')||e.repeat)return;const fn={ArrowRight:()=>moveRecovery(1),ArrowLeft:()=>moveRecovery(-1),d:die,e:recover}[e.key]||{d:die,e:recover}[e.key.toLowerCase()];if(fn){e.preventDefault();fn();}});updateRecovery();
  }
  function die(){if(!recovery.alive)return;const old=recovery.pile?.amount??0;recovery.lost+=old;recovery.pile=recovery.wallet>0?{amount:recovery.wallet,x:recovery.x}:null;const dropped=recovery.wallet;recovery.wallet=0;recovery.alive=false;recovery.menu=true;recovery.checkpoint='home';recovery.step=old>0?'Lost':'Dropped';updateRecovery();record(`Died · dropped ${dropped}. ${old>0?`Previous ${old} permanently lost.`:'Choose a checkpoint to return.'}`);$('return-home').focus();}
  function chooseReturn(){if(recovery.alive)return;recovery.menu=true;updateRecovery();$('return-home').focus();record('Checkpoint choice reopened. The drop has not changed.');}
  function cancelReturn(){if(!recovery.menu)return;recovery.menu=false;updateRecovery();$('choose-return').focus();record('Return cancelled · still downed. Choose return point to resume.');}
  function confirmReturn(){if(recovery.alive||!recovery.menu)return;if(recovery.checkpoint==='relay'&&!recovery.available){recovery.checkpoint='home';updateRecovery();record('Nearby checkpoint unavailable. Select Home.');return;}recovery.alive=true;recovery.menu=false;recovery.x=recovery.checkpoint==='relay'?P.recovery.relay_position:P.recovery.home_position;recovery.found=false;recovery.step='Returned';updateRecovery();record(`Returned to ${recovery.checkpoint}. Carrying 0; ${recovery.pile?.amount??0} still at the drop.`);$('advance').focus();}
  function moveRecovery(direction){if(!recovery.alive){record('Cannot move while downed. Choose a return point.');return;}recovery.x=clamp(recovery.x+direction*P.recovery.movement_step,7,93);updateRecovery();record(recovery.pile?`Moved · ${Math.abs(recovery.x-recovery.pile.x)} route units from the drop.`:'Moved · no recoverable drop.');}
  function recover(){if(!recovery.alive){record('Cannot recover while downed. Return first.');return;}if(!recovery.pile){record('Nothing to recover. A drop can be collected only once.');return;}if(Math.abs(recovery.x-recovery.pile.x)>P.recovery.recover_radius){record('Recovery failed · too far from the drop. Advance or Go back.');return;}let amount=recovery.pile.amount;recovery.wallet+=amount;recovery.pile=null;recovery.step='Recovered';updateRecovery();record(`Recovered ${amount} shards. Carrying ${recovery.wallet}; no recoverable drop remains.`);}
  function findShards(){if(!recovery.alive||recovery.found)return;recovery.wallet+=P.recovery.find_shards;recovery.found=true;updateRecovery();record(`Found 25 shards. Carrying ${recovery.wallet}. This pickup is exhausted for this life.`);}
  function updateRecovery(){$('wallet').textContent=recovery.wallet;$('pile-value').textContent=recovery.pile?.amount??0;$('lost-value').textContent=recovery.lost;$('life-state').textContent=recovery.alive?'Alive':'Downed';$('life-state').classList.toggle('warn',!recovery.alive);$('recovery-pawn').style.left=recovery.x+'%';$('recovery-pawn').classList.toggle('dead',!recovery.alive);$('shard-pile').hidden=!recovery.pile;if(recovery.pile){$('shard-pile').style.left=recovery.pile.x+'%';$('pile-label').textContent=recovery.pile.amount+' shards';}$('death-label').hidden=recovery.alive;$('death-label').textContent=recovery.menu?'Downed · choose a return point':'Downed · return choice cancelled';$('return-choice').hidden=!recovery.menu;$('choose-return').hidden=recovery.alive||recovery.menu;['die','advance','retreat','find-shards'].forEach(id=>$(id).disabled=!recovery.alive||(id==='find-shards'&&recovery.found));$('recover').disabled=!recovery.alive;$('return-relay').disabled=!recovery.available;$('return-home').checked=recovery.checkpoint==='home';$('return-relay').checked=recovery.checkpoint==='relay';$('relay-landmark').style.opacity=recovery.available?'1':'.4';$('recovery-distance').textContent=recovery.pile?`${Math.abs(recovery.x-recovery.pile.x)} route units to drop · recover within 8`:'No recoverable drop';['Alive','Dropped','Returned','Recovered','Lost'].forEach(s=>$('step-'+s).classList.toggle('current',s===recovery.step));}
  document.addEventListener('keydown',e=>{if(e.key!=='Escape')return;if(tab==='jump')stopJump('Run cancelled with Escape. Replay or Reset to retry.');else if(tab==='interaction')cancelTarget();else if(tab==='feedback')clearCues();else if(tab==='recovery')cancelReturn();});
  window.addEventListener('blur',()=>{releaseJump();stopJump('Run cancelled when window lost focus.');});
  document.addEventListener('visibilitychange',()=>{if(document.hidden)stopJump('Run cancelled while page was hidden.');});
  // Read-only diagnostics. Browser checks drive native UI events, never mutate this state.
  Object.defineProperty(window,'gameplaySnapshot',{value:()=>JSON.parse(JSON.stringify({tab,jump:{...jump,outcomes:{strict:jumpOutcome(false),assisted:jumpOutcome(true)}},interaction:{...interaction,candidates:candidates()},feedback:{...feedback,effectsSuppressed:motion.matches},recovery,records})),writable:false});
  switchTab('jump');
})();
