'use strict';
(() => {
const F=window.INTERACTION_FIXTURE, LABS=window.INTERACTION_LABS, SOURCES=window.INTERACTION_SOURCES;
const $=id=>document.getElementById(id), esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let lab=LABS.find(x=>x.id===location.hash.slice(1))||LABS[0], mode='corrected', state, epoch=0, modalOrigin=null, modalCancel=null;
const trace=[]; let audioContext=null;
const btn=(id,text,extra='')=>`<button id="${id}" data-action="${id}" ${extra}>${text}</button>`;
const status=text=>`<p id="runtime-status" class="status" role="status" aria-live="polite" aria-atomic="true">${text}</p>`;
const head=(name,note)=>`<div class="runtime-head"><strong>${name}</strong><small>${note}</small></div>`;
const terrain=`<svg viewBox="0 0 600 330" preserveAspectRatio="xMidYMid slice" aria-hidden="true"><path fill="#2d4939" d="M0 160 100 40 190 140 310 10 470 190 600 80V330H0Z"/><path fill="#41624b" d="M0 280 120 170 210 250 370 120 570 290 600 240V330H0Z"/><path d="M180 330Q310 180 410 210T590 30" fill="none" stroke="#87a687" stroke-width="8"/><path d="M180 330Q310 180 410 210T590 30" fill="none" stroke="#d0dcc2" stroke-width="2" stroke-dasharray="7 7"/></svg>`;
function record(action,extra={}){trace.push({at:Math.round(performance.now()),lab:lab.id,mode,action,...extra});if(trace.length>800)trace.shift();}
function say(text,type=''){const node=$('runtime-status');if(node){node.textContent=text;node.className='status'+(type?' '+type:'');}record('status',{text});}
function initial(){return {
 input:{attack:0,purchases:0,dismissTarget:'attack',modal:false,note:'',owner:'arena',last:'No input yet',polling:false,physicalA:false,armed:true,polledFrames:0},
 overload:{delivered:false,clock:0,claimed:false,shards:0,ack:false,drawer:''},
 decisions:{selected:'iron',equipped:'reed',ore:F.materials.ore,fiber:F.materials.fiber,crafted:false,coins:F.coins,charm:false,shop:false},
 adaptation:{route:'east',note:'',keyboard:false,long:false,scale:1,editing:{start:0,end:0,direction:'none'},focusLost:0,reviews:0},
 recovery:{query:'',draft:'',revision:0,ackRevision:0,ackDraft:'',selected:null,results:[],searchStatus:'idle',saveStatus:'idle',online:true,failNext:false,slowNext:false,nextId:0,pending:null,requests:0,ignored:0,ackRequest:null},
 feedback:{channel:'amber',pending:null,nextId:0,requests:0,successes:0,failures:0,pressed:false,failNext:false,reduced:matchMedia('(prefers-reduced-motion: reduce)').matches,sound:false,haptic:false,events:[],outcome:'idle',sensory:'Audio and haptics off. Text and symbols always remain.'}
}[lab.id];}
function openModal(title,body,actions,origin,onCancel=null){
 modalOrigin=origin||document.activeElement;modalCancel=onCancel;$('modal-title').textContent=title;$('modal-body').innerHTML=body;$('modal-actions').innerHTML=actions;
 $('modal').showModal();$('modal-actions').querySelector('button')?.focus();record('modal-open',{title,focus:document.activeElement.id});
}
function closeModal(canceled=false){
 const origin=modalOrigin,callback=modalCancel;modalOrigin=null;modalCancel=null;$('modal').close();
 if(origin?.isConnected)origin.focus();if(canceled)callback?.();record('modal-close',{canceled,focus:document.activeElement.id});
}
$('modal').addEventListener('cancel',e=>{e.preventDefault();closeModal(true);});
$('modal').addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b)action(b.dataset.action,e);});
function switchLab(next,implementation=mode){
 if($('modal').open)closeModal(true);epoch++;lab=next;mode=implementation;state=initial();location.hash=lab.id;render();record('fixture-reset');
}
function render(){
 $('labs').innerHTML=LABS.map((x,i)=>`<button id="lab-${x.id}" data-lab="${x.id}" aria-current="${x===lab}">${i+1}. ${x.label}</button>`).join('');
 $('lab-number').textContent=`Lab ${LABS.indexOf(lab)+1} / ${lab.layout}`;$('lab-title').textContent=lab.title;$('short-explanation').textContent=lab.explanation;
 $('problem').setAttribute('aria-pressed',String(mode==='problem'));$('corrected').setAttribute('aria-pressed',String(mode==='corrected'));
 $('procedure').innerHTML=lab.procedure.map(p=>`<li>${esc(p)}</li>`).join('');$('input').textContent=lab.input;$('output').textContent=lab.output;$('reason').textContent=lab.reason;
 $('reuse').innerHTML=`${esc(lab.reuse)} <a href="${lab.reusePath}">Existing contract</a>.`;$('instruction').textContent=lab.instruction;
 $('source-links').innerHTML=lab.sources.map(id=>`<p><a href="${SOURCES[id].url}" target="_blank" rel="noreferrer">${esc(SOURCES[id].title)}</a><br><span class="hint">${esc(SOURCES[id].note)}</span></p>`).join('');$('copy-status').textContent='';
 $('specimen').className=mode==='problem'?'problem-specimen':'corrected-specimen';
 const views={input:inputView,overload:overloadView,decisions:decisionsView,adaptation:adaptationView,recovery:recoveryView,feedback:feedbackView};$('specimen').innerHTML=views[lab.id]();
 if(lab.id==='input'){$('arena').addEventListener('click',e=>{if(mode==='problem'&&e.target.closest('.fault-overlay'))worldAction(state.dismissTarget,'bubbled dismiss');});updateInput();}
 if(lab.id==='overload')updateOverload();if(lab.id==='decisions')updateDecisions();if(lab.id==='adaptation'){bindEditor();updateAdaptation();}
 if(lab.id==='recovery')updateRecovery();if(lab.id==='feedback')updateFeedback();
}
function inputView(){return head('Trailwatch · local encounter','Attack / demo purchase')+`<div id="arena" class="arena" tabindex="0" role="group" aria-label="Encounter arena; A attacks, P makes a demo purchase when focused"><div class="arena-art">${terrain}</div><div class="scene-name">North gate / training encounter</div><div class="arena-line"><div><span class="actor" aria-hidden="true">◇</span><p>Training sentinel</p></div><div class="actions">${btn('attack','Attack · A')}${btn('purchase','Demo purchase · P')}</div></div></div><div class="input-bottom"><div><label class="field"><span>Radio note · type ap</span><input id="radio-note" autocomplete="off" maxlength="80" placeholder="All clear, proceed"></label><label class="check"><input id="polling" type="checkbox">Polled-input model · hold A on arena</label><p class="hint">200 ms update model. Close requires release and a fresh press.</p></div><div><label class="field"><span>Action under the dismiss gesture</span><select id="dismiss-target"><option value="attack">Attack</option><option value="purchases">Demo purchase</option></select></label>${btn('open-notice','Open notice')}</div></div><div class="metrics"><span>Attacks: <strong id="attack-count">0</strong></span><span>Demo purchases: <strong id="purchase-count">0</strong></span><span id="input-owner"></span><span id="poll-state"></span></div>`+status('Focus the arena to use A/P; text entry belongs to the radio note.');}
function worldAction(which,cause){if(mode==='corrected'&&(state.modal||$('modal').open))return;state[which==='attack'?'attack':'purchases']++;state.owner='arena';state.last=cause;updateInput();say(`${which==='attack'?'Attack':'Demo purchase'} recorded · ${cause}.`);record('world-action',{which,cause,attack:state.attack,purchases:state.purchases});}
function updateInput(){$('attack-count').textContent=state.attack;$('purchase-count').textContent=state.purchases;$('input-owner').textContent=`Last owner: ${state.owner} · ${state.last}`;$('poll-state').textContent=`Held A: ${state.physicalA} · armed: ${state.armed} · polled frames: ${state.polledFrames}`;}
function overloadView(){return head('Valley dispatch','Synthetic clock, not live time')+`<div class="dispatch"><div class="route-map">${terrain}<div class="map-label"><strong>North gate</strong><span>Route remains the primary task.</span></div><div id="fault-stack" class="fault-stack"></div></div><div id="dispatch-rail" class="dispatch-rail"></div></div><div class="dispatch-tools">${btn('burst','Deliver burst')}${btn('advance-clock','Advance 6 seconds')}<span id="clock" class="hint"></span></div>`+status('Deliver the same nine notices in either implementation.');}
function updateOverload(){
 const s=state,active=s.delivered?F.notices.filter(n=>mode==='problem'?s.clock<6:(n.kind==='hazard'?!s.ack:n.expires===null||s.clock<n.expires)):[];
 $('clock').textContent=`Fixture clock: ${s.clock}s · claimed: ${s.shards} shards`;
 if(mode==='problem'){$('fault-stack').innerHTML=active.map(n=>`<div class="notice"><p>${esc(n.text)}</p></div>`).join('');$('dispatch-rail').innerHTML='<h3>All messages, same priority</h3><p>Nine notices obscure the route. A single expiry clears everything, including unclaimed rewards.</p><p class="hint">Deliberate notification-policy fault.</p>';return;}
 $('fault-stack').innerHTML='';let content=s.delivered?(s.ack?'':`<div class="notice hazard"><span class="badge">Danger · needs acknowledgment</span><p><strong>Storm crossing · take shelter</strong></p>${btn('ack-hazard','Acknowledge hazard')}</div>`)+`<div class="notice quest"><span class="hint">Next objective</span><p><strong>Reach the north gate</strong><br>180 m along the west path</p></div><div class="notice"><strong>Rewards · 3 events / 20 shards</strong><p>Relay repaired, trail mapped, camp supplied.</p>${btn('claim-rewards',s.claimed?'Claimed · 20 shards':'Claim 20 shards',s.claimed?'disabled':'') }</div><div class="actions">${btn('toggle-chat',s.drawer?'Close chat history':(s.clock>=6?'Chat history · 3':'Chat · 3 new'),`aria-expanded="${Boolean(s.drawer)}"`)}</div><div id="chat-history" ${s.drawer?'':'hidden'}><ul class="history">${F.notices.filter(n=>n.kind==='chat').map(n=>`<li>${esc(n.text)}</li>`).join('')}</ul></div><p class="hint">${s.clock>=6?'Chat cues moved to history; ambient cue expired.':'Chat cues expire at 6s; ambient cue at 4s. Actionable records persist.'}</p>`:'<h3>No interruptions yet</h3><p>The next objective, hazard and grouped rewards will stay beside the route.</p>';
 const focusId=document.activeElement?.id;$('dispatch-rail').innerHTML=content;if(focusId&&$(focusId))$(focusId).focus();else if(focusId==='ack-hazard')$('toggle-chat')?.focus();
}
function weapon(){return `<svg class="weapon" viewBox="0 0 66 82" aria-hidden="true"><path d="M43 4 55 5 51 19 30 52 23 48Z" fill="#b6c4b9" stroke="#395144" stroke-width="2"/><path d="m17 42 20 12-4 6-20-12Z" fill="#ae8652" stroke="#61482f"/><path d="m20 52 8 5-12 18-8-5Z" fill="#795834" stroke="#61482f"/></svg>`;}
function decisionsView(){return head('Field workbench','Rank 2 · local stock')+`<div class="bench"><div class="item-list" aria-label="Inspect an item">${btn('inspect-reed','Reed sword<span>Starter equipment</span>')}${btn('inspect-iron','Iron blade<span>Owned</span>')}${btn('inspect-crafted','Field dagger<span>Crafting recipe</span>')}</div><div id="item-detail" class="item-detail"></div></div><div class="shop"><div class="shop-header"><h3>Camp shop</h3><span id="coin-count"></span>${btn('toggle-shop','Open shop','aria-expanded="false"')}</div><div id="shop-list" class="shop-list" hidden></div></div>`+status('Inspect the tradeoff against the currently equipped item.');}
function updateDecisions(){
 const s=state,item=F.stats[s.selected],current=F.stats[s.equipped];for(const id of ['reed','iron','crafted'])$('inspect-'+id).setAttribute('aria-pressed',String(s.selected===id));
 let content=`<div class="item-heading">${weapon()}<div><h3>${esc(item.name)}</h3><span class="badge">${s.selected===s.equipped?'Equipped':s.selected==='crafted'&&!s.crafted?'Recipe · not owned':'Owned'}</span></div></div>`;
 if(mode==='corrected')content+=`<p class="hint">Compared with equipped ${esc(current.name)}. Higher weight is a cost.</p><table class="stats"><thead><tr><th>Stat</th><th>Current</th><th>After</th><th>Change</th></tr></thead><tbody>${['attack','guard','weight'].map(k=>`<tr><td>${k[0].toUpperCase()+k.slice(1)}</td><td>${current[k]}</td><td>${item[k]}</td><td id="delta-${k}">${item[k]-current[k]>0?'+':''}${item[k]-current[k]}</td></tr>`).join('')}</tbody></table>`;
 else content+=`<p>Attack <strong>${item.attack}</strong> · Guard <strong>${item.guard}</strong> · Weight <strong>${item.weight}</strong></p><p class="hint">Current equipment and tradeoffs are omitted in this fault.</p>`;
 if(s.selected==='crafted'&&!s.crafted){content+=`<div class="bill"><div><strong>Ore · ${s.ore} / ${F.recipe.ore}</strong><span class="${s.ore<3?'warning':''}">${s.ore<3?'⚠ Missing '+(3-s.ore)+' ore':'✓ Enough ore'}</span></div><div><strong>Fiber · ${s.fiber} / ${F.recipe.fiber}</strong><span>${s.fiber<2?'⚠ Missing '+(2-s.fiber)+' fiber':'✓ Enough fiber'}</span></div></div><div class="actions">${btn('craft','Craft Field dagger',mode==='corrected'&&(s.ore<3||s.fiber<2)?'disabled':'')}${btn('gather-ore','Gather 1 ore',s.ore>=3?'disabled':'')}</div>`;}
 else content+=`<div class="actions" style="margin-top:18px">${btn('equip',s.equipped===s.selected?'Equipped':'Equip '+esc(item.name),mode==='corrected'&&s.equipped===s.selected?'disabled':'')}</div>`;
 const focusId=document.activeElement?.id;$('item-detail').innerHTML=content;if(focusId&&$(focusId)&&!$(focusId).disabled)$(focusId).focus();
 $('coin-count').textContent=`${s.coins} demo coins · ore ${s.ore} / fiber ${s.fiber}`;$('toggle-shop').setAttribute('aria-expanded',String(s.shop));$('toggle-shop').textContent=s.shop?'Close shop':'Open shop';$('shop-list').hidden=!s.shop;
 $('shop-list').innerHTML=[['reed','Reed sword',s.equipped==='reed'?'Equipped':'Owned · inspect or equip',10],['iron','Iron blade',s.equipped==='iron'?'Equipped':'Owned · inspect or equip',15],['solar','Solar blade','Unavailable · requires Rank 3',25],['charm','Copper charm',s.charm?'Owned · unique charm':'Available · 20 demo coins',20]].map(([id,name,desc,price])=>`<div class="shop-item"><strong>${name}</strong><p>${mode==='problem'?price+' coins':desc}</p>${btn('shop-'+id,mode==='problem'?'Buy again':id==='solar'?'Requires Rank 3':id==='charm'?(s.charm?'Owned':'Review · 20 coins'):(s.equipped===id?'Equipped':'Equip owned'),mode==='corrected'&&(id==='solar'||(id==='charm'&&s.charm)||s.equipped===id)?'disabled':'')}</div>`).join('');
 if(focusId?.startsWith('shop-')&&$(focusId)&&!$(focusId).disabled)$(focusId).focus();
}
function adaptationView(){return head('Ridge expedition · dispatch editor','Screen state is live')+`<div class="screen-controls"><label class="check"><input id="keyboard-model" type="checkbox">Keyboard occlusion model</label><label class="check"><input id="long-labels" type="checkbox">Long English labels</label><label class="check"><input id="large-text" type="checkbox">200% text</label></div><div id="screen-model" class="screen-model ${mode==='problem'?'faulty':''}"><div id="editor-surface" class="editor-surface"></div><div class="keyboard-model">Software keyboard occlusion model · no native keyboard opened</div></div><div class="request-ledger" id="screen-ledger"></div>`+status('Choose a route and draft a note; resize without losing editing state.');}
function editorMarkup(){return `<section><h3>Route</h3><label class="route"><input type="radio" name="route" id="route-east" value="east" ${state.route==='east'?'checked':''}><span id="east-label"></span></label><label class="route"><input type="radio" name="route" id="route-west" value="west" ${state.route==='west'?'checked':''}><span id="west-label"></span></label><p class="hint">One selected route for this dispatch.</p></section><section><label class="field"><span id="note-label">Dispatch note</span><textarea id="dispatch-note" maxlength="400" placeholder="Record where the team should meet.">${esc(state.note)}</textarea></label><div class="actions">${btn('review-dispatch','Review dispatch','class="primary"')}${btn('restore-editor','Continue editing')}</div><p class="range-output" id="range-output"></p></section>`;}
function bindEditor(){$('editor-surface').innerHTML=editorMarkup();$('dispatch-note').addEventListener('select',captureEditing);$('dispatch-note').addEventListener('keyup',captureEditing);$('dispatch-note').addEventListener('blur',captureEditing);}
function captureEditing(){if(lab.id!=='adaptation'||!$('dispatch-note'))return;const n=$('dispatch-note');state.editing={start:n.selectionStart,end:n.selectionEnd,direction:n.selectionDirection};$('range-output').textContent=`Retained range: ${state.editing.start}–${state.editing.end} · ${state.note.length} characters`;}
function restoreEditor(){const n=$('dispatch-note');if(!n)return;n.focus({preventScroll:true});n.setSelectionRange(state.editing.start,state.editing.end,state.editing.direction);n.scrollIntoView({block:'nearest'});captureEditing();}
function updateAdaptation(){
 const s=state;$('screen-model').classList.toggle('keyboard',s.keyboard);$('editor-surface').style.setProperty('--text-scale',s.scale);
 $('east-label').textContent=s.long?'East ridge observation route with sheltered river crossing and accessible return point':'East ridge · 2.4 km';$('west-label').textContent=s.long?'West valley supply route requiring a longer ascent before the northern expedition gate':'West valley · 3.1 km';$('note-label').textContent=s.long?'Dispatch note for the next expedition team and overnight route coordinator':'Dispatch note';
 $('screen-ledger').textContent=`Route ID: ${s.route} · native field retained · viewport ${innerWidth}×${innerHeight} · focus rebuilds: ${s.focusLost}`;captureEditing();
}
function adaptChange(){if(mode==='problem'){state.focusLost++;state.route='east';state.editing={start:0,end:0,direction:'none'};bindEditor();say('Problem rebuilt the editor: route resets; native focus and text selection are lost.','error');}updateAdaptation();if(mode==='corrected')restoreEditor();}
function recoveryView(){return head('Survey notebook','Local response simulation')+`<div class="recovery-controls"><label class="check"><input id="fail-next" type="checkbox">Fail next response</label><label class="check"><input id="slow-next" type="checkbox">Slow next · 1600 ms</label>${btn('disconnect','Disconnect')}${btn('reconnect','Reconnect','hidden')}</div><div class="notebook"><section class="search-shelf"><h3>Find a survey</h3><label class="field"><span>Search title</span><input id="search-query" placeholder="Try relay or zzz" maxlength="80" autocomplete="off"></label><div class="actions">${btn('search','Search','class="primary"')}${btn('cancel-request','Cancel request','hidden')}</div><p id="search-message" class="hint" role="status"></p><div id="results" class="results"></div></section><section class="draft-sheet"><h3>Field note</h3><p id="selected-survey" class="hint">No survey selected.</p><label class="field"><span>Draft · remains editable while saving</span><textarea id="survey-draft" placeholder="Enter a survey note…" maxlength="400"></textarea></label><div class="actions">${btn('save','Save local snapshot','class="primary"')}<span id="dirty" class="badge">No unsaved edits</span></div><p class="hint">Memory in this tab only. No server or reload persistence.</p></section></div><div id="request-ledger" class="request-ledger"></div>`+status('Enter work, then simulate waiting, cancellation, save failure or a disconnect.');}
function updateRecovery(){
 const s=state,busy=Boolean(s.pending);$('search').disabled=mode==='corrected'&&(busy||!s.online);$('save').disabled=mode==='corrected'&&(busy||!s.online||!s.draft.trim());$('cancel-request').hidden=!busy;$('disconnect').hidden=!s.online;$('reconnect').hidden=s.online;$('reconnect').disabled=mode==='corrected'&&busy;
 $('fail-next').checked=s.failNext;$('slow-next').checked=s.slowNext;$('dirty').textContent=s.revision===s.ackRevision?'No unsaved edits':`Unsaved revision ${s.revision}`;
 $('request-ledger').textContent=`requestId: ${s.pending?.id??'none'} / last ${s.nextId} · submittedRev: ${s.pending?.revision??'—'} · draftRev: ${s.revision} · acknowledgedRev: ${s.ackRevision} · acknowledgedRequest: ${s.ackRequest??'none'} · requests: ${s.requests} · ignoredLate: ${s.ignored} · ${s.online?'online':'offline'}`;
 const focusId=document.activeElement?.id;$('results').innerHTML=s.results.map((r,i)=>btn('result-'+i,esc(r),`aria-pressed="${s.selected===r}"`)).join('');if(focusId?.startsWith('result-')&&$(focusId))$(focusId).focus();$('selected-survey').textContent=s.selected?`Selected: ${s.selected}`:'No survey selected.';
 $('search-message').textContent=s.searchStatus==='empty'?(mode==='problem'?'':`No surveys match “${s.query}”. Try relay or clear your search.`):s.searchStatus==='pending'?'Searching…':s.searchStatus==='ready'?`${s.results.length} surveys found.`:s.searchStatus==='error'?'Search failed; your query is retained. Retry Search.':'';
}
function request(kind){
 const s=state;if(mode==='corrected'&&(s.pending||(!s.online&&kind!=='reconnect')||(kind==='save'&&!s.draft.trim())))return;
 const job={id:++s.nextId,kind,revision:s.revision,draft:s.draft,query:s.query,fail:s.failNext,delay:s.slowNext?1600:F.delayMs},thisEpoch=epoch;
 s.failNext=false;s.slowNext=false;s.pending=job;s.requests++;if(kind==='search')s.searchStatus='pending';if(kind==='save')s.saveStatus='pending';updateRecovery();
 say(mode==='problem'&&kind==='save'?'Saved! (premature claim in this fault)':`${kind==='save'?'Saving revision '+job.revision:kind==='search'?'Searching':'Reconnecting'} · request ${job.id}.`,'busy');record('request-start',job);
 setTimeout(()=>{
  if(thisEpoch!==epoch)return;if(mode==='corrected'&&s.pending?.id!==job.id){s.ignored++;updateRecovery();record('late-response-ignored',{id:job.id,revision:job.revision});return;}
  s.pending=null;
  if(job.fail){if(kind==='search')s.searchStatus='error';if(kind==='save'){s.saveStatus='error';if(mode==='problem'){s.draft='';$('survey-draft').value='';}}say(`${kind} failed · ${mode==='corrected'?'entered work retained; retry when ready.':'draft cleared by the fault.'}`,'error');}
  else if(kind==='search'){s.results=job.query.toLowerCase().includes('relay')?['North relay inspection','Valley relay repair']:[];s.searchStatus=s.results.length?'ready':'empty';say(s.results.length?'Search complete · 2 surveys.':mode==='corrected'?`No results for “${job.query}”. Try relay.`:'Search finished.');}
  else if(kind==='save'){s.ackDraft=job.draft;s.ackRevision=job.revision;s.ackRequest=job.id;s.saveStatus='success';if(mode==='problem'){s.draft=job.draft;$('survey-draft').value=job.draft;s.revision=job.revision;}say(s.revision===job.revision?`✓ Local snapshot acknowledged · revision ${job.revision}.`:`✓ Revision ${job.revision} acknowledged; newer revision ${s.revision} remains unsaved.`);}
  else{s.online=true;say('Reconnected · query, selected survey and draft retained.');}
  updateRecovery();record('request-resolved',{id:job.id,kind,fail:job.fail,ackRevision:s.ackRevision,draftRevision:s.revision});
 },job.delay);
}
function cancelRequest(){if(!state.pending)return;const job=state.pending;state.pending=null;if(job.kind==='search')state.searchStatus='idle';if(job.kind==='save')state.saveStatus='canceled';say(`Canceled request ${job.id}; entered work retained. Late completion is ignored.`);updateRecovery();record('request-cancel',{id:job.id});}
function feedbackView(){return head('Beacon calibration','700 ms authored response delay')+`<div id="calibrator" class="calibrator"><section class="beacon-panel"><div id="beacon" class="beacon"><span id="beacon-symbol">◇</span><small id="beacon-label">Ready</small></div><span id="selected-channel" class="selected-channel">Amber channel selected</span>${btn('calibrate','Calibrate beacon','class="primary calibrate-button"')}${btn('cancel-calibrate','Cancel calibration','hidden')}</section><section class="calibration-controls"><h3>Choose a channel</h3><label class="channel"><input id="channel-amber" type="radio" name="channel" value="amber" checked><span>◇ Amber · ridge relay</span></label><label class="channel"><input id="channel-cyan" type="radio" name="channel" value="cyan"><span>□ Cyan · valley relay</span></label><hr><label class="check"><input id="feedback-fail" type="checkbox">Fail next calibration</label><div class="feedback-options"><label class="check"><input id="reduce-motion" type="checkbox">Reduce motion</label><label class="check"><input id="sound" type="checkbox">Opt-in sound</label><label class="check"><input id="haptic" type="checkbox">Opt-in haptics</label></div><p id="sensory" class="sensory"></p><p class="hint">API attempts are observable. Hearing and physical vibration have not been verified.</p></section></div><ol id="timeline" class="timeline"></ol>`+status('Press is reversible; completion waits for the simulated response.');}
function feedbackEvent(name,extra={}){state.events.push({name,at:Math.round(performance.now()),...extra});state.events=state.events.slice(-7);record(name,extra);}
function updateFeedback(){const s=state;$('calibrator').classList.toggle('reduced',s.reduced);$('reduce-motion').checked=s.reduced;$('feedback-fail').checked=s.failNext;$('sound').checked=s.sound;$('haptic').checked=s.haptic;$('calibrate').disabled=mode==='corrected'&&Boolean(s.pending);$('calibrate').classList.toggle('pressed',s.pressed);$('cancel-calibrate').hidden=!s.pending;
 $('channel-amber').disabled=$('channel-cyan').disabled=mode==='corrected'&&Boolean(s.pending);$('selected-channel').textContent=(s.channel==='amber'?'◇ Amber':'□ Cyan')+' channel selected';$('sensory').textContent=s.sensory;
 $('beacon').className='beacon '+s.outcome+(s.outcome==='success'&&!s.reduced?' pulse':'');$('beacon-symbol').textContent=s.outcome==='success'?'✓':s.outcome==='failure'?'!':s.pending?'…':'◇';$('beacon-label').textContent=s.pending?'Pending':s.outcome==='success'?'Calibrated':s.outcome==='failure'?(mode==='problem'?'':'Failed'):'Ready';
 $('timeline').innerHTML=s.events.length?s.events.map(e=>`<li><strong>${esc(e.name)}</strong> · ${e.at} ms${e.elapsed!==undefined?' · response after '+e.elapsed+' ms':''}</li>`).join(''):'<li>No activation yet. Event times come from this browser’s clock.</li>';
}
function prepareAudio(){if(!state.sound)return;try{audioContext??=new (window.AudioContext||window.webkitAudioContext)();audioContext.resume().catch(()=>{});}catch{state.sensory='Audio unavailable; visible outcome remains.';}}
function sensoryFeedback(failed){const messages=[];if(state.sound){try{if(!audioContext||audioContext.state!=='running')throw Error('inactive');const oscillator=audioContext.createOscillator(),gain=audioContext.createGain();gain.gain.value=.035;oscillator.frequency.value=failed?180:540;oscillator.connect(gain).connect(audioContext.destination);oscillator.start();oscillator.stop(audioContext.currentTime+.08);messages.push('Audio scheduled; hearing unverified.');}catch{messages.push('Audio unavailable; text remains.');}}else messages.push('Audio off.');if(state.haptic){try{const result=typeof navigator.vibrate==='function'?navigator.vibrate(failed?[30,40,30]:30):false;messages.push(result?'Vibration API accepted; physical sensation unverified.':'Vibration unavailable/rejected; text remains.');}catch{messages.push('Vibration unavailable; text remains.');}}else messages.push('Haptics off.');state.sensory=messages.join(' ');}
function calibrate(){const s=state;if(mode==='corrected'&&s.pending)return;prepareAudio();const job={id:++s.nextId,channel:s.channel,fail:s.failNext,start:performance.now()},thisEpoch=epoch;s.failNext=false;s.pending=job;s.requests++;s.outcome='idle';feedbackEvent('Activation accepted',{id:job.id,channel:job.channel});say(mode==='problem'?'✓ Completed! (before a result exists)':'Calibrating '+job.channel+' channel…','busy');updateFeedback();
 setTimeout(()=>{if(thisEpoch!==epoch)return;if(mode==='corrected'&&s.pending?.id!==job.id){feedbackEvent('Late response ignored',{id:job.id});updateFeedback();return;}s.pending=null;s.outcome=job.fail?'failure':'success';if(job.fail)s.failures++;else s.successes++;const elapsed=Math.round(performance.now()-job.start);feedbackEvent(job.fail?'Failure acknowledged':'Success acknowledged',{id:job.id,elapsed});say(job.fail?(mode==='corrected'?'! Calibration failed: relay did not answer. Retry keeps your channel.':'Something happened.'):'✓ Beacon calibrated · '+job.channel+' channel.',job.fail?'error':'');sensoryFeedback(job.fail);updateFeedback();},F.delayMs);
}
function action(id,event){record('activate',{id});const s=state;
 if(id==='modal-cancel'){closeModal(true);return;}if(id==='modal-dismiss'){closeModal();if(lab.id==='input'){s.modal=false;s.owner='notice';s.last='dismiss consumed';updateInput();say('Notice dismissed · no arena action.');}return;}
 if(lab.id==='input'){
  if(id==='attack'||id==='purchase'){worldAction(id==='attack'?'attack':'purchases','explicit button');return;}
  if(id==='open-notice'){s.modal=true;if(mode==='corrected')s.armed=false;if(mode==='problem'){$('arena').insertAdjacentHTML('beforeend',`<div class="fault-overlay" role="group" aria-label="Faulty notice"><div><h3>Trail notice</h3><p>Dismiss this notice. Its event will bubble into ${s.dismissTarget==='attack'?'attack':'demo purchase'}.</p>${btn('fault-dismiss','Dismiss notice')}</div></div>`);$('fault-dismiss').focus();}else openModal('Trail notice','<p>Dismiss owns this gesture. The encounter remains inert until close.</p>',btn('modal-dismiss','Dismiss notice')+btn('modal-cancel','Cancel'),$('open-notice'),()=>{s.modal=false;s.owner='notice';s.last='cancel consumed';updateInput();});return;}
  if(id==='fault-dismiss'){$('arena').querySelector('.fault-overlay')?.remove();s.modal=false;$('open-notice').focus();return;}
 }
 if(lab.id==='overload'){
  if(id==='burst'){s.delivered=true;say('Nine notices delivered once · 1 hazard, 1 quest, 3 rewards, 3 chat, 1 ambient cue.');}
  if(id==='advance-clock'){s.clock+=6;say(mode==='problem'?'All notices expired, including unclaimed rewards.':'Ambient cue expired; chat in history; quest and rewards retained.');}
  if(id==='claim-rewards'&&!s.claimed){s.claimed=true;s.shards=20;say('✓ Claimed 20 shards once.');}
  if(id==='ack-hazard'){s.ack=true;say('Hazard acknowledged; objective retained.');}if(id==='toggle-chat')s.drawer=s.drawer?'':'chat';updateOverload();return;
 }
 if(lab.id==='decisions'){
  if(id.startsWith('inspect-')){s.selected=id.slice(8);updateDecisions();say(`Inspecting ${F.stats[s.selected].name}.`);return;}
  if(id==='equip'){if(s.selected==='crafted'&&!s.crafted)return;s.equipped=s.selected;updateDecisions();say(`✓ Equipped ${F.stats[s.selected].name}; comparison recomputed.`);return;}
  if(id==='gather-ore'&&s.ore<3){s.ore++;updateDecisions();say('Gathered 1 ore · recipe materials now available.');return;}
  if(id==='craft'){if(mode==='corrected'&&(s.crafted||s.ore<3||s.fiber<2))return;s.ore-=3;s.fiber-=2;s.crafted=true;updateDecisions();$('equip')?.focus();say(mode==='corrected'?'✓ Crafted once · 3 ore and 2 fiber consumed.':'Problem crafted despite missing ore; stock is negative.',mode==='problem'?'error':'');return;}
  if(id==='toggle-shop'){s.shop=!s.shop;updateDecisions();return;}
  if(id.startsWith('shop-')){const item=id.slice(5);if(mode==='problem'){s.coins-={reed:10,iron:15,solar:25,charm:20}[item];updateDecisions();say('Problem bought an owned/locked item without validation.','error');return;}
   if(item==='reed'||item==='iron'){s.equipped=item;updateDecisions();$('toggle-shop').focus();say('✓ Owned item equipped; no currency spent.');return;}
   if(item==='charm'&&!s.charm&&s.coins>=20){openModal('Review demo purchase','<p><strong>Copper charm · quantity 1</strong></p><p>Cost: 20 demo coins. Balance: 30 → 10.</p><p class="hint">This changes only the local fixture.</p>',btn('modal-cancel','Cancel')+btn('confirm-charm','Confirm · 20 coins','class="primary"'),$('shop-charm'));return;}
  }
  if(id==='confirm-charm'){if(!s.charm&&s.coins>=20){s.charm=true;s.coins-=20;}closeModal();updateDecisions();$('toggle-shop').focus();say('✓ Copper charm owned · 20 demo coins spent once.');return;}
 }
 if(lab.id==='adaptation'){
  if(id==='restore-editor'){restoreEditor();return;}if(id==='review-dispatch'){captureEditing();s.reviews++;openModal('Review dispatch',`<p>Route: <strong>${s.route==='east'?'East ridge':'West valley'}</strong></p><p>${s.note?esc(s.note):'No note entered.'}</p>`,btn('modal-cancel','Keep editing')+btn('confirm-dispatch','Confirm local dispatch','class="primary"'),$('dispatch-note'),restoreEditor);return;}if(id==='confirm-dispatch'){closeModal();restoreEditor();say('✓ Local dispatch reviewed; draft and route retained.');return;}
 }
 if(lab.id==='recovery'){
  if(['search','save','reconnect'].includes(id)){request(id);return;}if(id==='cancel-request'){cancelRequest();return;}
  if(id==='disconnect'){if(s.pending)cancelRequest();s.online=false;if(mode==='problem'){s.draft='';s.query='';s.selected=null;$('survey-draft').value='';$('search-query').value='';}updateRecovery();say(mode==='corrected'?'Offline · query, selected survey and draft retained. Reconnect when ready.':'Disconnected · problem cleared entered work.','error');return;}
  if(id.startsWith('result-')){s.selected=s.results[Number(id.slice(7))];updateRecovery();say('Selected '+s.selected+'.');return;}
 }
 if(lab.id==='feedback'){
  if(id==='calibrate'){if(mode==='corrected')calibrate();return;}
  if(id==='cancel-calibrate'){if(!s.pending)return;feedbackEvent('Canceled',{id:s.pending.id});s.pending=null;s.outcome='idle';say('Canceled; selected channel retained; late response ignored.');updateFeedback();return;}
 }
}
$('specimen').addEventListener('click',e=>{const button=e.target.closest('[data-action]');if(button&&!button.disabled)action(button.dataset.action,e);});
$('specimen').addEventListener('input',e=>{const id=e.target.id;
 if(lab.id==='input'&&id==='radio-note'){state.note=e.target.value;state.owner='radio note';state.last='text edit';updateInput();}
 if(lab.id==='adaptation'&&id==='dispatch-note'){state.note=e.target.value;captureEditing();}
 if(lab.id==='recovery'){if(id==='search-query')state.query=e.target.value;if(id==='survey-draft'){state.draft=e.target.value;state.revision++;updateRecovery();}}
});
$('specimen').addEventListener('change',e=>{const id=e.target.id;
 if(lab.id==='input'&&id==='dismiss-target')state.dismissTarget=e.target.value;if(lab.id==='input'&&id==='polling'){state.polling=e.target.checked;updateInput();}
 if(lab.id==='adaptation'){if(id.startsWith('route-')){state.route=e.target.value;updateAdaptation();}else{if(id==='keyboard-model')state.keyboard=e.target.checked;if(id==='long-labels')state.long=e.target.checked;if(id==='large-text')state.scale=e.target.checked?2:1;adaptChange();}}
 if(lab.id==='recovery'){if(id==='fail-next')state.failNext=e.target.checked;if(id==='slow-next')state.slowNext=e.target.checked;updateRecovery();}
 if(lab.id==='feedback'){if(id.startsWith('channel-')){state.channel=e.target.value;state.outcome='idle';feedbackEvent('Selection changed',{channel:state.channel});say('Channel selected; calibration still requires activation.');}if(id==='feedback-fail')state.failNext=e.target.checked;if(id==='reduce-motion')state.reduced=e.target.checked;if(id==='sound')state.sound=e.target.checked;if(id==='haptic')state.haptic=e.target.checked;updateFeedback();}
});
$('specimen').addEventListener('keydown',e=>{
 if(lab.id==='input'&&['a','p'].includes(e.key.toLowerCase())){const editable=e.target.matches('input,textarea,select')||e.target.isContentEditable;
  if(mode==='corrected'&&(document.activeElement!==$('arena')||editable||e.isComposing||e.repeat||e.ctrlKey||e.altKey||e.metaKey||state.modal||$('modal').open||!state.armed))return;if(mode==='corrected')e.preventDefault();if(!(state.polling&&e.key.toLowerCase()==='a'))worldAction(e.key.toLowerCase()==='a'?'attack':'purchases','shortcut '+e.key+(e.repeat?' repeat':''));}
 if(lab.id==='input'&&mode==='problem'&&e.key==='Escape'&&state.modal){$('arena').querySelector('.fault-overlay')?.remove();state.modal=false;$('open-notice').focus();}
 if(lab.id==='recovery'&&e.target.id==='search-query'&&e.key==='Enter'){e.preventDefault();request('search');}
 if(lab.id==='feedback'&&e.target.id==='calibrate'){if(e.repeat){e.preventDefault();return;}if(e.key===' '||e.key==='Enter'){state.pressed=true;feedbackEvent('Keyboard pressed');updateFeedback();}}
 if(e.key==='Escape'){if(lab.id==='feedback'&&state.pending)action('cancel-calibrate',e);if(lab.id==='recovery'&&state.pending)cancelRequest();}
});
$('specimen').addEventListener('keyup',e=>{if(lab.id==='feedback'&&e.target.id==='calibrate'){state.pressed=false;updateFeedback();}});
$('specimen').addEventListener('pointerdown',e=>{if(lab.id==='feedback'&&e.target.closest('#calibrate')&&!$('calibrate').disabled){state.pressed=true;feedbackEvent('Pointer pressed');updateFeedback();if(mode==='problem')calibrate();}});
function endPress(e){if(lab.id==='feedback'&&state.pressed){state.pressed=false;feedbackEvent(e.type==='pointercancel'?'Pointer canceled':'Pointer released');updateFeedback();}}
window.addEventListener('pointerup',endPress);window.addEventListener('pointercancel',endPress);window.addEventListener('blur',endPress);
window.addEventListener('keydown',e=>{if(lab.id==='input'&&e.key.toLowerCase()==='a'&&!e.isComposing&&!e.ctrlKey&&!e.altKey&&!e.metaKey){state.physicalA=true;updateInput();}});
window.addEventListener('keyup',e=>{if(lab.id==='input'&&e.key.toLowerCase()==='a'){state.physicalA=false;state.armed=true;updateInput();}});
window.addEventListener('blur',()=>{if(lab.id==='input'){state.physicalA=false;state.armed=false;updateInput();}});
setInterval(()=>{if(lab.id!=='input'||!state.polling||!state.physicalA)return;if(mode==='corrected'&&(state.modal||$('modal').open||!state.armed||document.activeElement!==$('arena')))return;state.polledFrames++;worldAction('attack','polled held A');},200);
$('labs').addEventListener('click',e=>{const b=e.target.closest('[data-lab]');if(b)switchLab(LABS.find(x=>x.id===b.dataset.lab));});
$('labs').addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();let i=LABS.indexOf(lab);i=e.key==='Home'?0:e.key==='End'?5:(i+(e.key==='ArrowRight'?1:-1)+6)%6;switchLab(LABS[i]);$('lab-'+lab.id).focus();}});
$('problem').addEventListener('click',()=>switchLab(lab,'problem'));$('corrected').addEventListener('click',()=>switchLab(lab,'corrected'));$('reset').addEventListener('click',()=>switchLab(lab));
$('copy').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(lab.instruction);$('copy-status').textContent='Instruction copied.';}catch{$('copy-status').textContent='Clipboard unavailable. Select and copy the instruction text.';}});
let resizeFrame=0;function onResize(){cancelAnimationFrame(resizeFrame);resizeFrame=requestAnimationFrame(()=>{if(lab.id!=='adaptation')return;if(mode==='problem'){state.focusLost++;state.route='east';state.editing={start:0,end:0,direction:'none'};bindEditor();}const available=Math.max(180,(window.visualViewport?.height||innerHeight)-180);$('editor-surface')?.style.setProperty('--available-editor',available+'px');updateAdaptation();});}
window.addEventListener('resize',onResize);window.visualViewport?.addEventListener('resize',onResize);
matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',e=>{if(lab.id==='feedback'){state.reduced=e.matches;updateFeedback();}});
window.interactionSnapshot=()=>({version:F.version,lab:lab.id,mode,state:structuredClone(state),focus:document.activeElement?.id||'',modal:$('modal').open,trace:structuredClone(trace)});
state=initial();render();record('loaded');
})();
