import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
import {startServer} from './serve.mjs';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_CORE_PATH||'playwright-core');
const root=path.dirname(fileURLToPath(import.meta.url)),runId=process.env.QA_RUN_ID||'final';assert.match(runId,/^[a-z0-9-]+$/);
const out=path.join(root,'checks',runId),captures=path.join(root,'captures',runId);fs.mkdirSync(out,{recursive:true});fs.mkdirSync(captures,{recursive:true});
const files=['index.html','data.js','app.js','style.css','serve.mjs','browser-checks.mjs'];fs.mkdirSync(path.join(out,'source'),{recursive:true});for(const f of files)fs.copyFileSync(path.join(root,f),path.join(out,'source',f));
const sha=f=>crypto.createHash('sha256').update(fs.readFileSync(f)).digest('hex');
const server=await startServer(0),base=`http://127.0.0.1:${server.address().port}`,url=base+'/research/interaction_corrections_v1/';
const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});
const context=await browser.newContext({viewport:{width:1165,height:747},deviceScaleFactor:1});let page=await context.newPage();page.setDefaultTimeout(5000);
const results=[],shots=[],errors=[],actions=[],geometry=[];
function observe(p){p.on('pageerror',e=>errors.push({type:'pageerror',message:e.message}));p.on('console',m=>{if(m.type()==='error')errors.push({type:'console',message:m.text()});});p.on('requestfailed',r=>errors.push({type:'requestfailed',path:new URL(r.url()).pathname,message:r.failure()?.errorText}));}observe(page);
const snap=()=>page.evaluate(()=>window.interactionSnapshot());
async function click(id){actions.push({input:'click',id});await page.locator('#'+id).click();}
async function key(value){actions.push({input:'key',value});await page.keyboard.press(value);}
async function type(id,text){actions.push({input:'fill',id,text});await page.locator('#'+id).fill(text);}
let freshId=0;
async function fresh(lab,mode='corrected',viewport){if(viewport)await page.setViewportSize(viewport);await page.goto(url+'?case='+(++freshId)+'#'+lab);await page.waitForFunction(()=>Boolean(window.interactionSnapshot));if(mode==='problem')await click('problem');}
async function waitDone(){await page.waitForFunction(()=>!window.interactionSnapshot().state.pending);}
async function shot(name,kind='specimen'){const filename=name+'.png',f=path.join(captures,filename);if(kind==='full')await page.screenshot({path:f,fullPage:true});else if(kind==='viewport'){await page.locator('#specimen').scrollIntoViewIfNeeded();await page.screenshot({path:f});}else await page.locator('#specimen').screenshot({path:f});shots.push({file:`captures/${runId}/${filename}`,kind,viewport:page.viewportSize(),sha256:sha(f),state:await snap()});}
async function check(name,fn){const start=Date.now();try{const note=await fn();results.push({name,status:'pass',elapsedMs:Date.now()-start,note:note||''});}catch(e){results.push({name,status:'fail',elapsedMs:Date.now()-start,error:String(e.message)});try{await shot('failure-'+name,'full');}catch{}console.log('FAIL '+name+': '+e.message);}}
async function fit(label){const g=await page.evaluate(()=>{const r=document.querySelector('#specimen').getBoundingClientRect();const controls=[...document.querySelectorAll('#specimen button,#specimen input,#specimen textarea,#specimen select')].filter(n=>n.getClientRects().length&&!n.closest('[hidden]'));return {width:innerWidth,height:innerHeight,pageOverflow:document.documentElement.scrollWidth-document.documentElement.clientWidth,specimen:{x:r.x,width:r.width},outside:controls.filter(n=>{const b=n.getBoundingClientRect();return b.left<r.left-1||b.right>r.right+1;}).map(n=>n.id),targets:controls.filter(n=>n.tagName==='BUTTON').map(n=>({id:n.id,height:n.getBoundingClientRect().height})),focus:document.activeElement.id};});geometry.push({label,...g});assert(g.pageOverflow<=1,JSON.stringify(g));assert.deepEqual(g.outside,[]);assert(g.targets.every(x=>x.height>=43));}
try{
await check('input-problem-dismiss-attack-and-purchase',async()=>{await fresh('input','problem');await click('open-notice');await click('fault-dismiss');assert.equal((await snap()).state.attack,1);await page.locator('#dismiss-target').selectOption('purchases');await click('open-notice');await click('fault-dismiss');assert.equal((await snap()).state.purchases,1);await shot('input-problem-dismiss');});
await check('input-problem-typing-and-repeat-reproduce',async()=>{await fresh('input','problem');await page.locator('#radio-note').focus();await page.keyboard.type('ap');let s=await snap();assert.equal(s.state.attack,1);assert.equal(s.state.purchases,1);assert.equal(s.state.note,'ap');await page.locator('#arena').focus();await page.keyboard.down('a');await page.keyboard.down('a');await page.keyboard.up('a');assert.equal((await snap()).state.attack,3);});
await check('input-corrected-modal-inert-tab-escape-return',async()=>{await fresh('input');await click('open-notice');assert((await snap()).modal);assert.equal((await snap()).focus,'modal-dismiss');await key('Shift+Tab');assert.equal((await snap()).focus,'modal-cancel');await key('Tab');assert.equal((await snap()).focus,'modal-dismiss');const attacks=(await snap()).state.attack;await page.locator('#attack').click({force:true});assert.equal((await snap()).state.attack,attacks);await key('Escape');assert.equal((await snap()).focus,'open-notice');assert.equal((await snap()).state.attack,0);assert.equal((await snap()).state.purchases,0);await page.locator('#dismiss-target').selectOption('purchases');await click('open-notice');await click('modal-dismiss');assert.equal((await snap()).state.purchases,0);});
await check('input-corrected-editing-modifiers-repeat-focus-only',async()=>{await fresh('input');await page.locator('#radio-note').focus();await page.keyboard.type('ap');assert.equal((await snap()).state.note,'ap');assert.equal((await snap()).state.attack,0);await page.locator('#arena').focus();await key('Control+a');assert.equal((await snap()).state.attack,0);await page.keyboard.down('a');await page.keyboard.down('a');await page.keyboard.up('a');assert.equal((await snap()).state.attack,1);await key('p');assert.equal((await snap()).state.purchases,1);await page.locator('#attack').focus();await key('Enter');await key('Space');assert.equal((await snap()).state.attack,3);});
await check('input-polled-held-problem-reproduce',async()=>{await fresh('input','problem');await page.locator('#polling').check();await page.locator('#arena').focus();await page.keyboard.down('a');await page.waitForTimeout(250);await click('open-notice');const n=(await snap()).state.attack;await page.waitForTimeout(450);assert((await snap()).state.attack>n);await key('Escape');await page.keyboard.up('a');});
await check('input-polled-held-corrected-gate-release-rearm',async()=>{await fresh('input');await page.locator('#polling').check();await page.locator('#arena').focus();await page.keyboard.down('a');await page.waitForTimeout(250);assert((await snap()).state.polledFrames>=1);await click('open-notice');const n=(await snap()).state.attack;await page.waitForTimeout(450);assert.equal((await snap()).state.attack,n);await key('Escape');await page.locator('#arena').focus();await page.waitForTimeout(450);assert.equal((await snap()).state.attack,n);await page.keyboard.up('a');await page.keyboard.down('a');await page.waitForTimeout(250);await page.keyboard.up('a');assert((await snap()).state.attack>n);await shot('input-corrected-rearmed');});
await check('overload-problem-burst-and-loss',async()=>{await fresh('overload','problem');await click('burst');assert.equal(await page.locator('.fault-stack .notice').count(),9);await shot('overload-problem-burst');await click('advance-clock');assert.equal(await page.locator('.fault-stack .notice').count(),0);assert.equal((await snap()).state.shards,0);});
await check('overload-corrected-group-expiry-repeat-claim',async()=>{await fresh('overload');await click('burst');await click('burst');assert.equal(await page.locator('.notice.hazard').count(),1);await click('toggle-chat');assert(await page.locator('#chat-history').isVisible());await click('advance-clock');assert(await page.locator('.notice.quest').isVisible());assert(await page.locator('#claim-rewards').isEnabled());assert.equal(await page.locator('#chat-history li').count(),3);await shot('overload-corrected-expired');await click('claim-rewards');assert(await page.locator('#claim-rewards').isDisabled());await click('burst');assert.equal((await snap()).state.shards,20);await click('ack-hazard');assert.equal(await page.locator('.notice.hazard').count(),0);assert.equal((await snap()).focus,'toggle-chat');});
await check('overload-cue-expiry-versus-action-deadline',async()=>{await fresh('overload');await click('burst');await click('toggle-chat');await click('advance-clock');assert(await page.locator('#join-invite').isEnabled());await click('advance-clock');assert(await page.locator('#join-invite').isDisabled());assert((await page.locator('#chat-history').textContent()).includes('expired'));await shot('overload-corrected-deadline');await fresh('overload');await click('burst');await click('toggle-chat');await click('advance-clock');await click('join-invite');assert((await snap()).state.inviteJoined);assert(await page.locator('#join-invite').isDisabled());});
await check('decisions-problem-negative-stock-and-owned-buy',async()=>{await fresh('decisions','problem');await click('inspect-crafted');await click('craft');assert.equal((await snap()).state.ore,-1);await shot('decisions-problem-negative');await click('toggle-shop');await click('shop-iron');assert.equal((await snap()).state.coins,15);await click('shop-solar');assert.equal((await snap()).state.coins,-10);});
await check('decisions-corrected-deltas-equip-recompute',async()=>{await fresh('decisions');assert.equal(await page.locator('#delta-attack').textContent(),'+6');assert.equal(await page.locator('#delta-guard').textContent(),'-2');assert.equal(await page.locator('#delta-weight').textContent(),'+2');await click('equip');assert.equal((await snap()).state.equipped,'iron');assert.equal((await snap()).focus,'inspect-iron');assert.equal(await page.locator('#delta-attack').textContent(),'0');await key('Enter');assert.equal((await snap()).state.equipped,'iron');await click('inspect-reed');assert.equal(await page.locator('#delta-attack').textContent(),'-6');await click('inspect-crafted');assert.equal(await page.locator('#delta-weight').textContent(),'-3');});
await check('decisions-corrected-missing-gather-craft-once',async()=>{await fresh('decisions');await click('inspect-crafted');assert(await page.locator('#craft').isDisabled());assert((await page.locator('.bill').textContent()).includes('Missing 1 ore'));await click('gather-ore');await click('craft');let s=(await snap()).state;assert.equal(s.ore,0);assert.equal(s.fiber,0);assert(s.crafted);assert.equal(await page.locator('#craft').count(),0);await click('equip');await key('Enter');s=(await snap()).state;assert.equal(s.equipped,'crafted');assert.equal(s.ore,0);await shot('decisions-corrected-crafted');});
await check('decisions-shop-states-cancel-confirm-repeat',async()=>{await fresh('decisions');await click('toggle-shop');assert(await page.locator('#shop-reed').isDisabled());assert(await page.locator('#shop-iron').isEnabled());assert(await page.locator('#shop-solar').isDisabled());await click('shop-iron');assert.equal((await snap()).state.coins,30);await click('shop-charm');assert.equal((await snap()).focus,'modal-cancel');await key('Escape');assert.equal((await snap()).focus,'shop-charm');assert.equal((await snap()).state.coins,30);await click('shop-charm');await shot('decisions-corrected-review','full');await click('confirm-charm');assert.equal((await snap()).state.coins,10);assert((await snap()).state.charm);assert(await page.locator('#shop-charm').isDisabled());await key('Enter');assert.equal((await snap()).state.coins,10);});
await check('decisions-shop-disclosure-hidden-and-focus',async()=>{await fresh('decisions');assert.equal(await page.locator('#shop-list').isVisible(),false);await click('toggle-shop');assert(await page.locator('#shop-list').isVisible());await click('toggle-shop');assert.equal(await page.locator('#shop-list').isVisible(),false);assert.equal((await snap()).focus,'toggle-shop');});
await check('adaptation-problem-rebuild-loss',async()=>{await fresh('adaptation','problem');await page.locator('#route-west').check();await type('dispatch-note','Meet at the north relay.');await page.locator('#dispatch-note').focus();await key('Control+a');await page.locator('#keyboard-model').check();assert.equal((await snap()).state.route,'east');assert.notEqual((await snap()).focus,'dispatch-note');assert.equal((await snap()).state.editing.start,(await snap()).state.editing.end);await shot('adaptation-problem-clipped');});
await check('adaptation-stable-route-field-range-rotation',async()=>{await fresh('adaptation','corrected',{width:390,height:844});await page.locator('#route-west').check();await type('dispatch-note','Meet at the north relay.');await page.locator('#dispatch-note').focus();await key('Control+a');const before=await snap();assert.equal(before.state.editing.end,24);await page.setViewportSize({width:844,height:390});await page.waitForTimeout(80);const after=await snap();assert.equal(after.focus,'dispatch-note');assert.equal(after.state.route,'west');assert.deepEqual(after.state.editing,before.state.editing);assert.equal(await page.locator('#dispatch-note').inputValue(),before.state.note);await fit('adaptation-rotated');await shot('adaptation-corrected-landscape');});
await check('adaptation-keyboard-long-200-percent-cancel-range',async()=>{await fresh('adaptation','corrected',{width:390,height:844});await page.locator('#route-west').check();await type('dispatch-note','Meet at the north relay.');await page.locator('#dispatch-note').focus();await key('Control+a');const range=(await snap()).state.editing;await page.locator('#keyboard-model').check();assert.equal((await snap()).focus,'dispatch-note');await page.locator('#long-labels').check();await page.locator('#large-text').check();assert.deepEqual((await snap()).state.editing,range);await fit('adaptation-200-long-keyboard');await shot('adaptation-corrected-text-keyboard');await click('review-dispatch');await key('Escape');assert.equal((await snap()).focus,'dispatch-note');assert.deepEqual((await snap()).state.editing,range);assert.equal((await snap()).state.route,'west');});
await check('recovery-problem-save-failure-and-disconnect-loss',async()=>{await fresh('recovery','problem');await type('survey-draft','Keep this work.');await page.locator('#fail-next').check();await click('save');await waitDone();assert.equal((await snap()).state.draft,'');await type('survey-draft','New draft.');await click('disconnect');assert.equal((await snap()).state.draft,'');await shot('recovery-problem-lost');});
await check('recovery-loading-empty-query-and-success',async()=>{await fresh('recovery');await type('search-query','zzz');await click('search');assert.equal((await snap()).state.searchStatus,'pending');assert(await page.locator('#search').isDisabled());await shot('recovery-corrected-loading');await waitDone();assert.equal((await snap()).state.searchStatus,'empty');assert((await page.locator('#search-message').textContent()).includes('zzz'));assert.equal(await page.locator('#search-query').inputValue(),'zzz');await shot('recovery-corrected-empty');await type('search-query','relay');await key('Enter');await waitDone();assert.equal((await snap()).state.results.length,2);await click('result-1');});
await check('recovery-duplicate-pending-key-and-cancel-late',async()=>{await fresh('recovery');await type('search-query','relay');await page.locator('#search-query').focus();await key('Enter');await key('Enter');assert.equal((await snap()).state.requests,1);await click('cancel-request');await page.waitForTimeout(750);assert.equal((await snap()).state.results.length,0);assert.equal((await snap()).state.ignored,1);assert.equal((await snap()).state.query,'relay');await click('search');await waitDone();assert.equal((await snap()).state.results.length,2);});
await check('recovery-save-failure-retry-and-edit-in-flight',async()=>{await fresh('recovery');await type('survey-draft','Revision one.');await page.locator('#fail-next').check();await click('save');await waitDone();assert.equal((await snap()).state.draft,'Revision one.');assert.equal((await snap()).state.ackRevision,0);await shot('recovery-corrected-failed-save');await click('save');const submitted=(await snap()).state.pending.revision;await type('survey-draft','Revision two, entered during saving.');await waitDone();let s=(await snap()).state;assert.equal(s.ackRevision,submitted);assert(s.revision>s.ackRevision);assert.equal(s.draft,'Revision two, entered during saving.');assert.equal(s.ackDraft,'Revision one.');await click('save');await waitDone();s=(await snap()).state;assert.equal(s.ackRevision,s.revision);assert.equal(s.ackDraft,s.draft);});
await check('recovery-out-of-order-old-reply-cannot-roll-back',async()=>{await fresh('recovery');await type('survey-draft','Older draft.');await page.locator('#slow-next').check();await click('save');const old=(await snap()).state.pending.id;await click('cancel-request');await type('survey-draft','Newer draft.');await click('save');await waitDone();const before=(await snap()).state;assert.notEqual(before.ackRequest,old);await page.waitForTimeout(950);const after=(await snap()).state;assert.equal(after.ignored,1);assert.equal(after.ackRequest,before.ackRequest);assert.equal(after.ackDraft,'Newer draft.');assert.equal(after.draft,'Newer draft.');await shot('recovery-corrected-out-of-order');});
await check('recovery-disconnect-reconnect-fail-cancel-retain',async()=>{await fresh('recovery');await type('search-query','relay');await click('search');await waitDone();await click('result-1');await type('survey-draft','Draft retained offline.');await click('disconnect');let s=(await snap()).state;assert.equal(s.query,'relay');assert.equal(s.selected,'Valley relay repair');assert.equal(s.draft,'Draft retained offline.');await page.locator('#fail-next').check();await click('reconnect');await waitDone();assert.equal((await snap()).state.online,false);await click('reconnect');await click('cancel-request');await page.waitForTimeout(750);assert.equal((await snap()).state.online,false);await click('reconnect');await waitDone();assert.equal((await snap()).state.draft,'Draft retained offline.');assert.equal((await snap()).state.selected,'Valley relay repair');});
await check('feedback-problem-down-commits-release-away',async()=>{await fresh('feedback','problem');await page.locator('#calibrate').scrollIntoViewIfNeeded();const b=await page.locator('#calibrate').boundingBox();await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.down();assert.equal((await snap()).state.requests,1);assert((await page.locator('#runtime-status').textContent()).includes('Completed'));await page.mouse.move(b.x+b.width+30,b.y+b.height+30);await page.mouse.up();await waitDone();assert.equal((await snap()).state.successes,1);await shot('feedback-problem-premature');});
await check('feedback-corrected-pressed-release-away-aborts',async()=>{await fresh('feedback');await page.locator('#calibrate').scrollIntoViewIfNeeded();const b=await page.locator('#calibrate').boundingBox();await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.down();assert((await snap()).state.pressed);assert.equal((await snap()).state.requests,0);await shot('feedback-corrected-pressed');await page.mouse.move(b.x+b.width+30,b.y+b.height+30);await page.mouse.up();assert.equal((await snap()).state.requests,0);assert.equal((await snap()).state.pressed,false);});
await check('feedback-selection-keyboard-pending-success-and-repeat',async()=>{await fresh('feedback');await page.locator('#channel-cyan').focus();await key('Space');assert.equal((await snap()).state.channel,'cyan');await page.locator('#calibrate').focus();await key('Enter');assert.equal((await snap()).state.requests,1);assert.equal((await snap()).state.successes,0);await key('Enter');assert.equal((await snap()).state.requests,1);await waitDone();assert.equal((await snap()).state.successes,1);assert((await page.locator('#runtime-status').textContent()).includes('cyan'));const e=(await snap()).state.events.find(e=>e.name==='Success acknowledged');assert(e.elapsed>=650);await page.locator('#calibrate').focus();await key('Space');await waitDone();assert.equal((await snap()).state.successes,2);});
await check('feedback-failure-retry-cancel-stale-and-motion',async()=>{await fresh('feedback');await page.locator('#feedback-fail').check();await click('calibrate');await waitDone();assert.equal((await snap()).state.failures,1);assert.equal(await page.locator('#beacon-symbol').textContent(),'!');assert((await page.locator('#runtime-status').textContent()).includes('relay did not answer'));await shot('feedback-corrected-failure');await click('calibrate');await key('Escape');await page.waitForTimeout(750);assert.equal((await snap()).state.successes,0);assert.equal((await snap()).state.channel,'amber');await page.locator('#reduce-motion').check();await click('calibrate');await waitDone();assert.equal((await snap()).state.successes,1);assert.equal(await page.locator('#beacon').evaluate(n=>getComputedStyle(n).animationName),'none');await shot('feedback-corrected-reduced');});
await check('feedback-system-reduced-motion-and-sensory-attempts',async()=>{await fresh('feedback');await page.emulateMedia({reducedMotion:'reduce'});await page.waitForFunction(()=>window.interactionSnapshot().state.reduced);await page.locator('#sound').check();await page.locator('#haptic').check();await click('calibrate');await waitDone();const text=await page.locator('#sensory').textContent();assert(/Audio (scheduled|unavailable)/.test(text));assert(/Vibration (API accepted|unavailable)/.test(text));assert.equal(await page.locator('#beacon').evaluate(n=>getComputedStyle(n).animationName),'none');await page.emulateMedia({reducedMotion:'no-preference'});return 'API scheduling/unsupported path observed; hearing and physical sensation unverified.';});
await check('mode-lab-switch-invalidates-pending-and-nav-keyboard',async()=>{await fresh('recovery');await type('survey-draft','Pending draft');await click('save');await click('lab-input');await page.waitForTimeout(750);assert.equal((await snap()).lab,'input');assert.equal((await snap()).state.attack,0);await page.locator('#lab-input').focus();await key('ArrowRight');assert.equal((await snap()).lab,'overload');assert.equal((await snap()).focus,'lab-overload');await key('End');assert.equal((await snap()).lab,'feedback');await key('Home');assert.equal((await snap()).lab,'input');});
for(const viewport of [{width:1165,height:747},{width:768,height:900},{width:390,height:844},{width:844,height:390},{width:320,height:720}]){
 for(const lab of ['input','overload','decisions','adaptation','recovery','feedback'])await check(`render-${lab}-${viewport.width}x${viewport.height}`,async()=>{await fresh(lab,'corrected',viewport);if(lab==='overload')await click('burst');if(lab==='decisions'){await click('inspect-crafted');await click('toggle-shop');}if(lab==='adaptation'){await page.locator('#long-labels').check();await type('dispatch-note','A retained dispatch note.');}if(lab==='recovery'){await type('search-query','zzz');await click('search');await waitDone();await type('survey-draft','The entered work stays here.');}if(lab==='feedback'){await page.locator('#feedback-fail').check();await click('calibrate');await waitDone();}await fit(lab+'-'+viewport.width);if([1165,390,844,320].includes(viewport.width)){await shot(`${lab}-corrected-${viewport.width}x${viewport.height}`);if([1165,390].includes(viewport.width)){await shot(`${lab}-corrected-full-${viewport.width}x${viewport.height}`,'full');await shot(`${lab}-corrected-viewport-${viewport.width}x${viewport.height}`,'viewport');}}});
}
for(const viewport of [{width:1165,height:747},{width:390,height:844}])for(const lab of ['input','overload','decisions','adaptation','recovery','feedback'])await check(`problem-capture-${lab}-${viewport.width}`,async()=>{await fresh(lab,'problem',viewport);if(lab==='overload')await click('burst');if(lab==='decisions')await click('inspect-crafted');if(lab==='adaptation'){await page.locator('#long-labels').check();await type('dispatch-note','A retained dispatch note.');}if(lab==='recovery'){await type('search-query','zzz');await click('search');await waitDone();await type('survey-draft','The entered work stays here.');}if(lab==='feedback'){await page.locator('#feedback-fail').check();await click('calibrate');await waitDone();}await shot(`${lab}-problem-${viewport.width}x${viewport.height}`);await shot(`${lab}-problem-full-${viewport.width}x${viewport.height}`,'full');});
await check('touch-emulation-critical-paths',async()=>{const touch=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1}),p=await touch.newPage();observe(p);await p.goto(url+'#input');await p.locator('#open-notice').tap();await p.locator('#modal-dismiss').tap();assert.equal((await p.evaluate(()=>window.interactionSnapshot())).state.attack,0);await p.locator('#lab-feedback').tap();await p.locator('#channel-cyan').tap();await p.locator('#calibrate').tap();await p.waitForFunction(()=>window.interactionSnapshot().state.successes===1);await touch.close();return 'Chromium touch emulation, not a physical phone or haptic test.';});
await check('local-links-source-bytes-and-console',async()=>{await fresh('input');for(const f of ['index.html','app.js','style.css','data.js']){const r=await fetch(url+f);assert.equal(r.status,200);assert.equal(crypto.createHash('sha256').update(Buffer.from(await r.arrayBuffer())).digest('hex'),sha(path.join(root,f)));}for(const id of ['input','overload','decisions','adaptation','recovery','feedback']){await click('lab-'+id);const r=await fetch(new URL(await page.locator('#reuse a').getAttribute('href'),url));assert.equal(r.status,200);}assert.deepEqual(errors,[]);});
}finally{
 const report={runId,runAt:new Date().toISOString(),baseCommit:'24e2fd2fcd8a0163b3560239b071a48d1188d7c8',artifactType:'authored-demonstrators',environment:{browser:browser.version(),platform:process.platform,headless:true,dpr:1,inputs:['native mouse','native keyboard','Playwright native form input','Chromium emulated touch']},sourceHashes:Object.fromEntries(files.map(f=>[f,sha(path.join(root,f))])),results,errors,limits:['No physical phone/touch/controller/haptic or hearing verification','No native software keyboard, safe-area, IME, speech input or screen-reader run','No true browser zoom; explicit CSS 200% text model only','No Godot/Unreal engine runtime','No real network/backend/purchase/authentication or durable-save service','No human usability study, causal effect, design acceptance or publication','No commit/push, plugin install or Site change']};
 fs.writeFileSync(path.join(out,'results.json'),JSON.stringify(report,null,2)+'\n');fs.writeFileSync(path.join(out,'captures.json'),JSON.stringify(shots,null,2)+'\n');fs.writeFileSync(path.join(out,'actions.json'),JSON.stringify(actions,null,2)+'\n');fs.writeFileSync(path.join(out,'geometry.json'),JSON.stringify(geometry,null,2)+'\n');await browser.close();await new Promise(resolve=>server.close(resolve));
 console.log(JSON.stringify({runId,passed:results.filter(x=>x.status==='pass').length,failed:results.filter(x=>x.status==='fail').length,captures:shots.length,errors:errors.length}));if(results.some(x=>x.status==='fail'))process.exitCode=1;
}
